{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Sales Orders\",\"Ship Trn\",\"Issue Line\",\"Customer\",\"Sales Rep\",\"Sales Order Measures\",\"Calendar\",\"Customer Address\",\"Item\",\"Currency Selection\",\"Last Refreshment\",\"FX FCST rates\",\"Hist_Exch_Rates\",\"Project\",\"BOM\",\"BOM Measures\",\"Item Measures\",\"SO_rep\",\"Revenue Margin Project Mapping\",\"Inventory\",\"Manufacturing Data\",\"Scheduled Receipt\",\"Shipment Inventory Transactions\",\"Measure Selection\",\"MPS Forecast\",\"On Time Delivery Measures\",\"Shipment Targets\",\"Product Hierarchy\",\"Inspections\",\"Manufacturing Requirements\",\"Supply - Demand Measures\",\"Project Code\",\"Quantity / Value Selection\",\"Requisition Lines\",\"Requisition Measures\",\"BOBL Date\",\"Inventory Types\",\"Invoices\",\"Invoice Measures\",\"Cash Receipts\",\"Warehouse\",\"MPS Measures\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.118.621.0 (23.06)"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "expressions": [
      {
        "name": "FX FCST rates",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
          "    sharepoint_FX_FCST_Rates_View = Source{[Schema=\"sharepoint\",Item=\"FX_FCST_Rates_View\"]}[Data],",
          "    #\"Changed Type\" = Table.TransformColumnTypes(sharepoint_FX_FCST_Rates_View,{{\"FX Rate (CAD/USD)\", type number}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "55ea0541-66fe-452f-b580-f9c0b897c801"
      },
      {
        "name": "Hist_Exch_Rates",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
          "    common_Currency_Rates_USD_CAD = Source{[Schema=\"common\",Item=\"Currency_Rates_USD_CAD\"]}[Data]",
          "in",
          "    common_Currency_Rates_USD_CAD"
        ],
        "kind": "m",
        "lineageTag": "1f379b17-b2a1-4add-9ed8-eec721ac74f9"
      },
      {
        "name": "SO_rep",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = #\"Sales Orders\",",
          "    #\"Grouped Rows\" = Table.Group(Source, {\"Sales Order Number\", \"Sales Rep ID\"}, {{\"Count\", each Table.RowCount(_), Int64.Type}}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Grouped Rows\",{\"Count\"})",
          "in",
          "    #\"Removed Columns\""
        ],
        "kind": "m",
        "lineageTag": "35f2cb04-f563-45fa-a96d-d95ab05410e8"
      },
      {
        "name": "Revenue Margin Project Mapping",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
          "    sharepoint_Revenue_Margin_Project_Mapping = Source{[Schema=\"GL\",Item=\"Revenue_Margin_Project_Mapping\"]}[Data]",
          "in",
          "    sharepoint_Revenue_Margin_Project_Mapping"
        ],
        "kind": "m",
        "lineageTag": "f2132c8c-9b53-4b9d-9122-0821592b41f5"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Deltek"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Measures"
      }
    ],
    "relationships": [
      {
        "name": "9d6cee1b-afec-4bbe-9bec-2316c199db0a",
        "fromColumn": "Customer Key",
        "fromTable": "Ship Trn",
        "isActive": false,
        "toColumn": "Customer Key",
        "toTable": "Customer"
      },
      {
        "name": "e01f8d32-5461-4951-9c15-a36918d7db4b",
        "fromColumn": "Customer Key",
        "fromTable": "Sales Orders",
        "toColumn": "Customer Key",
        "toTable": "Customer"
      },
      {
        "name": "f9497cf8-bc01-44a5-b161-cc7d9a5a0063",
        "fromColumn": "Item ID",
        "fromTable": "Sales Orders",
        "toColumn": "Item ID",
        "toTable": "Item"
      },
      {
        "name": "06f13f6e-e13f-4e68-8ecc-0ec87d44b4d3",
        "fromColumn": "Item ID",
        "fromTable": "Issue Line",
        "isActive": false,
        "toColumn": "Item ID",
        "toTable": "Item"
      },
      {
        "name": "fdc2b5b4-3690-49f6-9a6f-7813b8ad95b3",
        "fromColumn": "Order Date",
        "fromTable": "Sales Orders",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "a8dd8506-9832-4190-9fb4-b8aea56ece91",
        "fromColumn": "Sales Rep ID",
        "fromTable": "Sales Orders",
        "toColumn": "Sales Rep ID",
        "toTable": "Sales Rep"
      },
      {
        "name": "039bc4c7-4a1d-4530-a3dd-89dd09a60de1",
        "fromColumn": "SO_LN_KEY",
        "fromTable": "Issue Line",
        "isActive": false,
        "toColumn": "SO_LN_KEY2",
        "toTable": "Sales Orders"
      },
      {
        "name": "f68fc6f4-895b-4835-919f-ceb8210fbc85",
        "fromColumn": "Ship by Date",
        "fromTable": "Sales Orders",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "a867f9e0-b722-4fb4-b86e-a53c4120104c",
        "fromColumn": "Part ID",
        "fromTable": "Inventory",
        "toColumn": "Part ID",
        "toTable": "Item"
      },
      {
        "name": "dd934d10-e2cf-419d-82e6-d73f9ad16176",
        "fromColumn": "Planned Inventory Available Date",
        "fromTable": "Scheduled Receipt",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "c9f1ec65-1d33-4ccd-90d3-fb083347dd12",
        "fromColumn": "Need Date",
        "fromTable": "Manufacturing Data",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "aa2f422a-601e-4f9d-8996-0af2de5139d5",
        "fromColumn": "MO Build Part ID",
        "fromTable": "Manufacturing Data",
        "toColumn": "Part ID",
        "toTable": "Item"
      },
      {
        "name": "8a0c2e5b-1c76-4289-a5e9-55c05ea1d0e1",
        "fromColumn": "Transaction Date",
        "fromTable": "Shipment Inventory Transactions",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "b9156467-ccf7-48fb-89b9-6dd3fa72e6dd",
        "fromColumn": "Part ID",
        "fromTable": "Shipment Inventory Transactions",
        "toColumn": "Part ID",
        "toTable": "Item"
      },
      {
        "name": "4f3e2f8d-fa3b-487c-9826-041ecb88b956",
        "fromColumn": "Shipment Date",
        "fromTable": "Ship Trn",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "04db2ed9-8065-425b-881b-dcf72de6e373",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Date",
        "fromTable": "Shipment Targets",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "49cfe6aa-b1bc-4c02-8b00-d98fa0d6e36a",
        "fromColumn": "Item ID",
        "fromTable": "Inspections",
        "toColumn": "Item ID",
        "toTable": "Item"
      },
      {
        "name": "923e3989-838b-4db6-bdf1-713a0c187e77",
        "fromColumn": "TOP GA Project ID",
        "fromTable": "Product Hierarchy",
        "toColumn": "ProjectK",
        "toTable": "Project Code"
      },
      {
        "name": "81ce37e6-f0aa-438f-981c-f8b55f94de5e",
        "fromColumn": "Item ID",
        "fromTable": "Requisition Lines",
        "toColumn": "Item ID",
        "toTable": "Item"
      },
      {
        "name": "d1911065-de10-45ed-aed4-52b675c038fa",
        "fromColumn": "Requested Date",
        "fromTable": "Requisition Lines",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "09bffbf9-bc4a-4103-a91f-f39bc03c7eaa",
        "fromColumn": "Inventory Abbreviation Code",
        "fromTable": "Sales Orders",
        "toColumn": "Inventory Abbreviation Code",
        "toTable": "Inventory Types"
      },
      {
        "name": "02125a8d-daf8-4ab6-ac24-18604fa3d5e8",
        "fromColumn": "Inventory Abbreviation Code",
        "fromTable": "Requisition Lines",
        "toColumn": "Inventory Abbreviation Code",
        "toTable": "Inventory Types"
      },
      {
        "name": "18bd063e-a34f-4626-bac5-c402e4d347ed",
        "fromColumn": "Inventory Abbreviation Code",
        "fromTable": "Scheduled Receipt",
        "toColumn": "Inventory Abbreviation Code",
        "toTable": "Inventory Types"
      },
      {
        "name": "e2abd68c-8a47-468d-9abf-71272f49033e",
        "fromColumn": "Part ID",
        "fromTable": "Scheduled Receipt",
        "toColumn": "Item ID",
        "toTable": "Item"
      },
      {
        "name": "ba9a8130-fc8b-4d54-b50f-87a48b3b4e12",
        "fromColumn": "Shipment ID",
        "fromTable": "Sales Orders",
        "toColumn": "Shipment ID",
        "toTable": "Customer Address"
      },
      {
        "name": "1e927ffe-c755-4317-b63a-e53d5a528ed8",
        "fromColumn": "Project ID",
        "fromTable": "Sales Orders",
        "toColumn": "Project ID",
        "toTable": "Project"
      },
      {
        "name": "4686e271-dcb0-48ef-9ede-b905567ec60b",
        "fromColumn": "Shipment ID",
        "fromTable": "Ship Trn",
        "isActive": false,
        "toColumn": "Shipment ID",
        "toTable": "Customer Address"
      },
      {
        "name": "57b89995-0490-406b-8535-88595fc560cc",
        "fromColumn": "End Product Part ID",
        "fromTable": "BOM",
        "toColumn": "Item ID",
        "toTable": "Item"
      },
      {
        "name": "1ad01fad-a26b-4868-ab1e-acb2845a6862",
        "fromColumn": "Project ID",
        "fromTable": "Inventory",
        "toColumn": "Project ID",
        "toTable": "Project"
      },
      {
        "name": "848d9d14-c7e7-4071-a318-fdc0c6921687",
        "fromColumn": "Manufacturing Order ID",
        "fromTable": "Manufacturing Requirements",
        "toColumn": "Manufacturing Order ID",
        "toTable": "Manufacturing Data"
      },
      {
        "name": "92c655bd-1624-4b5f-abab-0a5b8077bd00",
        "fromColumn": "Ship-By-Date",
        "fromTable": "Issue Line",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "aa68b6d0-2d7f-4e12-acfa-10fb7c435958",
        "fromColumn": "Part ID",
        "fromTable": "MPS Forecast",
        "toColumn": "Item ID",
        "toTable": "Item"
      },
      {
        "name": "d79f4ab6-5eb8-4245-98e4-a9a8ac24be4a",
        "fromColumn": "Inventory Abbreviation",
        "fromTable": "MPS Forecast",
        "toColumn": "Inventory Abbreviation Code",
        "toTable": "Inventory Types"
      },
      {
        "name": "ad6d7ffe-2a0a-4fe4-9601-315d3f67acca",
        "fromColumn": "MPS Need Date",
        "fromTable": "MPS Forecast",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "4da24db1-e707-413c-9ac2-c2c9c01e21fa",
        "fromColumn": "Project ID",
        "fromTable": "MPS Forecast",
        "toColumn": "Project ID",
        "toTable": "Project"
      },
      {
        "name": "a7f04ae3-0176-4bcb-9a5f-adde82a5cf93",
        "fromColumn": "Shipment / Ship By Date",
        "fromTable": "Ship Trn",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "7505c834-2189-4e66-9a8c-535bf855f710",
        "fromColumn": "Invoice Date",
        "fromTable": "Invoices",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "9e8f7c4a-162f-478f-bbf0-5b61c89473ea",
        "fromColumn": "Invoice Due Date",
        "fromTable": "Invoices",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "24defa75-03d9-463e-bab8-44a0618dfc48",
        "fromColumn": "Invoice Key",
        "fromTable": "Invoices",
        "isActive": false,
        "toCardinality": "many",
        "toColumn": "Invoice Key",
        "toTable": "Ship Trn"
      },
      {
        "name": "adc1653f-97b6-4dff-90e6-fed94e9a4df3",
        "fromColumn": "Warehouse ID",
        "fromTable": "Manufacturing Data",
        "toColumn": "Warehouse ID",
        "toTable": "Warehouse"
      },
      {
        "name": "559506fd-f4da-4888-8354-d6dd3037f496",
        "fromColumn": "Warehouse ID",
        "fromTable": "Manufacturing Requirements",
        "isActive": false,
        "toColumn": "Warehouse ID",
        "toTable": "Warehouse"
      },
      {
        "name": "1e0f39f3-5bb2-4401-ba00-a9c496db73a1",
        "fromColumn": "Warehouse ID",
        "fromTable": "Sales Orders",
        "toColumn": "Warehouse ID",
        "toTable": "Warehouse"
      },
      {
        "name": "d379679d-e599-4877-a1ad-28bb7bf07f70",
        "fromColumn": "Warehouse ID",
        "fromTable": "MPS Forecast",
        "toColumn": "Warehouse ID",
        "toTable": "Warehouse"
      },
      {
        "name": "f1e6c5d4-0577-4090-9ddc-a95111a6ea4b",
        "fromColumn": "Warehouse ID",
        "fromTable": "Scheduled Receipt",
        "toColumn": "Warehouse ID",
        "toTable": "Warehouse"
      },
      {
        "name": "6616f35e-8f08-4524-8960-97a46234bdb1",
        "fromColumn": "Warehouse ID",
        "fromTable": "Shipment Inventory Transactions",
        "toColumn": "Warehouse ID",
        "toTable": "Warehouse"
      },
      {
        "name": "31d9ba89-e36c-4d46-8ad7-5b12abb0b761",
        "fromColumn": "Sales Order Number",
        "fromTable": "Invoices",
        "toCardinality": "many",
        "toColumn": "Sales Order Number",
        "toTable": "Sales Orders"
      },
      {
        "name": "490bd845-900b-41cc-add5-95f6e46c1e7a",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Issue Line Key",
        "fromTable": "Issue Line",
        "isActive": false,
        "toColumn": "Issue Line Key",
        "toTable": "Ship Trn"
      },
      {
        "name": "5433d7af-e490-4afe-a8a3-3fdf0607c6e2",
        "fromColumn": "SO-LN-Key",
        "fromTable": "Ship Trn",
        "toColumn": "SO_LN_KEY2",
        "toTable": "Sales Orders"
      }
    ],
    "roles": [
      {
        "name": "Finance",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c9b1f7288db64bfba0faa1bf2f8213b0"
          }
        ],
        "modelPermission": "read"
      },
      {
        "name": "Other",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "d025e0d3fc2941afab973c92a36ed791"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Project"
          }
        ]
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "BOBL Date",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "BOBL Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b8d1da9-a0f1-4a0e-a5cb-9f70f6e3c136",
            "sourceColumn": "BOBL Date",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6f0fd776-e63d-4c45-87ca-08295f8e6e53",
        "partitions": [
          {
            "name": "BOBL Date-c5b6c35a-c8a4-4f06-b9c4-548f0f575932",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCkgsLlFwKU1VitWJVnIrLSktAjJjAQ==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"BOBL Date\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"BOBL Date\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "BOM",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "Avg Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c9119633-ebc9-468d-8cc9-4d56afc9c98e",
            "sourceColumn": "Avg Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Component Part Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e417095-3e09-4e5e-b4cc-12d8cf0a195f",
            "sourceColumn": "Component Part Description",
            "summarizeBy": "none"
          },
          {
            "name": "Component Part ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d3a25277-09e3-4e9f-98a6-08faef81f554",
            "sourceColumn": "Component Part ID",
            "summarizeBy": "none"
          },
          {
            "name": "Component Part Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7751e22e-5e26-41e0-be62-4eb45c653bca",
            "sourceColumn": "Component Part Key",
            "summarizeBy": "count"
          },
          {
            "name": "Cumulative Component Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "46b109ef-0ad2-407f-8666-0600f851ffec",
            "sourceColumn": "Cumulative Component Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Effective Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4b71f155-a461-4a51-9bbd-14a5bbb52d7d",
            "sourceColumn": "Effective Date",
            "summarizeBy": "none"
          },
          {
            "name": "End Product Part ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "df87a517-cbcc-45ce-9034-a5891eecce14",
            "sourceColumn": "End Product Part ID",
            "summarizeBy": "none"
          },
          {
            "name": "End Product Part Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6c3a1c56-6c4f-48ba-83b8-9196586822af",
            "sourceColumn": "End Product Part Key",
            "summarizeBy": "count"
          },
          {
            "name": "Latest Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "228b8c72-9f1f-42a1-8260-04c617c476ca",
            "sourceColumn": "Latest Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Part Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4308a938-7c8e-42df-99ce-10698c37073a",
            "sourceColumn": "Part Type",
            "summarizeBy": "none"
          },
          {
            "name": "Standard Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f8553666-e3d9-40d4-886e-c0e612f20f44",
            "sourceColumn": "Standard Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Timestamp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "cdeb9d34-d48d-424d-abed-cd04f55df7d8",
            "sourceColumn": "Timestamp",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5a5a1df7-93a5-42b0-9425-4bcc9ed060f8",
        "partitions": [
          {
            "name": "BOM-90d601bb-0085-455f-a195-7ad029b129af",
            "mode": "import",
            "queryGroup": "Deltek",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    deltek_BOM = Source{[Schema=\"deltek\",Item=\"BOM\"]}[Data]",
                "in",
                "    deltek_BOM"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "BOM Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "description": "This section contains measure related to Bill of Materials",
        "lineageTag": "e27c846d-c81b-43b8-bee1-fdb1861b2d83",
        "measures": [
          {
            "name": "BOM Avg Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Average cost of a BOM",
            "expression": "AVERAGE(BOM[Avg Cost])",
            "lineageTag": "2bbafda0-3a4b-48ca-812e-4ca705d7394e"
          },
          {
            "name": "BOM Latest Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Latest cost of a BOM by Item Cost table or last available PO",
            "expression": "AVERAGE(BOM[Latest Cost])",
            "lineageTag": "9d04ff6c-51ba-42f0-ae4a-ddeaed52b233"
          },
          {
            "name": "BOM Standard Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Standard cost of a BOM",
            "expression": "AVERAGE(BOM[Standard Cost])",
            "lineageTag": "de172376-c9d5-4825-9608-22eca9b49a4f"
          },
          {
            "name": "BOM Average Diff between Avg & Latest",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "This measure calculates the average difference between BOM Avg and Latest Costs",
            "expression": [
              "",
              "AVERAGEX(BOM,DIVIDE(BOM[Avg Cost],BOM[Cumulative Component Quantity])-DIVIDE(BOM[Latest Cost],BOM[Cumulative Component Quantity]))"
            ],
            "lineageTag": "172f8be7-ca81-4319-9f12-2eb9146a55cf"
          },
          {
            "name": "BOM Average Diff between Avg & Standard",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "This measure calculates the average difference between BOM Avg and Standard Costs",
            "expression": [
              "",
              "AVERAGEX(BOM,DIVIDE(BOM[Avg Cost],BOM[Cumulative Component Quantity])-DIVIDE(BOM[Standard Cost],BOM[Cumulative Component Quantity]))"
            ],
            "lineageTag": "25f0a13d-9126-431b-afb8-4e5229f5e781"
          },
          {
            "name": "BOM Average Diff between Latest & Standard",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "This measure calculates the average difference between BOM Latest and Standard Costs",
            "expression": [
              "",
              "AVERAGEX(BOM,DIVIDE(BOM[Latest Cost],BOM[Cumulative Component Quantity])-DIVIDE(BOM[Standard Cost],BOM[Cumulative Component Quantity]))"
            ],
            "lineageTag": "faccbbc0-7239-4631-af06-5077cd33bbaf"
          }
        ],
        "partitions": [
          {
            "name": "BOM Measures-821cfb0c-a7c7-4185-8ee2-effff66a6be7",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "Before Last Refreshment Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bb426999-ddf5-4ea2-9f96-856351183eff",
            "sourceColumn": "Before Last Refreshment Date",
            "summarizeBy": "sum"
          },
          {
            "name": "Calendar Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "763a5b53-9304-4fe7-8e19-e3b3397aedbd",
            "sourceColumn": "Calendar Day",
            "summarizeBy": "sum"
          },
          {
            "name": "Calendar Day Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "38d76fd5-8705-4461-aa30-1a784dbaa0a4",
            "sourceColumn": "Calendar Day Name",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dbf359ab-ea33-4e00-a361-2f969d621f2f",
            "sourceColumn": "Calendar Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Calendar Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "126aa216-d970-4f5c-9923-101410974506",
            "sortByColumn": "Calendar Month",
            "sourceColumn": "Calendar Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fc7be448-a7fb-44f7-9a27-390b335ee4d4",
            "sourceColumn": "Calendar Quarter",
            "summarizeBy": "sum"
          },
          {
            "name": "Calendar Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "5fbdd4d3-8ce3-40e9-9575-f745e9c0189a",
            "sourceColumn": "Calendar Week",
            "summarizeBy": "sum"
          },
          {
            "name": "Calendar Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5f96c68e-e5df-4d5a-ab5a-087a171beedc",
            "sourceColumn": "Calendar Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isKey": true,
            "lineageTag": "7f0ec153-b141-4733-a8f9-6bc9b342772f",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Date LY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "da415129-123c-4a21-a07e-72a2fc2b1f47",
            "sourceColumn": "Date LY",
            "summarizeBy": "none"
          },
          {
            "name": "DateText",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6c66492-29ec-4627-b17f-476f18f62b6c",
            "sourceColumn": "DateText",
            "summarizeBy": "none"
          },
          {
            "name": "DateYYYYMMdd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "777c4759-0d15-478b-ab7f-c25c275a01ef",
            "sourceColumn": "DateYYYYMMdd",
            "summarizeBy": "sum"
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c8934e4f-ff2d-4329-b251-04fc46674dd8",
            "sourceColumn": "Day of Week",
            "summarizeBy": "sum"
          },
          {
            "name": "FX Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "27660669-82bd-48d3-86c8-ea2e881252b4",
            "sourceColumn": "FX Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5038aafe-6028-4070-9c1e-28cf77a3bb42",
            "sourceColumn": "Fiscal Month",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Month Nr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9926a85-200a-44d8-973c-b904ff55eaf4",
            "sourceColumn": "Fiscal Month Nr",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Month Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "15cefd9e-6a28-4ecf-b334-92bd3cfa2793",
            "sourceColumn": "Fiscal Month Order",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c497e343-fee1-49d1-87f0-f997cbd5381b",
            "sourceColumn": "Fiscal Quarter",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8d773a85-36df-44e5-8e7d-9a5fa2f36d80",
            "sourceColumn": "Fiscal Week",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4364232e-33af-4fe2-aaab-6cd32d09c50c",
            "sourceColumn": "Fiscal Year",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year-Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "78d983c4-6687-4f6b-a080-115f1870f0ad",
            "sortByColumn": "Fiscal Year-Month Order",
            "sourceColumn": "Fiscal Year-Month",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year-Month Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9222d4bf-02a3-4c24-9fdd-55c5e5215d3b",
            "sourceColumn": "Fiscal Year-Month Order",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Year-Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3d31803-1b1c-4f5e-b61e-5d1d17555bef",
            "sourceColumn": "Fiscal Year-Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year-Quarter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dbbfcf5a-7b86-4f40-b233-026636c10f0e",
            "sourceColumn": "Fiscal Year-Quarter Order",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Year-Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1da4e7cc-041d-4c22-913d-71acb8f6f86b",
            "sourceColumn": "Fiscal Year-Week",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year-Week Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bc4a9b1e-21c8-496f-b39c-75887169f030",
            "sourceColumn": "Fiscal Year-Week Order",
            "summarizeBy": "sum"
          },
          {
            "name": "Nr of days in fiscal year-month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b4b7f413-5d95-4e40-8371-8847a745f054",
            "sourceColumn": "Nr of days in fiscal year-month",
            "summarizeBy": "sum"
          },
          {
            "name": "Nr of days in fiscal year-quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "36811ce5-6809-492b-828d-da1ab0f1d802",
            "sourceColumn": "Nr of days in fiscal year-quarter",
            "summarizeBy": "sum"
          },
          {
            "name": "Nr of workdays in fiscal month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4a37d91c-4d99-4972-833a-444f5969897e",
            "sourceColumn": "Nr of workdays in fiscal month",
            "summarizeBy": "sum"
          },
          {
            "name": "Nr of workdays in fiscal quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "41e03381-0402-45aa-8488-6cff7e7994ac",
            "sourceColumn": "Nr of workdays in fiscal quarter",
            "summarizeBy": "sum"
          },
          {
            "name": "Shop Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "384efb9e-f433-4beb-9112-c354ac9414a4",
            "sourceColumn": "Shop Day",
            "summarizeBy": "none"
          },
          {
            "name": "Short Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e76c304-fbc0-46c2-a6cd-80b2641a2361",
            "sourceColumn": "Short Date",
            "summarizeBy": "none"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "5b908c01-9c79-4218-b131-bd3fefe6ebcb",
        "partitions": [
          {
            "name": "Calendar-990b791f-a9d2-41b2-8400-0e6d3d3ae9da",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    calculated_Calendar_View = Source{[Schema=\"calculated\",Item=\"Calendar_View\"]}[Data],",
                "    #\"Merged Queries\" = Table.NestedJoin(calculated_Calendar_View, {\"Fiscal Year-Month\"}, #\"FX FCST rates\", {\"Fiscal Period\"}, \"FX\", JoinKind.LeftOuter),",
                "    #\"Expanded TTM\" = Table.ExpandTableColumn(#\"Merged Queries\", \"FX\", {\"FX Rate (CAD/USD)\"}, {\"FX Rate FCST\"}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Expanded TTM\",{{\"Date\", Order.Ascending}}),",
                "    #\"Filled Down\" = Table.FillDown(#\"Sorted Rows\",{\"FX Rate FCST\"}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Filled Down\", {\"Date\"}, Hist_Exch_Rates, {\"Exchange Date\"}, \"Hist_Exch_Rates\", JoinKind.LeftOuter),",
                "    #\"Expanded Hist_Exch_Rates\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"Hist_Exch_Rates\", {\"ExchangeRate\"}, {\"Hist_Exch_Rates.ExchangeRate\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded Hist_Exch_Rates\",{{\"FX Rate FCST\", \"FX Rate FCST_\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns\", \"FX Rate\", each if [FX Rate FCST_] is null then [Hist_Exch_Rates.ExchangeRate] else [FX Rate FCST_]),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Custom\",{\"FX Rate FCST_\", \"Hist_Exch_Rates.ExchangeRate\"}),",
                "    #\"Filled Up\" = Table.FillUp(#\"Removed Columns\",{\"FX Rate\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filled Up\",{{\"FX Rate\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Cash Receipts",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Bank Account Abbreviation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8264a679-a467-4b3f-bd2c-c59606daeadc",
            "sourceColumn": "Bank Account Abbreviation",
            "summarizeBy": "none"
          },
          {
            "name": "Cash Receipt Header Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4d16c4fa-bbf3-45b0-83c2-e6fc2dacfd94",
            "sourceColumn": "Cash Receipt Header Key",
            "summarizeBy": "count"
          },
          {
            "name": "Cash Receipt Transaction Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5f729da3-f378-4a2d-a16c-adbdd96ab43c",
            "sourceColumn": "Cash Receipt Transaction Key",
            "summarizeBy": "count"
          },
          {
            "name": "Check Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c7296c4d-d845-4cb6-bcc4-49b4c19c890b",
            "sourceColumn": "Check Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Financial Account ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04ed7723-c0c0-4447-9377-b0812d569d25",
            "sourceColumn": "Financial Account ID",
            "summarizeBy": "none"
          },
          {
            "name": "Inserted into Bank Rec Hist Code (CKY, CKN)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4a5b482f-ac9d-42e4-af87-3507376bbacb",
            "sourceColumn": "Inserted into Bank Rec Hist Code (CKY, CKN)",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8176605b-a9fc-4360-a73d-12bdb4bec79c",
            "sourceColumn": "Invoice ID",
            "summarizeBy": "none"
          },
          {
            "name": "Line Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c625fb01-80f9-40a9-b0c9-ddda86372b23",
            "sourceColumn": "Line Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Line Source Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "59641384-5dc6-4422-80f0-086e4bbd3ae0",
            "sourceColumn": "Line Source Code",
            "summarizeBy": "none"
          },
          {
            "name": "Organization ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "08cb419c-b101-46ca-8acb-327d27cc1e8f",
            "sourceColumn": "Organization ID",
            "summarizeBy": "none"
          },
          {
            "name": "Pay Transaction Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6097e146-c360-42dd-a35d-065603f173a6",
            "sourceColumn": "Pay Transaction Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Project ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1b5d99b5-93c3-49ca-bac6-527ce4e85192",
            "sourceColumn": "Project ID",
            "summarizeBy": "none"
          },
          {
            "name": "Transaction Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "291ff9a3-a6a6-498d-8454-2e91d3623e2b",
            "sourceColumn": "Transaction Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Transaction Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8de7f829-d147-458a-9252-04726ee96060",
            "sourceColumn": "Transaction Description",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "25fa7d0e-a968-4b20-803e-4eadeadfc878",
        "partitions": [
          {
            "name": "Cash Receipts-2968c25d-b6e8-4ff4-a54b-a69ef0f94358",
            "mode": "import",
            "queryGroup": "Deltek",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    deltek_AR_Cash_Transactions_Lines = Source{[Schema=\"deltek\",Item=\"AR_Cash_Transactions_Lines\"]}[Data]",
                "in",
                "    deltek_AR_Cash_Transactions_Lines"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Currency Selection",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5cf4540-a0d1-4610-9167-495025a2ff36",
            "sourceColumn": "Currency",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c1257c7e-9668-42db-b582-332bf254026b",
        "partitions": [
          {
            "name": "Currency Selection-577d2dae-aded-42bd-adc9-3607eeb601df",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WcnZ0UYrViVYKDQbSsQA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Currency = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Currency\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Customer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83ccb82d-3bda-4535-b5fb-44e35da905c0",
            "sourceColumn": "Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c5133b3-baa8-4a5e-9910-c88247309974",
            "sourceColumn": "Customer Key",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "398a8834-fe8f-46a2-885d-823a9b4c4da2",
            "sourceColumn": "Customer Name",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Term",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb55793e-e4ef-4362-b00e-b5d2422821cf",
            "sourceColumn": "Customer Term",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Term Nr of Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "73503a02-fd07-441c-bbbb-cd2c386b8e08",
            "sourceColumn": "Customer Term Nr of Days",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "27d87e10-bb44-471a-b3fe-ea1282fe6cb4",
            "sourceColumn": "Customer Type",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Territory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5caebf0f-a27c-4b9a-965d-a20bc1b71da9",
            "sourceColumn": "Sales Territory",
            "summarizeBy": "none"
          },
          {
            "name": "Tax ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6c37579-8cd5-4518-88ba-7c53f05f4482",
            "sourceColumn": "Tax ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "48091ad2-95a3-4d69-88ad-103daea87ba8",
        "partitions": [
          {
            "name": "Customer-524d13d0-14f2-4da6-b040-8be0bbb3e450",
            "mode": "import",
            "queryGroup": "Deltek",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    deltek_Customer_View = Source{[Schema=\"deltek\",Item=\"Customer_View\"]}[Data]",
                "in",
                "    deltek_Customer_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Customer Address",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "Address ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84d84762-500b-4faa-8597-fe80fa2d74cf",
            "sourceColumn": "Address ID",
            "summarizeBy": "none"
          },
          {
            "name": "Address Line 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d3f8f0f8-d459-462a-90ce-358e0456abf6",
            "sourceColumn": "Address Line 1",
            "summarizeBy": "none"
          },
          {
            "name": "Address Line 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6acadb01-875e-4520-ad84-1dc6125dee9a",
            "sourceColumn": "Address Line 2",
            "summarizeBy": "none"
          },
          {
            "name": "Address Line 3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7b86c331-88e8-4456-9f99-1d6f87b7a87a",
            "sourceColumn": "Address Line 3",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ee707a3-e1fe-4464-aa14-e3b537724045",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eeb29154-20d2-4229-8225-ecc9b1f37840",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Address Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff924331-86a6-467e-8e43-2534ca855807",
            "sourceColumn": "Customer Address Key",
            "summarizeBy": "none"
          },
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33926934-6656-43f1-bad7-baf152888833",
            "sourceColumn": "Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "719d8cd3-7538-4774-85c8-c9ba03443b63",
            "sourceColumn": "Customer Key",
            "summarizeBy": "none"
          },
          {
            "name": "E-mail",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "044d9f43-06c5-4b8c-bd16-9d804cd637dc",
            "sourceColumn": "E-mail",
            "summarizeBy": "none"
          },
          {
            "name": "Phone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f6f01533-388d-48a8-94d9-7dfe83ff6158",
            "sourceColumn": "Phone",
            "summarizeBy": "none"
          },
          {
            "name": "Postal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8490db1-3dff-4f43-9a48-642400450ba4",
            "sourceColumn": "Postal Code",
            "summarizeBy": "none"
          },
          {
            "name": "Shipment ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e878524-a33e-4249-92b3-721de74e083b",
            "sourceColumn": "Shipment ID",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea97698f-30df-44d1-80c8-a4eecdbbb21c",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "TIME_STAMP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "5488c1f4-127c-4c68-b7b9-950bda3f4eff",
            "sourceColumn": "TIME_STAMP",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cea59820-0cd5-4403-9d4a-96190b0f0a1c",
        "partitions": [
          {
            "name": "Customer Address-c139f380-bb01-4f43-8a88-58c4c088af09",
            "mode": "import",
            "queryGroup": "Deltek",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    deltek_Customer_Address = Source{[Schema=\"deltek\",Item=\"Customer_Address\"]}[Data]",
                "in",
                "    deltek_Customer_Address"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Inspections",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "Entry Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "a17c3920-7097-43d4-8fcd-b1ab0586365c",
            "sourceColumn": "Entry Date",
            "summarizeBy": "none"
          },
          {
            "name": "Inspection ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "796d9b90-9c22-46a3-88cb-7ab6c1df6710",
            "sourceColumn": "Inspection ID",
            "summarizeBy": "none"
          },
          {
            "name": "Inspection Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a803d3e1-bd4a-4ecd-8ce7-132385aa91a9",
            "sourceColumn": "Inspection Key",
            "summarizeBy": "count"
          },
          {
            "name": "Item ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb384f2c-b1f3-4288-a234-5102a0178f45",
            "sourceColumn": "Item ID",
            "summarizeBy": "none"
          },
          {
            "name": "Receipt Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8b90a8d5-3a23-40f6-b70b-b0bae4efb64d",
            "sourceColumn": "Receipt Key",
            "summarizeBy": "count"
          },
          {
            "name": "Rejected Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "35304941-dc8a-423a-b5db-e076a34f3dab",
            "sourceColumn": "Rejected Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Sub Line Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ea2a4fed-3376-4cd9-8729-e1aa9e8d2f85",
            "sourceColumn": "Sub Line Key",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "7754e60e-3235-4135-9338-1edd3554d30b",
        "partitions": [
          {
            "name": "Inspections-4a0510ab-3ebf-4ff6-8ef6-24bddab90661",
            "mode": "import",
            "queryGroup": "Deltek",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    deltek_Inspections = Source{[Schema=\"deltek\",Item=\"Inspections\"]}[Data]",
                "in",
                "    deltek_Inspections"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Inventory",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "Company ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47f8d41c-4b99-4ecd-8888-bda9c0f12e28",
            "sourceColumn": "Company ID",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "7578a1d5-9b50-4acb-a1e3-5179050da809",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "In Inspection Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3a06a2b6-a868-4251-94f2-6a0c2a9b7fba",
            "sourceColumn": "In Inspection Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "In MRB Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8c4a7855-6d3f-4d9a-b62b-95ca131f58cc",
            "sourceColumn": "In MRB Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "In Shipment Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "988923a9-117e-45b7-8404-bb7ac907a063",
            "sourceColumn": "In Shipment Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Inventory Abbreviation Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65352ab2-82c9-4224-b67a-5b04ca5a091a",
            "sourceColumn": "Inventory Abbreviation Code",
            "summarizeBy": "none"
          },
          {
            "name": "Materials Cost Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f0f57107-03a1-41e3-a699-c6287d611dc7",
            "sourceColumn": "Materials Cost Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Modified By",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7b9c732b-8734-4096-ab37-7945f6f50e9b",
            "sourceColumn": "Modified By",
            "summarizeBy": "none"
          },
          {
            "name": "On Hand Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "291996fa-7012-48d5-a21d-de0a724b81c6",
            "sourceColumn": "On Hand Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "On Hold Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fd5afa16-bbe1-4d4f-8d92-9c2baeace0b8",
            "sourceColumn": "On Hold Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "On Order Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6ef34969-b1d9-4f4d-9cce-066d82577833",
            "sourceColumn": "On Order Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "On Requisition Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cb1ef43c-e7bc-47ba-a377-beccfc57611d",
            "sourceColumn": "On Requisition Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Part ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b4232327-6a84-4b67-aded-4b3e1beb7a18",
            "sourceColumn": "Part ID",
            "summarizeBy": "none"
          },
          {
            "name": "Part Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "88170963-1ac6-40b3-b91f-537aa6bedf4c",
            "sourceColumn": "Part Key",
            "summarizeBy": "count"
          },
          {
            "name": "Project ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ebae875-e411-4454-b72e-411dac4de20a",
            "sourceColumn": "Project ID",
            "summarizeBy": "none"
          },
          {
            "name": "Reserved Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9bb1da0a-e284-475f-8fc8-3d3a13fdec65",
            "sourceColumn": "Reserved Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Timestamp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "9d8f612a-fa7d-4758-971e-c4d8e2e99547",
            "sourceColumn": "Timestamp",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1a86d46a-9fb4-43bc-b9fe-c2686a8e901d",
        "partitions": [
          {
            "name": "Inventory-d0c99e08-c5c9-4dc6-b847-46e9b352046b",
            "mode": "import",
            "queryGroup": "Deltek",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    deltek_Inventory = Source{[Schema=\"deltek\",Item=\"Inventory\"]}[Data]",
                "in",
                "    deltek_Inventory"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Inventory Types",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Inventory Abbreviation Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48f845e2-8a35-4ce9-a2b0-d75e7eb4d0ea",
            "sourceColumn": "Inventory Abbreviation Code",
            "summarizeBy": "none"
          },
          {
            "name": "Inventory Abbreviation Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca0967a5-ad6d-483c-b405-629362720901",
            "sourceColumn": "Inventory Abbreviation Name",
            "summarizeBy": "none"
          },
          {
            "name": "Inventory Account Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea30f261-07f7-4802-bc37-f5d732664c98",
            "sourceColumn": "Inventory Account Description",
            "summarizeBy": "none"
          },
          {
            "name": "Inventory Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "16eb4aee-9189-4749-b25c-1f4438b15b13",
            "sortByColumn": "Inventory Type Order",
            "sourceColumn": "Inventory Type",
            "summarizeBy": "none"
          },
          {
            "name": "Inventory Type Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "15bd04c2-e9eb-4a80-a226-f7cf93564a45",
            "sourceColumn": "Inventory Type Order",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "e5f5c43c-ff66-4fba-b890-1e8a7a0f3199",
        "partitions": [
          {
            "name": "Inventory Types-1fecd10e-0b4b-4f21-acc1-c230d61df943",
            "mode": "import",
            "queryGroup": "Deltek",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    deltek_Inventory_Abbreviations = Source{[Schema=\"deltek\",Item=\"Inventory_Abbreviations\"]}[Data]",
                "in",
                "    deltek_Inventory_Abbreviations"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Invoice Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "description": "This section contains Sales Order related measures",
        "lineageTag": "bfd5225a-3b60-4f8c-8c37-a3c283ea7028",
        "measures": [
          {
            "name": "Invoice Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Invoices[Invoice Quantity])",
              "    ,USERELATIONSHIP(Invoices[Invoice Date],'Calendar'[Date])",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "6151e956-73bb-4262-b352-63cf6b132aae"
          },
          {
            "name": "Invoice Amount",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "var invoiceamountusd =",
              "CALCULATE(",
              "    SUMX(",
              "        Invoices",
              "        ,Invoices[Net Unit Price]*Invoices[Invoice Quantity]",
              "    )",
              "    ,USERELATIONSHIP(Invoices[Invoice Date],'Calendar'[Date])",
              ")",
              "",
              "var invoiceamountcad =",
              "CALCULATE(",
              "    SUMX(",
              "        Invoices",
              "        ,Invoices[Net Unit Price CAD]*Invoices[Invoice Quantity]",
              "    )",
              "    ,USERELATIONSHIP(Invoices[Invoice Date],'Calendar'[Date])",
              ")",
              "",
              "RETURN",
              "",
              "SWITCH(",
              "    TRUE()",
              "    ,SELECTEDVALUE('Currency Selection'[Currency]) = \"CAD\",invoiceamountcad",
              "    ,invoiceamountusd",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "bc8274b8-6416-437f-b0a3-3d6409fa7b35"
          },
          {
            "name": "Invoice Amount (by Due Date)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "var invoiceamountusd =",
              "CALCULATE(",
              "    SUMX(",
              "        Invoices",
              "        ,Invoices[Net Unit Price]*Invoices [Invoice Quantity]",
              "    )",
              "    ,USERELATIONSHIP(Invoices[Invoice Due Date],'Calendar'[Date])",
              ")",
              "",
              "var invoiceamountcad =",
              "CALCULATE(",
              "    SUMX(",
              "        Invoices",
              "        ,Invoices[Net Unit Price CAD]*Invoices[Invoice Quantity]",
              "    )",
              "    ,USERELATIONSHIP(Invoices[Invoice Due Date],'Calendar'[Date])",
              ")",
              "",
              "RETURN",
              "",
              "SWITCH(",
              "    TRUE()",
              "    ,SELECTEDVALUE('Currency Selection'[Currency]) = \"CAD\",invoiceamountcad",
              "    ,invoiceamountusd",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "ce68a66e-74a4-4bd3-a719-a134e3bd8eb0"
          },
          {
            "name": "Invoice Quantity (by Due Date)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Invoices[Invoice Quantity])",
              "    ,USERELATIONSHIP(Invoices[Invoice Due Date],'Calendar'[Date])",
              ")"
            ],
            "lineageTag": "6f1d3ad7-fa46-4571-ac55-daab416e50bc"
          },
          {
            "name": "Invoice Amount (by Ship Date)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "var invoiceamountusd =",
              "CALCULATE(",
              "    SUMX(",
              "        Invoices",
              "        ,Invoices[Net Unit Price]*Invoices[Invoice Quantity]",
              "    )",
              ")",
              "",
              "var invoiceamountcad =",
              "CALCULATE(",
              "    SUMX(",
              "        Invoices",
              "        ,Invoices[Net Unit Price CAD]*Invoices[Invoice Quantity]",
              "    )",
              ")",
              "",
              "RETURN",
              "",
              "SWITCH(",
              "    TRUE()",
              "    ,SELECTEDVALUE('Currency Selection'[Currency]) = \"CAD\",invoiceamountcad",
              "    ,invoiceamountusd",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "2d06e16a-c39c-4490-b565-23f9a5d1c46b"
          },
          {
            "name": "Invoice Quantity (by Ship Date)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Invoices[Invoice Quantity])",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "719ad27a-3fb7-48f1-a77a-b6de53c8b193"
          },
          {
            "name": "Paid Amount",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "var paidusd =",
              "CALCULATE(",
              "    SUMX(",
              "        SUMMARIZE(",
              "            Invoices",
              "            ,Invoices[Invoice ID]",
              "            ,Invoices[Paid Amount USD]",
              "        )",
              "        ,Invoices[Paid Amount USD]",
              "    )",
              "    ,USERELATIONSHIP(Invoices[Invoice Date],'Calendar'[Date])",
              ")",
              "",
              "var paidcad =",
              "CALCULATE(",
              "    SUMX(",
              "        SUMMARIZE(",
              "            Invoices",
              "            ,Invoices[Invoice ID]",
              "            ,Invoices[Paid Amount CAD]",
              "        )",
              "        ,Invoices[Paid Amount CAD]",
              "    )",
              "    ,USERELATIONSHIP(Invoices[Invoice Date],'Calendar'[Date])",
              ")",
              "",
              "RETURN",
              "",
              "SWITCH(",
              "    TRUE()",
              "    ,SELECTEDVALUE('Currency Selection'[Currency]) = \"CAD\",paidcad",
              "    ,paidusd",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a27df73f-c7fb-43b8-88a0-e9eb3627a3a4"
          },
          {
            "name": "Paid Amount (by Due Date)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "var paidusd =",
              "CALCULATE(",
              "    SUMX(",
              "        SUMMARIZE(",
              "            Invoices",
              "            ,Invoices[Invoice ID]",
              "            ,Invoices[Paid Amount USD]",
              "        )",
              "        ,Invoices[Paid Amount USD]",
              "    )",
              "    ,USERELATIONSHIP(Invoices[Invoice Due Date],'Calendar'[Date])",
              ")",
              "",
              "var paidcad =",
              "CALCULATE(",
              "    SUMX(",
              "        SUMMARIZE(",
              "            Invoices",
              "            ,Invoices[Invoice ID]",
              "            ,Invoices[Paid Amount CAD]",
              "        )",
              "        ,Invoices[Paid Amount CAD]",
              "    )",
              "    ,USERELATIONSHIP(Invoices[Invoice Due Date],'Calendar'[Date])",
              ")",
              "",
              "RETURN",
              "",
              "SWITCH(",
              "    TRUE()",
              "    ,SELECTEDVALUE('Currency Selection'[Currency]) = \"CAD\",paidcad",
              "    ,paidusd",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "64a6efa4-d319-4db8-b662-ede19348db54"
          },
          {
            "name": "Paid Amount (by Ship Date)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "var paidusd =",
              "",
              "    SUMX(",
              "        SUMMARIZE(",
              "            Invoices",
              "            ,Invoices[Invoice ID]",
              "            ,Invoices[Paid Amount USD]",
              "        )",
              "        ,Invoices[Paid Amount USD]",
              "    )",
              "",
              "",
              "var paidcad =",
              "",
              "    SUMX(",
              "        SUMMARIZE(",
              "            Invoices",
              "            ,Invoices[Invoice ID]",
              "            ,Invoices[Paid Amount CAD]",
              "        )",
              "        ,Invoices[Paid Amount CAD]",
              "    )",
              "",
              "RETURN",
              "",
              "SWITCH(",
              "    TRUE()",
              "    ,SELECTEDVALUE('Currency Selection'[Currency]) = \"CAD\",paidcad",
              "    ,paidusd",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "2a930fd5-613f-4373-b268-0041ac74a251"
          }
        ],
        "partitions": [
          {
            "name": "Invoice Measures-53111473-a42a-4c5d-b9b2-4572de8e361b",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Invoices",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "AR Account ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e7944508-e837-4631-beb1-2ce8b37a7b2c",
            "sourceColumn": "AR Account ID",
            "summarizeBy": "none"
          },
          {
            "name": "AR Organization ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "71871166-37df-4b95-8bf1-b0316fb9c401",
            "sourceColumn": "AR Organization ID",
            "summarizeBy": "none"
          },
          {
            "name": "AR Project ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5377c380-fe79-40bd-b462-76b104c2c6c4",
            "sourceColumn": "AR Project ID",
            "summarizeBy": "none"
          },
          {
            "name": "CLIN ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "852e1917-9e41-4172-92d4-1ce5844e1c1a",
            "sourceColumn": "CLIN ID",
            "summarizeBy": "none"
          },
          {
            "name": "Charge Project ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "667bac4e-4683-49ca-b9d7-61ee2c7f4621",
            "sourceColumn": "Charge Project ID",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Address ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "88580966-cec0-495b-a4ef-c876b3484476",
            "sourceColumn": "Customer Address ID",
            "summarizeBy": "none"
          },
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6c0e226-73b9-486b-94b4-4000b006371b",
            "sourceColumn": "Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "Discount Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0859ad27-ee5a-4c96-bac0-0dd04335e0a3",
            "sourceColumn": "Discount Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "Freight Inclusion Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2c873f3-39b2-4ad6-ab23-767a5a2a3c80",
            "sourceColumn": "Freight Inclusion Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Hold Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b92709d-ba3d-471d-bc65-0541d0e576c2",
            "sourceColumn": "Hold Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Amount Original Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e77260eb-5a07-40c1-abae-1d8d77481722",
            "sourceColumn": "Invoice Amount Original Currency",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice Amount USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "27684eb1-36db-4d62-983e-4a1532e8653e",
            "sourceColumn": "Invoice Amount USD",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3f3ef8f1-96ab-488c-bce4-a02409a4dcf2",
            "sourceColumn": "Invoice Date",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Due Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4f95a9a8-0156-4faa-a875-52f6ee6534ec",
            "sourceColumn": "Invoice Due Date",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Full Amount Original Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b1fc49ee-98a1-4129-9665-f0d8fb9f1db7",
            "sourceColumn": "Invoice Full Amount Original Currency",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice Full Amount USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "73daf238-fcaa-4f4c-b2a2-fba31d91f796",
            "sourceColumn": "Invoice Full Amount USD",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45b4a371-532b-4d0a-a545-f91331b3c354",
            "sourceColumn": "Invoice ID",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4a4026a-9005-4d0b-ab07-19e705da54b4",
            "sourceColumn": "Invoice Key",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Line Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a93ec43-9a8b-483e-b83a-4a2ad51208b5",
            "sourceColumn": "Invoice Line Description",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Line Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e3f23e6d-0bdd-4bdc-a88a-907c0f5488cd",
            "sourceColumn": "Invoice Line Key",
            "summarizeBy": "count"
          },
          {
            "name": "Invoice Line Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "db7f7f40-b916-4685-9d3a-7fd64c806390",
            "sourceColumn": "Invoice Line Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice Line Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "697fdd63-f2fa-4316-bc4a-9304f1c2b53e",
            "sourceColumn": "Invoice Line Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice Note",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11e306eb-0fa0-4ece-a948-1de3da375c19",
            "sourceColumn": "Invoice Note",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "03deff02-5d73-45a8-8a57-45b099ace76f",
            "sourceColumn": "Invoice Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice Term",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1fa62dc-94ab-4cdd-aa39-114596571a48",
            "sourceColumn": "Invoice Term",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice UOM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eeab322e-57e8-44a1-bb49-cd9f20c24405",
            "sourceColumn": "Invoice UOM",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Unit Cost Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "509827f2-18d1-43d1-87f4-556f0a672565",
            "sourceColumn": "Invoice Unit Cost Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Item ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3722995-6582-4528-bba8-a900c3130333",
            "sourceColumn": "Item ID",
            "summarizeBy": "none"
          },
          {
            "name": "Journal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50151554-4df3-4781-86c6-f4e322538760",
            "sourceColumn": "Journal Code",
            "summarizeBy": "none"
          },
          {
            "name": "Net Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f464e78f-6192-4089-afc6-4a58553681f3",
            "sourceColumn": "Net Unit Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Net Unit Price CAD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "Invoices[Net Unit Price] * CALCULATE(MAX('Calendar'[FX Rate]),FILTER('Calendar','Calendar'[Date]=Invoices[Invoice Date]))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "b464d4b5-b900-443e-995c-ece050fbc14b",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "PS ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3945da88-55b3-4b17-82fb-6d6969d1ba7b",
            "sourceColumn": "PS ID",
            "summarizeBy": "none"
          },
          {
            "name": "Paid Amount CAD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "[Paid Amount USD] * CALCULATE(MAX('Calendar'[FX Rate]),FILTER('Calendar','Calendar'[Date]=Invoices[Invoice Date]))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "eec796a7-1d43-434a-be58-6941c9a007a1",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Paid Amount Original Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1e07c0a1-8100-4502-a914-9f6d7795e4b8",
            "sourceColumn": "Paid Amount Original Currency",
            "summarizeBy": "sum"
          },
          {
            "name": "Paid Amount USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "16d47c48-0457-4963-a375-c86548994006",
            "sourceColumn": "Paid Amount USD",
            "summarizeBy": "sum"
          },
          {
            "name": "Paid Percent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "39699906-a10b-4731-b097-c29ab2e37542",
            "sourceColumn": "Paid Percent",
            "summarizeBy": "sum"
          },
          {
            "name": "Payment Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d623930d-0ee8-4a2e-accf-bb625a531b42",
            "sourceColumn": "Payment Status",
            "summarizeBy": "none"
          },
          {
            "name": "Post Sequence Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fff82b7a-b220-4c96-b822-baff9514e481",
            "sourceColumn": "Post Sequence Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Posted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "20d77963-91d3-4583-8ec7-c1fe9832bd8b",
            "sourceColumn": "Posted",
            "summarizeBy": "none"
          },
          {
            "name": "Revenue Recognition Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86d7f4bc-31a2-41a2-983f-4c7809e8f70e",
            "sourceColumn": "Revenue Recognition Code",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Abbreviation Group Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8479405e-1951-47ff-ab88-0985f5b0a0f0",
            "sourceColumn": "Sales Abbreviation Group Code",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Order Issue Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "99981c09-fbd3-4366-ada8-be7709fa0bdd",
            "sourceColumn": "Sales Order Issue Key",
            "summarizeBy": "count"
          },
          {
            "name": "Sales Order Line Composite Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "409e4ce2-af54-479b-aba3-f07b3f26af99",
            "sourceColumn": "Sales Order Line Composite Key",
            "summarizeBy": "count"
          },
          {
            "name": "Sales Order Line Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "521099aa-20d0-41bf-a3ce-5e251b529d31",
            "sourceColumn": "Sales Order Line Key",
            "summarizeBy": "count"
          },
          {
            "name": "Sales Order Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "424373cb-d0e0-4af2-bcb3-1ba6264107ee",
            "sourceColumn": "Sales Order Number",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Order Release Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cdb9cb08-3249-4f3e-bfbe-dc10dcb2186f",
            "sourceColumn": "Sales Order Release Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Transaction Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb4a6e34-d4ae-4432-b93b-af1b4dff1582",
            "sourceColumn": "Transaction Currency",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f6d89d1f-4d9e-4f0f-ad84-7f52fdbbbe1d",
        "partitions": [
          {
            "name": "Invoices-3c2e2bcc-ba2f-47c2-9821-74ce58982181",
            "mode": "import",
            "queryGroup": "Deltek",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    deltek_SalesOrders = Source{[Schema=\"deltek\",Item=\"Invoices\"]}[Data]",
                "in",
                "    deltek_SalesOrders"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Issue Line",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "Customer Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "edca95e2-e984-4f8e-85ae-5e3af000d5fe",
            "sourceColumn": "Customer Key",
            "summarizeBy": "none"
          },
          {
            "name": "Invoiced Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6b1a1b37-4842-41af-9a25-044e19e3b0f9",
            "sourceColumn": "Invoiced Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Issue Composite Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "696ec940-f13c-4794-a9a7-af20eb06f4a9",
            "sourceColumn": "Issue Composite Key",
            "summarizeBy": "none"
          },
          {
            "name": "Issue Cost Amount USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1609fd97-209a-4878-9d39-18e9ced6fda7",
            "sourceColumn": "Issue Cost Amount USD",
            "summarizeBy": "sum"
          },
          {
            "name": "Issue Item Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3cccea8e-b321-4698-a838-ef0fd36952d6",
            "sourceColumn": "Issue Item Key",
            "summarizeBy": "none"
          },
          {
            "name": "Issue Line Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1072953-72aa-4e97-810b-7d8c37739441",
            "sourceColumn": "Issue Line Key",
            "summarizeBy": "none"
          },
          {
            "name": "Issue Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "45de290d-077d-4131-929e-d117585e78ae",
            "sourceColumn": "Issue Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Issue Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a52db473-3cc4-4420-961d-b8a54ff2ce5f",
            "sourceColumn": "Issue Status",
            "summarizeBy": "none"
          },
          {
            "name": "Item ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51693029-84b3-4e28-b523-7fd660fe9f84",
            "sourceColumn": "Item ID",
            "summarizeBy": "none"
          },
          {
            "name": "Item Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aa664b79-fcc1-48da-a349-36138e87df08",
            "sourceColumn": "Item Key",
            "summarizeBy": "count"
          },
          {
            "name": "Kit Item ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1541f3bc-ad55-4d46-a2c0-69cfe66bf315",
            "sourceColumn": "Kit Item ID",
            "summarizeBy": "none"
          },
          {
            "name": "Kit Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dbe3b4ba-99f3-43b2-af7f-a1cf4fa3d48b",
            "sourceColumn": "Kit Unit Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Net Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b149f24-9bb7-4d06-bd9f-47a057acb845",
            "sourceColumn": "Net Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Net Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              " CALCULATE(",
              "     MAX('Sales Orders'[Net Unit Price])",
              "     ,FILTER('Sales Orders','Issue Line'[SO_LN_KEY]='Sales Orders'[SO_LN_KEY2])",
              " )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "335e56e4-41ec-4e7c-9713-871b55fb7bb9",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "PS_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25e1d481-ac5c-4bfa-8962-bedcd0d79069",
            "sourceColumn": "PS_ID",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "381d309c-3be9-482d-9cb5-e8ec1a180958",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "SO Line Nr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "db847849-6aa6-47a0-9fa0-51e26a0aeef7",
            "sourceColumn": "SO Line Nr",
            "summarizeBy": "sum"
          },
          {
            "name": "SO_ISSUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9e1cfd30-a462-490e-aa23-2678ce9cd633",
            "sourceColumn": "SO_ISSUE_KEY",
            "summarizeBy": "sum"
          },
          {
            "name": "SO_ISSUE_LN_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "17a6eb72-8265-43d6-ab75-e84adc6967f0",
            "sourceColumn": "SO_ISSUE_LN_KEY",
            "summarizeBy": "sum"
          },
          {
            "name": "SO_LN_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15860f02-8801-430d-bc1a-f6eea2ebf8e4",
            "sourceColumn": "SO_LN_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Order Component Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c7ac950e-5363-4ffa-abfb-7389c54f7da0",
            "sourceColumn": "Sales Order Component Key",
            "summarizeBy": "count"
          },
          {
            "name": "Sales Order Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83d05d45-8298-4e97-b067-0c621539245d",
            "sourceColumn": "Sales Order Number",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Order Release Nr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1d68526a-bbd7-4a07-b94d-ccea33343acb",
            "sourceColumn": "Sales Order Release Nr",
            "summarizeBy": "sum"
          },
          {
            "name": "Ship-By-Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "aedb902c-b762-4089-9ddc-3d4792c217ae",
            "sourceColumn": "Ship-By-Date",
            "summarizeBy": "none"
          },
          {
            "name": "Shipment Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "148efc2f-42b1-4f06-bd49-10e0b6afe0a8",
            "sourceColumn": "Shipment Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Spreaded Extended Amount CAD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "expression": [
              "'Issue Line'[Spreaded Extended Amount USD]",
              "    * LOOKUPVALUE( 'Calendar'[FX Rate] , 'Calendar'[Date] , 'Issue Line'[Ship-By-Date] )"
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "227eecc9-0b0d-4518-bf8e-9728c1d7f979",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Spreaded Extended Amount USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "1114e045-3f06-4d7a-89f9-a9fc5f089c78",
            "sourceColumn": "Spreaded Extended Amount USD",
            "summarizeBy": "sum"
          },
          {
            "name": "Timestamp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "ee9ba725-dec7-4b6b-bc2c-10a38a38cba1",
            "sourceColumn": "Timestamp",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Cost Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6ebd1141-2f87-429d-9058-19a28c5e363b",
            "sourceColumn": "Unit Cost Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "group abbree",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              " CALCULATE(",
              "     MAX('Sales Orders'[Sales Group Inclusion])",
              "     ,FILTER('Sales Orders','Issue Line'[SO_LN_KEY]='Sales Orders'[SO_LN_KEY2])",
              " )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "06c945bd-2d16-4ca8-88d2-44e2a0f4a8f4",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "3977d12e-d71d-48c8-8ea1-5fd05bfefb36",
        "partitions": [
          {
            "name": "Issue Line-301cce44-6fd7-4fcb-8c6a-d7d096c696c2",
            "mode": "import",
            "queryGroup": "Deltek",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    deltek_Issue_Line_Expanded = Source{[Schema=\"deltek\",Item=\"Issue_Line_Expanded\"]}[Data]",
                "in",
                "    deltek_Issue_Line_Expanded"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Item",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "Active Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ead61905-78ac-445e-9e43-a0e98787c360",
            "sourceColumn": "Active Product",
            "summarizeBy": "none"
          },
          {
            "name": "Average SO price by last 90 days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ac21b109-eacb-4cc8-b7b6-ce6f4f875459",
            "sourceColumn": "Average SO price by last 90 days",
            "summarizeBy": "sum"
          },
          {
            "name": "Average Salesforce Price by +-90 days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "743aaca4-eb82-409f-a59a-68297b17afad",
            "sourceColumn": "Average Salesforce Price by +-90 days",
            "summarizeBy": "sum"
          },
          {
            "name": "Buyer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "901abfcc-b2b5-449d-b17a-438a8ce869ab",
            "sourceColumn": "Buyer",
            "summarizeBy": "none"
          },
          {
            "name": "Commodity Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0e4069b3-93bf-45cd-ba6d-f46941628997",
            "sourceColumn": "Commodity Code",
            "summarizeBy": "none"
          },
          {
            "name": "Commodity Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "146e32d4-98d4-4f7d-944e-1ebe98e889b6",
            "sourceColumn": "Commodity Description",
            "summarizeBy": "none"
          },
          {
            "name": "Common Stock Inventory Abbrev Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9378cca6-ebf2-4414-a6e6-f3faf5d7ce8b",
            "sourceColumn": "Common Stock Inventory Abbrev Code",
            "summarizeBy": "none"
          },
          {
            "name": "Company ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "53dc3d7f-ded5-4ff3-a904-319976cadea8",
            "sourceColumn": "Company ID",
            "summarizeBy": "none"
          },
          {
            "name": "Default Inventory Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2fd5c79d-a7c2-4d51-bf96-de8e97a76b4e",
            "sourceColumn": "Default Inventory Location",
            "summarizeBy": "none"
          },
          {
            "name": "Default UOM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73027020-4a83-46ce-a4cc-ceb3bd559c0a",
            "sourceColumn": "Default UOM",
            "summarizeBy": "none"
          },
          {
            "name": "Default Warehouse",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4dc6e02-2e24-44c6-b70a-668229667605",
            "sourceColumn": "Default Warehouse",
            "summarizeBy": "none"
          },
          {
            "name": "ECN Pending Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "547f27d4-c645-4ff5-adf2-b97aa86e71f2",
            "sourceColumn": "ECN Pending Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Floor Stock Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2dbf84b-7228-4e81-89cc-c9f9dba75815",
            "sourceColumn": "Floor Stock Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Industry Class Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a070ef4-70e3-40d6-9776-0a0c4cf6d67d",
            "sourceColumn": "Industry Class Code",
            "summarizeBy": "none"
          },
          {
            "name": "Inventory Part Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2b1c926-d9a0-46c4-9a99-26699a1d0d0d",
            "sourceColumn": "Inventory Part Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Inventory Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0eb9789e-06f8-4e83-8a17-067b345694a6",
            "sourceColumn": "Inventory Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "13a25e92-af08-4880-811b-c486ea50d3fc",
            "sourceColumn": "Item",
            "summarizeBy": "none"
          },
          {
            "name": "Item Average Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "735a8c09-97ea-4777-a617-91f3a025cc96",
            "sourceColumn": "Item Average Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Item Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02839658-cf53-4866-995e-715abd7d237d",
            "sourceColumn": "Item Description",
            "summarizeBy": "none"
          },
          {
            "name": "Item ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3892400e-0ba3-46d7-9742-4e05091ad405",
            "sourceColumn": "Item ID",
            "summarizeBy": "none"
          },
          {
            "name": "Item Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ab1e76c4-1ad6-4ad5-9353-7dc571e7e494",
            "sourceColumn": "Item Key",
            "summarizeBy": "count"
          },
          {
            "name": "Item Material Cost Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1e50ab1d-2873-4fd7-8518-937ae5b00652",
            "sourceColumn": "Item Material Cost Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Item Notes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9709eeff-3329-4359-bcc2-90ca96599e94",
            "sourceColumn": "Item Notes",
            "summarizeBy": "none"
          },
          {
            "name": "Item Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f8e165a-5312-41e4-ae1f-5655c6f1cacf",
            "sourceColumn": "Item Type",
            "summarizeBy": "none"
          },
          {
            "name": "Item Unit Cost Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ac17bcd9-2106-4911-925c-7ce042046527",
            "sourceColumn": "Item Unit Cost Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Last PO / Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7f0105b9-085d-4101-99bd-64f37817ba56",
            "sourceColumn": "Last PO / Unit Price",
            "summarizeBy": "sum"
          },
          {
            "name": "MFG Part Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15b3f3e0-6eb4-4cf1-9cca-628b78bb12cf",
            "sourceColumn": "MFG Part Number",
            "summarizeBy": "none"
          },
          {
            "name": "Make / Buy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3dfae41b-3182-417a-a05e-b4cc5c050473",
            "sourceColumn": "Make / Buy",
            "summarizeBy": "none"
          },
          {
            "name": "National Stock Nr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "567c4e63-70db-4f7f-ad7b-44754571a071",
            "sourceColumn": "National Stock Nr",
            "summarizeBy": "none"
          },
          {
            "name": "Part ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c04a430-9f13-4043-a79a-908af3914143",
            "sourceColumn": "Part ID",
            "summarizeBy": "none"
          },
          {
            "name": "Part Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "626694b7-5fc2-4092-bf53-6fa3c6177faa",
            "sourceColumn": "Part Type",
            "summarizeBy": "none"
          },
          {
            "name": "Product Classification",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "99fa24ff-69ec-4312-a1d7-9dea94e93f3a",
            "sourceColumn": "Product Classification",
            "summarizeBy": "none"
          },
          {
            "name": "Product Classification Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c30093d-98bb-496b-b21f-b46df190aee0",
            "sourceColumn": "Product Classification Code",
            "summarizeBy": "none"
          },
          {
            "name": "Product Classification Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "371734d5-4fc6-4c32-8eac-fb999f800118",
            "sourceColumn": "Product Classification Description",
            "summarizeBy": "none"
          },
          {
            "name": "Product Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bbcd52c8-90c9-43e9-8dfc-4b4423a952a1",
            "sourceColumn": "Product Type",
            "summarizeBy": "none"
          },
          {
            "name": "QC Required Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6614b9a-7359-417f-a3f4-22c1c33852a0",
            "sourceColumn": "QC Required Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Scrap Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "36b88807-9cdf-454c-a07d-51175ba1f91f",
            "sourceColumn": "Scrap Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "Status Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dcde8d59-b1db-4b4e-9ac6-6ca82c119673",
            "sourceColumn": "Status Type",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Price in Deltek",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "964ef4f3-2653-43bc-b41d-5e21cfabfba8",
            "sourceColumn": "Unit Price in Deltek",
            "summarizeBy": "sum"
          },
          {
            "name": "Yield Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4c674bb7-a3bd-478e-b959-0a19cb5b42fc",
            "sourceColumn": "Yield Rate",
            "summarizeBy": "sum"
          }
        ],
        "hierarchies": [
          {
            "name": "Item Hierarchy",
            "levels": [
              {
                "name": "Product Type",
                "column": "Product Type",
                "lineageTag": "f0ff5549-d095-44fa-8792-4a0f36cce58c",
                "ordinal": 0
              },
              {
                "name": "Product Classification Description",
                "column": "Product Classification Description",
                "lineageTag": "9d19d587-0df4-4e47-aafe-95192db548ff",
                "ordinal": 1
              },
              {
                "name": "Item",
                "column": "Item",
                "lineageTag": "69794e87-5586-487f-b81c-59985c617c37",
                "ordinal": 2
              }
            ],
            "lineageTag": "876b5b01-66cc-4236-925d-64a67a4fdc8f"
          }
        ],
        "lineageTag": "cd06561a-a409-4263-950b-d8a6e0f957ee",
        "partitions": [
          {
            "name": "Item-46bf4292-fe7f-41de-b5ff-531dfa14f652",
            "mode": "import",
            "queryGroup": "Deltek",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    deltek_Items = Source{[Schema=\"deltek\",Item=\"Items\"]}[Data]",
                "in",
                "    deltek_Items"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Item Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "description": "This section contains Item related measures",
        "lineageTag": "80c5b960-9f92-43e8-9ea9-b6d87f619a45",
        "measures": [
          {
            "name": "Item Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": "The measure calculates item cost considering the following calculation types in this order: 1. Average Cost if available, 2. Latest cost if available, else Standard Cost",
            "expression": [
              "",
              "AVERAGE('Item'[Item Unit Cost Amount])"
            ],
            "isHidden": true,
            "lineageTag": "35686ca1-9688-4e99-b3b4-48f68772c477"
          },
          {
            "name": "Open Order Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Scheduled Receipt'[Open Order Quantity])",
              "    ,'Item'[Part ID]<>\"REPAIR\"",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "26369ed8-3d2c-4eeb-9807-0babed213767"
          },
          {
            "name": "Shipment Transaction",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Shipment Inventory Transactions'[Transaction Quantity])*-1",
              "    ,'Item'[Part ID]<\"A\"",
              ")"
            ],
            "lineageTag": "24cf0052-9130-448d-a121-feb159674f39"
          }
        ],
        "partitions": [
          {
            "name": "Item Measures-13febd5d-a91f-4c8a-a57f-65c817f1c5b6",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Last Refreshment",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Last Refreshment EST",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "259b08aa-53ce-494d-a581-6102e53855ab",
            "sourceColumn": "Last Refreshment EST",
            "summarizeBy": "none"
          },
          {
            "name": "Last Refreshment UTC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "3c7e5725-25ab-4d20-b5aa-42b4bd44d0a1",
            "sourceColumn": "Last Refreshment UTC",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "389b6163-3eb1-4f5c-9ffc-7f5228e64249",
        "partitions": [
          {
            "name": "Last Refreshment-13d39006-934e-4647-b63a-e94b559723ea",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    deltek_LastRefreshmentTime = Source{[Schema=\"deltek\",Item=\"LastRefreshmentTime\"]}[Data]",
                "in",
                "    deltek_LastRefreshmentTime"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MPS Forecast",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "BOM Configuration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7fbf84df-7026-4e9d-8425-9bac8c748343",
            "sourceColumn": "BOM Configuration",
            "summarizeBy": "none"
          },
          {
            "name": "Company ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7d604572-ed0b-4e44-a78f-0186dc3d41aa",
            "sourceColumn": "Company ID",
            "summarizeBy": "none"
          },
          {
            "name": "Inventory Abbreviation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f3e102c5-afa4-4f3a-98f7-cf913378959a",
            "sourceColumn": "Inventory Abbreviation",
            "summarizeBy": "none"
          },
          {
            "name": "MPS Need Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "4435fb88-b838-4ac4-b971-9cac7e6f7e25",
            "sourceColumn": "MPS Need Date",
            "summarizeBy": "none"
          },
          {
            "name": "MPS Plan Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01f96e63-7cf3-4dc4-90a7-f2f4a05ed437",
            "sourceColumn": "MPS Plan Code",
            "summarizeBy": "none"
          },
          {
            "name": "MPS Plan Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ca1bcba-91c3-4469-b0bd-b2e477b3e253",
            "sourceColumn": "MPS Plan Description",
            "summarizeBy": "none"
          },
          {
            "name": "Open Production Forecast Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "12ca8343-7bd5-4b2d-8626-46caa315c747",
            "sourceColumn": "Open Production Forecast Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Open Sales Forecast Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6d06c653-bb96-4b55-8305-3e21851d8469",
            "sourceColumn": "Open Sales Forecast Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Original Production Forecast Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5f9f7137-ca83-4273-aa40-2553bf9c10d8",
            "sourceColumn": "Original Production Forecast Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Original Sales Forecast Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8d986c0a-75bd-44f6-9f1c-7bbacc04d242",
            "sourceColumn": "Original Sales Forecast Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Parent Part ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e047d8e0-71ec-4e85-b9eb-0d21d21edb89",
            "sourceColumn": "Parent Part ID",
            "summarizeBy": "none"
          },
          {
            "name": "Part ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9d49b375-62f7-4060-b109-b79140b6f805",
            "sourceColumn": "Part ID",
            "summarizeBy": "none"
          },
          {
            "name": "Planner ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0324b59d-04f1-4edf-857c-ed7d706d18ab",
            "sourceColumn": "Planner ID",
            "summarizeBy": "none"
          },
          {
            "name": "Project ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ad4f765-6958-4e8a-81ae-0f3cb58ed58c",
            "sourceColumn": "Project ID",
            "summarizeBy": "none"
          },
          {
            "name": "Warehouse ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c546ac09-f660-4575-9505-548b607588d2",
            "sourceColumn": "Warehouse ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0bafe05e-47ac-4f24-b641-8f95e595555f",
        "partitions": [
          {
            "name": "MPS Forecast-9dd38e76-0683-4efa-82f6-f7bc0a1971ab",
            "mode": "import",
            "queryGroup": "Deltek",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    calculated_MPS_Component = Source{[Schema=\"calculated\",Item=\"MPS_Component\"]}[Data]",
                "in",
                "    calculated_MPS_Component"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MPS Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "description": "This section contains Sales Order related measures",
        "lineageTag": "a6bedf17-2349-40da-9afd-6f34684647e1",
        "measures": [
          {
            "name": "Total Original Sales Forecast Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "SUMX('MPS Forecast',IF(LEFT('MPS Forecast'[Parent Part ID],4)=\"FCST\",'MPS Forecast'[Original Sales Forecast Quantity]))",
            "formatString": "#,0",
            "lineageTag": "d5ab66a6-3978-48cc-9f0a-3f85709208ff"
          },
          {
            "name": "Total Original Production Forecast Quantity",
            "expression": "SUMX('MPS Forecast',IF(LEFT('MPS Forecast'[Parent Part ID],4)=\"FCST\",'MPS Forecast'[Original Production Forecast Quantity]))",
            "formatString": "#,0.00",
            "lineageTag": "3e40a10b-95ae-4665-a05c-cbee491d2459"
          },
          {
            "name": "Total Open Sales Forecast Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "SUMX('MPS Forecast',IF(LEFT('MPS Forecast'[Parent Part ID],4)=\"FCST\",'MPS Forecast'[Open Sales Forecast Quantity]))",
            "formatString": "#,0",
            "lineageTag": "feeff65d-9850-4dc7-ac43-a127b1d95b5d"
          },
          {
            "name": "Total Open Production Forecast Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "SUMX('MPS Forecast',IF(LEFT('MPS Forecast'[Parent Part ID],4)=\"FCST\",'MPS Forecast'[Open Production Forecast Quantity]))",
            "formatString": "#,0",
            "lineageTag": "ba22bb0a-093c-4dda-b888-2a001d64e2cc"
          },
          {
            "name": "Total Original Forecast Quantity",
            "expression": "[Total Original Production Forecast Quantity] + [Total Original Sales Forecast Quantity]",
            "formatString": "#,0.00",
            "lineageTag": "6471c5e2-9536-4d63-85dc-425c7525c8c8"
          },
          {
            "name": "Nr of Shop Days",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "COUNTX(",
              "    'Calendar'",
              "    ,IF('Calendar'[Shop Day]=\"Y\",1)",
              ")"
            ],
            "lineageTag": "f3ec0e92-de9f-4594-8fa8-8fbc78a2d2eb"
          }
        ],
        "partitions": [
          {
            "name": "MPS Measures-ccb8b69b-56f6-4bb7-becd-f5aace1d2f2c",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Manufacturing Data",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "Due Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "21c75db2-e333-498b-a4f5-c0542070aee8",
            "sourceColumn": "Due Date",
            "summarizeBy": "none"
          },
          {
            "name": "MO Build Part ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7b7edf5-cae2-46d5-81d1-4705ac917064",
            "sourceColumn": "MO Build Part ID",
            "summarizeBy": "none"
          },
          {
            "name": "MO Build Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5147b2f6-7c3e-4009-82ac-39c17dbb5442",
            "sourceColumn": "MO Build Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "MO Completed Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "43d40d8f-f661-438d-b569-b7088000aeef",
            "sourceColumn": "MO Completed Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "MO Planned In Shop Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4be69073-2d2a-4d73-ba44-2360d0b45ecf",
            "sourceColumn": "MO Planned In Shop Date",
            "summarizeBy": "none"
          },
          {
            "name": "MO Status Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f721501-4be6-4cc6-9649-90d3abe8e70b",
            "sourceColumn": "MO Status Description",
            "summarizeBy": "none"
          },
          {
            "name": "MO Type Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba5f041c-0ea5-4b16-8673-946dfe311e1c",
            "sourceColumn": "MO Type Code",
            "summarizeBy": "none"
          },
          {
            "name": "Manufacturing Order ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "de78343c-370f-4a8c-8e89-019c11e337ca",
            "sourceColumn": "Manufacturing Order ID",
            "summarizeBy": "none"
          },
          {
            "name": "Need Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f0f0b6e0-a415-46ef-b47a-c5246a8b8864",
            "sourceColumn": "Need Date",
            "summarizeBy": "none"
          },
          {
            "name": "Open Qty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7e7ae271-32aa-49b8-afc2-4ee6f1e8b1a6",
            "sourceColumn": "Open Qty",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Reference ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74bdc9a7-ea24-414e-a85d-e3ccf1dfdd1f",
            "sourceColumn": "Order Reference ID",
            "summarizeBy": "none"
          },
          {
            "name": "Planned Release Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d69196d7-feb8-4e15-8c53-844fd1e50cdf",
            "sourceColumn": "Planned Release Date",
            "summarizeBy": "none"
          },
          {
            "name": "Warehouse ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a120012e-4c0c-4e0f-a3b6-0846abd61284",
            "sourceColumn": "Warehouse ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e47e7228-94f9-4f1a-bd83-66d0f197c882",
        "partitions": [
          {
            "name": "Manufacturing Data-dba42ca7-e96f-408e-bebe-de20a110debb",
            "mode": "import",
            "queryGroup": "Deltek",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    deltek_Manufacturing_Order_Header = Source{[Schema=\"deltek\",Item=\"Manufacturing_Order_Header\"]}[Data]",
                "in",
                "    deltek_Manufacturing_Order_Header"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Manufacturing Requirements",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "BOM Line Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f6280027-38ed-406d-89ee-4d8091a0d3ce",
            "sourceColumn": "BOM Line Key",
            "summarizeBy": "count"
          },
          {
            "name": "Component Line No",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eb603e9a-0f67-4305-ac32-9e66c5080840",
            "sourceColumn": "Component Line No",
            "summarizeBy": "sum"
          },
          {
            "name": "Component Part ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ee8287f-6186-46fc-8a93-cbb3e166c92a",
            "sourceColumn": "Component Part ID",
            "summarizeBy": "none"
          },
          {
            "name": "Component Type Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46e2d020-6bba-4772-9697-64b291cc6019",
            "sourceColumn": "Component Type Code",
            "summarizeBy": "none"
          },
          {
            "name": "Inventory Abbreviation Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a85ccab7-6212-460b-b5de-8bc644031de6",
            "sourceColumn": "Inventory Abbreviation Code",
            "summarizeBy": "none"
          },
          {
            "name": "Inventory Reserved Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "112ec1fe-0b24-42c4-b699-28ad3646af09",
            "sourceColumn": "Inventory Reserved Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Issues Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "71ec6293-725d-4d27-82ad-7d6265e650ff",
            "sourceColumn": "Issues Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Manufacturing Order ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3cd1920f-4b5c-46b9-8288-9b757dce73b0",
            "sourceColumn": "Manufacturing Order ID",
            "summarizeBy": "none"
          },
          {
            "name": "Need Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1f58fff0-47fa-487f-a37d-1aa117a8d886",
            "sourceColumn": "Need Date",
            "summarizeBy": "none"
          },
          {
            "name": "Original Part ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e04e6542-3f74-4110-91bf-04892afdfb36",
            "sourceColumn": "Original Part ID",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity Type Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4e9dd99-62b3-41ab-b86c-b33ae11711ba",
            "sourceColumn": "Quantity Type Code",
            "summarizeBy": "none"
          },
          {
            "name": "Required Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ce65062f-71ae-4d17-a532-12df13a174f0",
            "sourceColumn": "Required Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Requirement Line Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "575f06d5-b060-4236-b9e7-17cfe58bc858",
            "sourceColumn": "Requirement Line Key",
            "summarizeBy": "count"
          },
          {
            "name": "Reservation ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0cc418a2-01c2-4dc1-996c-4f2ea05a1d6e",
            "sourceColumn": "Reservation ID",
            "summarizeBy": "none"
          },
          {
            "name": "Reservation Line Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "de883e84-958c-4b6f-a3cb-d285468ceca6",
            "sourceColumn": "Reservation Line Key",
            "summarizeBy": "count"
          },
          {
            "name": "To Issue Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "64083ba0-124c-4d4b-a569-5e1abf63ce38",
            "sourceColumn": "To Issue Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Warehouse ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2cddae7-b7fa-4594-b8c3-8e49874db9d6",
            "sourceColumn": "Warehouse ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4c18a61d-81a5-40dc-acec-c6e1f5801b20",
        "partitions": [
          {
            "name": "Manufacturing Requirements-ac7a1aee-4104-4e00-b33b-eb5e4f05f21c",
            "mode": "import",
            "queryGroup": "Deltek",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    deltek_Manufacturing_Requirements = Source{[Schema=\"deltek\",Item=\"Manufacturing_Requirements\"]}[Data]",
                "in",
                "    deltek_Manufacturing_Requirements"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Measure Selection",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Measure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9df4445-eed2-4d8f-80d6-64372d2cec2a",
            "sourceColumn": "Measure",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "82c6e42a-27fe-4892-82c5-8e43b1acb4ed",
        "partitions": [
          {
            "name": "Measure Selection-f1f86df2-5b55-482a-bc53-5b8415d14b45",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCskvScxRCM7ILMhNzSspVlBRitVBF1UILE3MK8ksqUSS8y9KSS1S8MwrScxORdEEkUDR4ZdaouDk7+QDVedelF9cDBHQCMosztYEiccCAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Measure = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Measure\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "On Time Delivery Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "description": "This section contains Sales Order related measures",
        "lineageTag": "33b92378-f5e4-45b8-94e6-75fafa06ac83",
        "measures": [
          {
            "name": "Average Aging (Days)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "AVERAGEX(",
              "    FILTER('Ship Trn',NOT(ISBLANK('Ship Trn'[Shipment Date]))",
              "    &&RELATED('Sales Orders'[Net Unit Price])>0",
              "    &&'Ship Trn'[Shipment Status]=\"Shipped\")",
              "    ,DATEDIFF(RELATED('Sales Orders'[Order Date]),'Ship Trn'[Shipment Date],DAY)",
              ")"
            ],
            "formatString": "#,0.0",
            "lineageTag": "6a48a0ec-121f-4779-961f-0db62f07983e"
          },
          {
            "name": "On Time Delivery %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "var OnTime = ",
              "",
              "    CALCULATE(",
              "        COUNTROWS('Ship Trn')",
              "        ,FILTER('Ship Trn',",
              "            'Ship Trn'[On Time Flag]=\"Y\")",
              "    )",
              "",
              "",
              "var Overdue = ",
              "",
              "    CALCULATE(",
              "        COUNTROWS('Ship Trn')",
              "        ,FILTER('Ship Trn',",
              "            'Ship Trn'[On Time Flag]=\"N\")",
              "    )",
              " ",
              "var allshiptrn =",
              "CALCULATE(",
              "    COUNTROWS('Ship Trn')",
              "    ,FILTER('Ship Trn',",
              "        'Ship Trn'[On Time Flag]=\"Y\"||'Ship Trn'[On Time Flag]=\"N\")",
              ")",
              "",
              "RETURN",
              "",
              "IF([Total Shipments]>0",
              "    ,COALESCE(",
              "        DIVIDE(",
              "            OnTime",
              "            ,allshiptrn",
              "        )",
              "        ,0",
              "    )",
              ")",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "d50b086c-4efb-46da-95ae-7fbc37a9365e"
          },
          {
            "name": "Nr of Shipments (Shipped)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS('Ship Trn')",
              "    ,FILTER('Ship Trn',",
              "        NOT(ISBLANK('Ship Trn'[Shipment Date]))",
              "        &&RELATED('Sales Orders'[Net Unit Price])>0",
              "        &&'Ship Trn'[Shipment Status]=\"Shipped\")",
              ")"
            ],
            "lineageTag": "b8e77077-2693-44a0-b65e-444d82c9d4da"
          },
          {
            "name": "Overdue & Early Ship Nr of Days Balance (Days)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "AVERAGEX(",
              "    FILTER('Ship Trn',",
              "        NOT(ISBLANK('Ship Trn'[Shipment Date]))",
              "        &&RELATED('Sales Orders'[Net Unit Price])>0",
              "        &&'Ship Trn'[Shipment Status]=\"Shipped\"",
              "        &&NOT(ISBLANK('Ship Trn'[Shipment Date])))",
              ",",
              "IF(",
              "    'Ship Trn'[Shipment Date]>RELATED('Sales Orders'[Promise Date])",
              "    ,DATEDIFF(RELATED('Sales Orders'[Promise Date]),'Ship Trn'[Shipment Date],DAY)",
              "    ,DATEDIFF('Ship Trn'[Shipment Date],RELATED('Sales Orders'[Promise Date]),DAY)*-1",
              ")",
              ")"
            ],
            "lineageTag": "ae5bc1a7-1b93-4e33-91c6-70748dfbc7cc"
          }
        ],
        "partitions": [
          {
            "name": "On Time Delivery Measures-8775b6a0-ac38-4b88-8172-15a80f8434a7",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product Hierarchy",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Buy Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "12c7a95a-08ad-434e-948d-9c27b31bc860",
            "sourceColumn": "Buy Level",
            "summarizeBy": "none"
          },
          {
            "name": "DS_MPS Qty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('MPS Forecast'[Open Sales Forecast Quantity])",
              "    ,FILTER('MPS Forecast','MPS Forecast'[Part ID]='Product Hierarchy'[Level 0])",
              ")"
            ],
            "formatString": "#,0",
            "isDataTypeInferred": true,
            "lineageTag": "e70ca8ce-b497-450c-bbc0-b27392ddb5f3",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "DS_On-Hand Qty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Inventory[On Hand Quantity])",
              "    ,FILTER('MPS Forecast','MPS Forecast'[Part ID]='Product Hierarchy'[Level 0])",
              ")"
            ],
            "formatString": "#,0",
            "isDataTypeInferred": true,
            "lineageTag": "de2e58ea-b632-4cd5-8b38-fb8cc8182be6",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "DS_Open Order Qty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Sales Orders'[Order Quantity])",
              "    ,FILTER('Sales Orders','Sales Orders'[Item ID]='Product Hierarchy'[Level 0]&&'Sales Orders'[SO Line Status]=\"O\")",
              ")"
            ],
            "formatString": "#,0",
            "isDataTypeInferred": true,
            "lineageTag": "a3490d30-6037-42db-86a4-ece874816b9c",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "DS_ToIssue Qty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Manufacturing Requirements'[To Issue Quantity])",
              "    ,FILTER('Manufacturing Requirements','Manufacturing Requirements'[Component Part ID]='Product Hierarchy'[Level 11])",
              ")"
            ],
            "formatString": "#,0",
            "isDataTypeInferred": true,
            "lineageTag": "0cfbba10-7935-4ed2-8bb2-b27ebd6d82f9",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "DS_WIP Qty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"In Shop\"&&'Manufacturing Data'[MO Build Part ID]='Product Hierarchy'[Level 0])",
              ")"
            ],
            "formatString": "#,0",
            "isDataTypeInferred": true,
            "lineageTag": "68e13ddb-ef76-4741-bfb9-a87a39ea0aab",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Level 0",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0daeab10-f2f0-4b09-88f4-41157ed50acd",
            "sourceColumn": "Level 0",
            "summarizeBy": "none"
          },
          {
            "name": "Level 0 Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX('Item'[Item])",
              "    ,FILTER('Item','Item'[Item ID]='Product Hierarchy'[Level 0])",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "4bfcad15-9cdc-4fdb-9e00-c7d004bdc392",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Level 0 Product Classification",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX('Item'[Product Classification Description])",
              "    ,FILTER('Item','Item'[Item ID]='Product Hierarchy'[Level 0])",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "7570fb3d-5c5a-4eba-b2b9-57b398307da9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Level 0 Product Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX('Item'[Product Type])",
              "    ,FILTER('Item','Item'[Item ID]='Product Hierarchy'[Level 0])",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "ba5e7644-f84f-40ed-813d-db683284b56d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Level 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "308a9edf-574e-4a00-9169-8f4fb0e43847",
            "sourceColumn": "Level 1",
            "summarizeBy": "none"
          },
          {
            "name": "Level 10",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "673365d5-c0f8-469a-826d-a6ed83f5aa32",
            "sourceColumn": "Level 10",
            "summarizeBy": "none"
          },
          {
            "name": "Level 11",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ac1b8ca-fdc9-4a29-b64d-4d86a7c3f932",
            "sourceColumn": "Level 11",
            "summarizeBy": "none"
          },
          {
            "name": "Level 11 Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX('Item'[Item])",
              "    ,FILTER('Item','Item'[Item ID]='Product Hierarchy'[Level 11])",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "e5c5a657-2be8-4da0-9f52-ad50287e69a6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Level 11 Product Classification",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX('Item'[Product Classification Description])",
              "    ,FILTER('Item','Item'[Item ID]='Product Hierarchy'[Level 11])",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "c2ff417f-8520-4979-9d8f-ff47ebe38644",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Level 11 Product Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX('Item'[Product Type])",
              "    ,FILTER('Item','Item'[Item ID]='Product Hierarchy'[Level 11])",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "9bcc8c10-70bf-4295-96bf-9c11c1ddcc99",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Level 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d4ada33-47ff-412f-8f5a-3efc64cc53fb",
            "sourceColumn": "Level 2",
            "summarizeBy": "none"
          },
          {
            "name": "Level 3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ce9850a-5e21-4654-8e19-edc2b639730e",
            "sourceColumn": "Level 3",
            "summarizeBy": "none"
          },
          {
            "name": "Level 4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc9fbb24-c144-4795-9bea-67a71782405b",
            "sourceColumn": "Level 4",
            "summarizeBy": "none"
          },
          {
            "name": "Level 5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aac466c5-4b3e-4960-9376-e1a5fc0bb660",
            "sourceColumn": "Level 5",
            "summarizeBy": "none"
          },
          {
            "name": "Level 6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "856db7a8-b79b-4e47-8c61-78361af1bedf",
            "sourceColumn": "Level 6",
            "summarizeBy": "none"
          },
          {
            "name": "Level 7",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f61bbcb0-9675-4886-8225-f0f6716e6089",
            "sourceColumn": "Level 7",
            "summarizeBy": "none"
          },
          {
            "name": "Level 8",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c8346201-9d8d-4230-9307-a9aec8918cac",
            "sourceColumn": "Level 8",
            "summarizeBy": "none"
          },
          {
            "name": "Level 9",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "377a9529-a457-461d-85d0-b24c6a1f9d16",
            "sourceColumn": "Level 9",
            "summarizeBy": "none"
          },
          {
            "name": "Qty L1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "0.00",
            "lineageTag": "10a2a544-2f85-403f-b8aa-17ce946bf2d7",
            "sourceColumn": "Qty L1",
            "summarizeBy": "sum"
          },
          {
            "name": "Qty L10",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bcfa1055-a1e5-49ad-a49c-9331359f62c7",
            "sourceColumn": "Qty L10",
            "summarizeBy": "sum"
          },
          {
            "name": "Qty L11",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6c930fb7-157f-4655-b79f-263cefdacc58",
            "sourceColumn": "Qty L11",
            "summarizeBy": "sum"
          },
          {
            "name": "Qty L2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fd960493-7504-4717-8acb-5a2b4ab90052",
            "sourceColumn": "Qty L2",
            "summarizeBy": "sum"
          },
          {
            "name": "Qty L3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "72884244-4dc6-4c7c-8fa5-3dd58683648d",
            "sourceColumn": "Qty L3",
            "summarizeBy": "sum"
          },
          {
            "name": "Qty L4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ce9ae616-e81b-4367-89bb-d06f4e53959c",
            "sourceColumn": "Qty L4",
            "summarizeBy": "sum"
          },
          {
            "name": "Qty L5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "858ad0f9-e6b1-41fd-b84d-4aacbfce437f",
            "sourceColumn": "Qty L5",
            "summarizeBy": "sum"
          },
          {
            "name": "Qty L6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3aa4df3b-2021-4371-8047-902c20a3691c",
            "sourceColumn": "Qty L6",
            "summarizeBy": "sum"
          },
          {
            "name": "Qty L7",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4f019ebf-f368-4604-bc97-9d1de0f5a51d",
            "sourceColumn": "Qty L7",
            "summarizeBy": "sum"
          },
          {
            "name": "Qty L8",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b4dfdc0b-fee9-46ce-b628-c9db8c27f193",
            "sourceColumn": "Qty L8",
            "summarizeBy": "sum"
          },
          {
            "name": "Qty L9",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4586f7e7-a843-4d42-9869-5884350db742",
            "sourceColumn": "Qty L9",
            "summarizeBy": "sum"
          },
          {
            "name": "TOP GA Project ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a616a387-9354-46a4-b7f5-b353db1fb722",
            "sourceColumn": "TOP GA Project ID",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "Product Hierarchy",
            "levels": [
              {
                "name": "Level 0",
                "column": "Level 0",
                "lineageTag": "1c1b379e-7156-46de-91a7-be5e2546310f",
                "ordinal": 0
              },
              {
                "name": "Level 1",
                "column": "Level 1",
                "lineageTag": "da2bb5bc-fb0b-4fbd-9e61-1df9b8c4a212",
                "ordinal": 1
              },
              {
                "name": "Level 2",
                "column": "Level 2",
                "lineageTag": "290a8bbf-648a-40ae-bf42-e9d61d2e7752",
                "ordinal": 2
              },
              {
                "name": "Level 3",
                "column": "Level 3",
                "lineageTag": "5cfabe7d-b2e9-4ba5-8a01-5212c1da2aa9",
                "ordinal": 3
              },
              {
                "name": "Level 4",
                "column": "Level 4",
                "lineageTag": "5ccf8711-8d7a-4a5b-aa14-b8e135b4aec8",
                "ordinal": 4
              },
              {
                "name": "Level 5",
                "column": "Level 5",
                "lineageTag": "12dc2634-fecd-47cb-9c84-bc44d66c79d4",
                "ordinal": 5
              },
              {
                "name": "Level 6",
                "column": "Level 6",
                "lineageTag": "7bbdd17e-1da6-4fb7-ad15-683ba415721f",
                "ordinal": 6
              },
              {
                "name": "Level 7",
                "column": "Level 7",
                "lineageTag": "5f39cc5d-dd20-4e99-85b4-a21f7d460c5a",
                "ordinal": 7
              },
              {
                "name": "Level 8",
                "column": "Level 8",
                "lineageTag": "05eefb95-0ab2-4797-84f3-2e071ea959e6",
                "ordinal": 8
              },
              {
                "name": "Level 9",
                "column": "Level 9",
                "lineageTag": "bd748778-8953-4a6f-92cb-5bc1b2310011",
                "ordinal": 9
              },
              {
                "name": "Level 10",
                "column": "Level 10",
                "lineageTag": "ae4f66f7-7893-4ade-a432-c9f8943dd822",
                "ordinal": 10
              },
              {
                "name": "Level 11",
                "column": "Level 11",
                "lineageTag": "e1572888-6b77-4f60-a7c9-d3111eed9883",
                "ordinal": 11
              }
            ],
            "lineageTag": "33c18587-82bf-40e2-9c25-c30a244ad1a8"
          }
        ],
        "lineageTag": "d23866cd-abc6-4bb4-b0bd-27464922bfbd",
        "partitions": [
          {
            "name": "Product Hierarchy-b9b594b0-d9b0-4791-a6d9-4259d223a1f8",
            "mode": "import",
            "queryGroup": "Deltek",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    calculated_Product_Hierarchy_View = Source{[Schema=\"calculated\",Item=\"Product_Hierarchy_View\"]}[Data]",
                "in",
                "    calculated_Product_Hierarchy_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Project",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "Active Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fad6540f-d174-4729-a32b-0f9608fb332a",
            "sourceColumn": "Active Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Classification for MOR spread",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "204d8d81-fb37-433f-b9e3-d96f37c5b4eb",
            "sourceColumn": "Classification for MOR spread",
            "summarizeBy": "none"
          },
          {
            "name": "Company ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e041b97-3bd5-4b32-a6f7-373fc8e26970",
            "sourceColumn": "Company ID",
            "summarizeBy": "none"
          },
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02babc49-7622-4db4-8694-a3c89ac0abbf",
            "sourceColumn": "Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "94b5475f-dbea-4e4a-9c65-e021e72bef28",
            "sourceColumn": "Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "L1_PROJ_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9bd22dff-93d9-41d6-a887-d1541990a1a8",
            "sourceColumn": "L1_PROJ_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "Margin Product Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(Project[New Category TYPE - COGS]=\"Patient Other\",\"Patient Sim\",Project[Classification for MOR spread])"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "843c807c-c282-4f27-ab33-b0a1ad256f7b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "New Category TYPE - COGS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "808b6c80-9803-456b-8a1e-6382440876f5",
            "sourceColumn": "New Category TYPE - COGS",
            "summarizeBy": "none"
          },
          {
            "name": "New Planning classification",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e7f5f13b-b5eb-44c7-b593-19be001fe90e",
            "sourceColumn": "New Planning classification",
            "summarizeBy": "none"
          },
          {
            "name": "New Planning type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73ef69b1-9b48-409c-a3a4-11363b0c4c01",
            "sourceColumn": "New Planning type",
            "summarizeBy": "none"
          },
          {
            "name": "Note",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8565c079-1b5f-4c00-9a67-01f8e8bd4ace",
            "sourceColumn": "Note",
            "summarizeBy": "none"
          },
          {
            "name": "Organization ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9d8170e4-ca5b-47a3-a1be-86da54111dbd",
            "sourceColumn": "Organization ID",
            "summarizeBy": "none"
          },
          {
            "name": "Project End Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "bc6bb57f-f78f-4f19-8880-a463c09a6e87",
            "sourceColumn": "Project End Date",
            "summarizeBy": "none"
          },
          {
            "name": "Project ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a5191e4-a9bf-4d28-bbe0-5b7eab4b1c93",
            "sourceColumn": "Project ID",
            "summarizeBy": "none"
          },
          {
            "name": "Project Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e95db637-8c2a-460b-9824-2cf7b2801828",
            "sourceColumn": "Project Manager",
            "summarizeBy": "none"
          },
          {
            "name": "Project Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b5f8746-08b7-4e9e-b53d-e0182917e9df",
            "sourceColumn": "Project Name",
            "summarizeBy": "none"
          },
          {
            "name": "Project Notes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af5e6ac8-f2aa-4cc8-8951-0c5b8d1d8578",
            "sourceColumn": "Project Notes",
            "summarizeBy": "none"
          },
          {
            "name": "Project Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "a130d41b-c53d-4e14-a440-699b946a5243",
            "sourceColumn": "Project Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "Project Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "568934fc-dc01-45e4-b949-34b3bd158660",
            "sourceColumn": "Project Type",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d549a86a-e906-494f-85d1-8e629fed6e45",
        "partitions": [
          {
            "name": "Project-d4c4e9fc-2acb-46b6-961b-97c196299e1b",
            "mode": "import",
            "queryGroup": "Deltek",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    deltek_Project = Source{[Schema=\"deltek\",Item=\"Project\"]}[Data],",
                "    #\"Merged Queries\" = Table.NestedJoin(deltek_Project, {\"Project ID\"}, #\"Revenue Margin Project Mapping\", {\"Project ID\"}, \"Revenue Margin Project Mapping\", JoinKind.LeftOuter),",
                "    #\"Expanded Revenue Margin Project Mapping\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Revenue Margin Project Mapping\", {\"New Category TYPE - COGS\", \"Classification for MOR spread\", \"New Planning type\", \"New Planning classification\", \"Note\"}, {\"New Category TYPE - COGS\", \"Classification for MOR spread\", \"New Planning type\", \"New Planning classification\", \"Note\"})",
                "in",
                "    #\"Expanded Revenue Margin Project Mapping\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Project Code",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Product BOM's",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'Project Code'[ProjectK] & \" - \" & 'Project Code'[Project]",
            "isDataTypeInferred": true,
            "lineageTag": "0b121632-cf80-42d6-824a-49077b404369",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Project",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "67f92ca1-59d7-4ae2-a6cf-b97e3d06193a",
            "sourceColumn": "Project",
            "summarizeBy": "none"
          },
          {
            "name": "Project Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf406054-d901-4d97-8547-52d7df994225",
            "sourceColumn": "Project Code",
            "summarizeBy": "none"
          },
          {
            "name": "ProjectK",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "069a8463-d424-4dd4-9de7-70ec3fe0cc21",
            "sourceColumn": "ProjectK",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "49bd0ea1-5053-4ba4-a732-0a947292716c",
        "partitions": [
          {
            "name": "Project Code-620f97ea-e36e-483e-993b-be8b43dcd534",
            "mode": "import",
            "queryGroup": "Deltek",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"lZZLbus2FIa3QmSUCySI9ZaGiqzUxrVsw3JcFGkGjMzYRGVJ1SOP2d1DN9C1dCld\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Project Code\" = _t, Project = _t, ProjectK = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Project Code\", type text}, {\"Project\", type text}, {\"ProjectK\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Quantity / Value Selection",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Quantity or Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11837bcd-a31e-40a5-9b8a-762d2a79ad26",
            "sourceColumn": "Quantity or Value",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "429a9484-0fb8-4b82-99b7-a0df129f3e0c",
        "partitions": [
          {
            "name": "Quantity / Value Selection-5c71d6f4-7405-42b4-8e88-f90f8d2cf902",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCixNzCvJLKlUitWJVgpLzClNVVBRio0FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Quantity or Value\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Quantity or Value\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Requisition Lines",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Completion Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9519521a-062f-4a58-a888-cf0ddb986185",
            "sourceColumn": "Completion Date",
            "summarizeBy": "none"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74276eb6-ab37-4335-882c-101b4f883bdf",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "Generated Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b4a0643d-bb0f-40da-bd17-a0a53f662333",
            "sourceColumn": "Generated Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Generated Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "98633f9f-f048-450b-a5fa-c5e8130a4cc8",
            "sourceColumn": "Generated Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Inventory Abbreviation Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "116b13d2-f090-44c4-96c6-71aa7a3a7bbe",
            "sourceColumn": "Inventory Abbreviation Code",
            "summarizeBy": "none"
          },
          {
            "name": "Item ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0aaec3a8-5560-472d-8903-d97b72b96103",
            "sourceColumn": "Item ID",
            "summarizeBy": "none"
          },
          {
            "name": "Net Unit Cost Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bbdea1b2-33de-46cf-a365-5f29cfb15965",
            "sourceColumn": "Net Unit Cost Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "OUM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dcd14ca5-7fda-4a43-9632-8203ec6103f0",
            "sourceColumn": "OUM",
            "summarizeBy": "none"
          },
          {
            "name": "PO Line Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44e232e3-d4d5-431b-8fd2-f17502ea1779",
            "sourceColumn": "PO Line Type",
            "summarizeBy": "none"
          },
          {
            "name": "Requested Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "26e5d6f7-325f-4006-9cd6-33dddafe9680",
            "sourceColumn": "Requested Date",
            "summarizeBy": "none"
          },
          {
            "name": "Requested Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7d33d928-a3fe-480b-a054-0196f6fef40c",
            "sourceColumn": "Requested Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Requisition Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "38f8a78e-0253-4802-a21c-000cb57afe61",
            "sourceColumn": "Requisition Date",
            "summarizeBy": "none"
          },
          {
            "name": "Requisition ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad13cf34-39ac-4154-8753-d950b073f457",
            "sourceColumn": "Requisition ID",
            "summarizeBy": "none"
          },
          {
            "name": "Requisition Line Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c3c8d634-3307-4f76-b217-ecb908a94131",
            "sourceColumn": "Requisition Line Key",
            "summarizeBy": "count"
          },
          {
            "name": "Requisition Line Nr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2a9f1343-46aa-4c0d-b223-d935acffcf12",
            "sourceColumn": "Requisition Line Nr",
            "summarizeBy": "sum"
          },
          {
            "name": "Requisition Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "10545188-0ad9-428c-ac3d-aa2a12aba0f9",
            "sourceColumn": "Requisition Status",
            "summarizeBy": "none"
          },
          {
            "name": "Timestamp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f03087e5-9932-4385-917c-87867667904a",
            "sourceColumn": "Timestamp",
            "summarizeBy": "none"
          },
          {
            "name": "req_vs_compl",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              " DATEDIFF('Requisition Lines'[Requisition Date],'Requisition Lines'[Completion Date],DAY)"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "401bf603-5fc4-4380-af88-71fa5508f57a",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "250bab51-4289-47a6-a528-58c1bfa25674",
        "measures": [
          {
            "name": "RQcount",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "COUNTROWS('Requisition Lines')",
            "lineageTag": "eb89c5be-0e03-4fc0-ab94-b3b24cb3c923"
          }
        ],
        "partitions": [
          {
            "name": "Requisition Lines-cd01897f-ba66-422d-8745-47ab4b83e710",
            "mode": "import",
            "queryGroup": "Deltek",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    deltek_Requisition_Lines = Source{[Schema=\"deltek\",Item=\"Requisition_Lines\"]}[Data]",
                "in",
                "    deltek_Requisition_Lines"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Requisition Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "description": "This section contains Sales Order related measures",
        "lineageTag": "bbf04463-7d63-45fb-89c0-256f91908fc4",
        "measures": [
          {
            "name": "Requested Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUM('Requisition Lines'[Requested Quantity])"
            ],
            "formatString": "#,0",
            "lineageTag": "f75fb5ff-5a71-49a8-9aa5-1aac2f9dde93"
          },
          {
            "name": "Requested Value",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              " SUMX(",
              "     'Requisition Lines'",
              "     ,'Requisition Lines'[Net Unit Cost Amount]*'Requisition Lines'[Requested Quantity]",
              " )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "80f775e0-457a-4f98-aa56-6ab43bdb9d59"
          },
          {
            "name": "Requisitions",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH(",
              "    TRUE()",
              "    ,SELECTEDVALUE('Quantity / Value Selection'[Quantity or Value])=\"Quantity\",[Requested Quantity]",
              "    ,SELECTEDVALUE('Quantity / Value Selection'[Quantity or Value])=\"Value $\",[Requested Value]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "0032b5f9-fcc2-45bd-a253-0bd038b10e10"
          },
          {
            "name": "Requisitions running total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [Requisitions]",
              "    ,FILTER(ALL('Calendar'),'Calendar'[Date]<=MAX('Calendar'[Date]))",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "387a3078-2fa4-4769-b55a-0ae9e88f85c6"
          }
        ],
        "partitions": [
          {
            "name": "Requisition Measures-f9eb5561-94be-44ad-b297-ccbad4c2ea24",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales Order Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "description": "This section contains Sales Order related measures",
        "lineageTag": "f26430c4-a221-442f-a0e6-85b0d992c8c2",
        "measures": [
          {
            "name": "Total Shipments",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "Calculates value of order by Shipment Date",
            "displayFolder": "Core",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [Total Spread Amount Shipment]",
              "    ,FILTER('Ship Trn'",
              "    ,'Ship Trn'[Shipment Status]  IN {\"Shipped\"}",
              "    --&&NOT('Ship Trn'[Issue Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    --&&RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\"",
              ")",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "43f40698-7f3a-4f86-bdc6-a9a2bfd5d291"
          },
          {
            "name": "Paced Shipments Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Targets",
            "expression": [
              "",
              "",
              "var lastrefreshment = DATE(YEAR(MAX('Last Refreshment'[Last Refreshment UTC])),MONTH(MAX('Last Refreshment'[Last Refreshment UTC])),DAY(MAX('Last Refreshment'[Last Refreshment UTC])))",
              "",
              "var todatetarget =",
              "",
              "IF (",
              "    HASONEVALUE ( 'Currency Selection'[Currency] ),",
              "    IF (",
              "        SELECTEDVALUE ( 'Currency Selection'[Currency] ) = \"USD\",",
              "        SUMX('Shipment Targets','Shipment Targets'[Daily Shipment Target USD]*IF(RELATED('Calendar'[Date])<lastrefreshment,1,0)),",
              "        SUMX('Shipment Targets','Shipment Targets'[Daily Shipment Target CAD]*IF(RELATED('Calendar'[Date])<lastrefreshment,1,0))",
              "    ),",
              "    SUMX('Shipment Targets','Shipment Targets'[Daily Shipment Target USD]*IF(RELATED('Calendar'[Date])<lastrefreshment,1,0))",
              ")",
              "",
              "RETURN",
              "",
              "todatetarget"
            ],
            "lineageTag": "53d3ff15-96d2-42d5-bfaa-f52946d0ddde"
          },
          {
            "name": "Total Order Intake",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "Calculates value of order by Order Date",
            "displayFolder": "Core",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [Total Value]",
              "    ,FILTER('Sales Orders'",
              "    ,NOT('Sales Orders'[Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&'Sales Orders'[Sales Group Inclusion] = \"Include\"",
              ")",
              ")"
            ],
            "lineageTag": "f9fe2a12-8813-4236-9f7a-145dcf87ed38"
          },
          {
            "name": "Net BOBL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "Net Back Order BackLog: Calculates Total Shipments with the following filters: the sales order line status is \"O\", the sales order is approved, the line type is INV or INT, Ship status is blank, Order-Shipment and Invoice quantities are not equal, there are no invoice components and invoice quantity is 0.",
            "displayFolder": "Core",
            "expression": [
              "",
              "",
              "VAR pastdueValue =",
              "CALCULATE(",
              "    [Total Spread Amount Shipment]",
              "    ,FILTER('Ship Trn'",
              "    ,'Ship Trn'[Shipment Status]  IN {\"Open\"}",
              "    &&NOT('Ship Trn'[Issue Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\"",
              "    &&'Ship Trn'[Shipment / Ship By Date]<TODAY()",
              ")",
              ")",
              "",
              "",
              "VAR futureValue =",
              "CALCULATE(",
              "    [Total Spread Amount Shipment]",
              "    ,FILTER('Ship Trn'",
              "    ,'Ship Trn'[Shipment Status]  IN {\"Open\"}",
              "    &&NOT('Ship Trn'[Issue Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\"",
              "    &&'Ship Trn'[Shipment / Ship By Date]>=TODAY()",
              ")",
              ")",
              "",
              "VAR pastdueQty =",
              "CALCULATE(",
              "    [Total Quantity]",
              "    ,FILTER('Ship Trn'",
              "    ,'Ship Trn'[Shipment Status]  IN {\"Open\"}",
              "    &&NOT('Ship Trn'[Issue Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\"",
              "    &&'Ship Trn'[Shipment / Ship By Date]<TODAY()",
              ")",
              ")",
              "",
              "",
              "VAR futureQty =",
              "CALCULATE(",
              "    [Total Quantity]",
              "    ,FILTER('Ship Trn'",
              "    ,'Ship Trn'[Shipment Status]  IN {\"Open\"}",
              "    &&NOT('Ship Trn'[Issue Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\"",
              "    &&'Ship Trn'[Shipment / Ship By Date]>=TODAY()",
              ")",
              ")",
              "",
              "RETURN",
              "",
              "SWITCH(",
              "    TRUE()",
              "    ,SELECTEDVALUE('Quantity / Value Selection'[Quantity or Value]) = \"Quantity\"",
              "        ,IF(MIN('BOBL Date'[BOBL Date])=\"Past Due\"||MAX('BOBL Date'[BOBL Date])=\"Past Due\",pastdueQty)",
              "        +",
              "        IF(MIN('BOBL Date'[BOBL Date])=\"Future\"||MAX('BOBL Date'[BOBL Date])=\"Future\",futureQty)",
              "    ,IF(MIN('BOBL Date'[BOBL Date])=\"Past Due\"||MAX('BOBL Date'[BOBL Date])=\"Past Due\",pastdueValue)",
              "    +",
              "    IF(MIN('BOBL Date'[BOBL Date])=\"Future\"||MAX('BOBL Date'[BOBL Date])=\"Future\",futureValue)",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "2b0d31fe-677a-4029-b4ed-9797333e0128"
          },
          {
            "name": "Gross BOBL (Risk)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "Gross Back Order BackLog: Calculates Total Shipments with the following filters: the sales order line status is \"O\", the sales order is approved, the line type is INV or INT, Ship status is blank, On-hold or Pending, Order-Shipment and Invoice quantities are not equal, there are no invoice components and invoice quantity is 0.",
            "displayFolder": "Core",
            "expression": [
              "",
              "",
              "VAR pastdueValue =",
              "CALCULATE(",
              "    [Total Spread Amount Shipment]",
              "    ,FILTER('Ship Trn'",
              "    ,'Ship Trn'[Shipment Status]  IN {\"Open\",\"On-Hold\",\"Pending\"}",
              "    &&NOT('Ship Trn'[Issue Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\"",
              "    &&'Ship Trn'[Shipment / Ship By Date]<TODAY()",
              ")",
              ")",
              "",
              "",
              "VAR futureValue =",
              "CALCULATE(",
              "    [Total Spread Amount Shipment]",
              "    ,FILTER('Ship Trn'",
              "    ,'Ship Trn'[Shipment Status]  IN {\"Open\",\"On-Hold\",\"Pending\"}",
              "    &&NOT('Ship Trn'[Issue Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\"",
              "    &&'Ship Trn'[Shipment / Ship By Date]>=TODAY()",
              ")",
              ")",
              "",
              "VAR pastdueQty =",
              "CALCULATE(",
              "    [Total Quantity]",
              "    ,FILTER('Ship Trn'",
              "    ,'Ship Trn'[Shipment Status]  IN {\"Open\",\"On-Hold\",\"Pending\"}",
              "    &&NOT('Ship Trn'[Issue Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\"",
              "    &&'Ship Trn'[Shipment / Ship By Date]<TODAY()",
              ")",
              ")",
              "",
              "",
              "VAR futureQty =",
              "CALCULATE(",
              "    [Total Quantity]",
              "    ,FILTER('Ship Trn'",
              "    ,'Ship Trn'[Shipment Status]  IN {\"Open\",\"On-Hold\",\"Pending\"}",
              "    &&NOT('Ship Trn'[Issue Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\"",
              "    &&'Ship Trn'[Shipment / Ship By Date]>=TODAY()",
              ")",
              ")",
              "",
              "RETURN",
              "",
              "SWITCH(",
              "    TRUE()",
              "    ,SELECTEDVALUE('Quantity / Value Selection'[Quantity or Value]) = \"Quantity\"",
              "        ,IF(MIN('BOBL Date'[BOBL Date])=\"Past Due\"||MAX('BOBL Date'[BOBL Date])=\"Past Due\",pastdueQty)",
              "        +",
              "        IF(MIN('BOBL Date'[BOBL Date])=\"Future\"||MAX('BOBL Date'[BOBL Date])=\"Future\",futureQty)",
              "    ,IF(MIN('BOBL Date'[BOBL Date])=\"Past Due\"||MAX('BOBL Date'[BOBL Date])=\"Past Due\",pastdueValue)",
              "    +",
              "    IF(MIN('BOBL Date'[BOBL Date])=\"Future\"||MAX('BOBL Date'[BOBL Date])=\"Future\",futureValue)",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "1972da70-2427-4295-8dd1-5d67e214bcc9"
          },
          {
            "name": "Total Order Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "Calculates total quantity of orders by Order ",
              "Date"
            ],
            "displayFolder": "Core",
            "expression": [
              "",
              "CALCULATE(",
              "    SUMX(",
              "    FILTER('Sales Orders'",
              "    ,NOT('Sales Orders'[Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&'Sales Orders'[Sales Group Inclusion] = \"Include\"",
              "    )",
              "    ,'Sales Orders'[Order Quantity]",
              "    )",
              "    ,USERELATIONSHIP ( 'Sales Orders'[Order Date], 'Calendar'[Date] )",
              ")"
            ],
            "lineageTag": "c55e48d2-3ad8-41fb-ae00-4b1b34fde0f5"
          },
          {
            "name": "Total Shipment Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "Calculates total quantity of orders by Shipment Date",
            "displayFolder": "Core",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    SUM('Ship Trn'[Issue Shipment Quantity])",
              "    ,FILTER('Ship Trn'",
              "    ,'Ship Trn'[Shipment Status]  IN {\"Shipped\"}",
              "    &&NOT('Ship Trn'[Issue Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\"",
              ")",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "07e01dca-da48-484f-aa87-226ba2a25385"
          },
          {
            "name": "Total Shipment Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Core",
            "expression": [
              "",
              "",
              "IF (",
              "    HASONEVALUE ( 'Currency Selection'[Currency] ),",
              "    IF (",
              "        SELECTEDVALUE ( 'Currency Selection'[Currency] ) = \"USD\",",
              "        SUMX ( 'Sales Orders' , 'Sales Orders'[Item_cost_USD] * 'Sales Orders'[Shipment Quantity] ),",
              "        SUMX ( 'Sales Orders' , 'Sales Orders'[Item_cost_CAD] * 'Sales Orders'[Shipment Quantity] )",
              "    ),",
              "    SUMX ( 'Sales Orders' , 'Sales Orders'[Item_cost_USD] * 'Sales Orders'[Shipment Quantity] )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "32006db3-dbed-4d92-b679-dc8b207ebce0"
          },
          {
            "name": "Total Order Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Core",
            "expression": [
              "",
              "CALCULATE(",
              "IF (",
              "    HASONEVALUE ( 'Currency Selection'[Currency] ),",
              "    IF (",
              "        SELECTEDVALUE ( 'Currency Selection'[Currency] ) = \"USD\",",
              "        SUMX ( 'Sales Orders' , 'Sales Orders'[Item_cost_USD] * 'Sales Orders'[Order Quantity] ),",
              "        SUMX ( 'Sales Orders' , 'Sales Orders'[Item_cost_CAD] * 'Sales Orders'[Order Quantity] )",
              "    ),",
              "    SUMX ( 'Sales Orders' , 'Sales Orders'[Item_cost_USD] * 'Sales Orders'[Order Quantity] )",
              ")",
              ",USERELATIONSHIP ( 'Sales Orders'[Order Date], 'Calendar'[Date] )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "864870fa-699f-443e-8739-83830d3ba122"
          },
          {
            "name": "Total Value by Measure Selection",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Core",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE()",
              "    ,SELECTEDVALUE('Measure Selection'[Measure]) = \"Total Shipments $\",[Total Shipments]",
              "    ,SELECTEDVALUE('Measure Selection'[Measure]) = \"Total Shipment Quantity\",[Total Shipment Quantity]",
              "    ,SELECTEDVALUE('Measure Selection'[Measure]) = \"Total Order Intake $\",[Total Order Intake]",
              "    ,SELECTEDVALUE('Measure Selection'[Measure]) = \"Total Order Quantity\",[Total Order Quantity]",
              "    ,SELECTEDVALUE('Measure Selection'[Measure]) = \"Net BOBL $\",[Net BOBL]",
              "    ,SELECTEDVALUE('Measure Selection'[Measure]) = \"Gross BOBL (Risk) $\",[Gross BOBL (Risk)]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "6a35c234-0d3e-446d-82fe-175ec2ce7a3a"
          },
          {
            "name": "Total Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Core",
            "expression": [
              "",
              "CALCULATE(",
              "    IF (",
              "        HASONEVALUE ( 'Currency Selection'[Currency] ),",
              "        IF (",
              "            SELECTEDVALUE ( 'Currency Selection'[Currency] ) = \"USD\",",
              "            SUM ( 'Ship Trn'[Spreaded Extended Amount USD] ),",
              "            SUM ( 'Ship Trn'[Spreaded Extended Amount CAD] )",
              "        ),",
              "        SUM ( 'Ship Trn'[Spreaded Extended Amount USD] )",
              "    )",
              "    ,USERELATIONSHIP('Calendar'[Date],'Sales Orders'[Order Date])",
              ")"
            ],
            "lineageTag": "5c1f1c27-d04a-4d33-a6b3-4de6da732666"
          },
          {
            "name": "On-Hold and Pending Shipments",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Core",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [Total Spread Amount Shipment]",
              "    ,FILTER('Ship Trn'",
              "    ,'Ship Trn'[Shipment Status]  IN {\"On-Hold\",\"Pending\"}",
              "    &&NOT('Ship Trn'[Issue Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\"",
              ")",
              ")"
            ],
            "lineageTag": "27cfd719-48a5-4203-91fd-78d6b72e1d15"
          },
          {
            "name": "Total Shipments Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Targets",
            "expression": [
              "",
              "",
              "var totaltarget =",
              "",
              "IF (",
              "    HASONEVALUE ( 'Currency Selection'[Currency] ),",
              "    IF (",
              "        SELECTEDVALUE ( 'Currency Selection'[Currency] ) = \"USD\",",
              "        SUM('Shipment Targets'[Daily Shipment Target USD]),",
              "        SUM('Shipment Targets'[Daily Shipment Target CAD])",
              "    ),",
              "    SUM('Shipment Targets'[Daily Shipment Target USD])",
              ")",
              "",
              "RETURN",
              "",
              "totaltarget"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "7730a59f-9553-489c-b2fd-7cb04e1ffafb"
          },
          {
            "name": "Total Shipments Forecast",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Targets",
            "expression": [
              "",
              "",
              "var totalfcst =",
              "",
              "IF (",
              "    HASONEVALUE ( 'Currency Selection'[Currency] ),",
              "    IF (",
              "        SELECTEDVALUE ( 'Currency Selection'[Currency] ) = \"USD\",",
              "        SUM('Shipment Targets'[Daily Shipment Forecast USD]),",
              "        SUM('Shipment Targets'[Daily Shipment Forecast CAD])",
              "    ),",
              "    SUM('Shipment Targets'[Daily Shipment Forecast USD])",
              ")",
              "",
              "RETURN",
              "",
              "totalfcst"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "89b731d9-fe03-42de-96b7-47d1f7ca3123"
          },
          {
            "name": "Paced Shipments Forecast",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Targets",
            "expression": [
              "",
              "",
              "var lastrefreshment = DATE(YEAR(MAX('Last Refreshment'[Last Refreshment UTC])),MONTH(MAX('Last Refreshment'[Last Refreshment UTC])),DAY(MAX('Last Refreshment'[Last Refreshment UTC])))",
              "",
              "var todatefcst =",
              "",
              "IF (",
              "    HASONEVALUE ( 'Currency Selection'[Currency] ),",
              "    IF (",
              "        SELECTEDVALUE ( 'Currency Selection'[Currency] ) = \"USD\",",
              "        SUMX('Shipment Targets','Shipment Targets'[Daily Shipment Forecast USD]*IF(RELATED('Calendar'[Date])<lastrefreshment,1,0)),",
              "        SUMX('Shipment Targets','Shipment Targets'[Daily Shipment Forecast CAD]*IF(RELATED('Calendar'[Date])<lastrefreshment,1,0))",
              "    ),",
              "    SUMX('Shipment Targets','Shipment Targets'[Daily Shipment Forecast USD]*IF(RELATED('Calendar'[Date])<lastrefreshment,1,0))",
              ")",
              "",
              "RETURN",
              "",
              "todatefcst"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "5970402b-ad49-451a-a142-e6910be94d8b"
          },
          {
            "name": "Paced Shipments Minimum Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Targets",
            "expression": [
              "",
              "",
              "var lastrefreshment = DATE(YEAR(MAX('Last Refreshment'[Last Refreshment UTC])),MONTH(MAX('Last Refreshment'[Last Refreshment UTC])),DAY(MAX('Last Refreshment'[Last Refreshment UTC])))",
              "",
              "var todatemintarget =",
              "",
              "IF (",
              "    HASONEVALUE ( 'Currency Selection'[Currency] ),",
              "    IF (",
              "        SELECTEDVALUE ( 'Currency Selection'[Currency] ) = \"USD\",",
              "        SUMX('Shipment Targets','Shipment Targets'[Daily Shipment Min Target USD]*IF(RELATED('Calendar'[Date])<lastrefreshment,1,0)),",
              "        SUMX('Shipment Targets','Shipment Targets'[Daily Shipment Min Target CAD]*IF(RELATED('Calendar'[Date])<lastrefreshment,1,0))",
              "    ),",
              "    SUMX('Shipment Targets','Shipment Targets'[Daily Shipment Min Target USD]*IF(RELATED('Calendar'[Date])<lastrefreshment,1,0))",
              ")",
              "",
              "RETURN",
              "",
              "todatemintarget"
            ],
            "lineageTag": "fa4e8bb5-f3e1-4978-ad59-55cb1f8036e1"
          },
          {
            "name": "Total Shipments Minimum Target",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Targets",
            "expression": [
              "",
              "",
              "var totalmintarget =",
              "",
              "IF (",
              "    HASONEVALUE ( 'Currency Selection'[Currency] ),",
              "    IF (",
              "        SELECTEDVALUE ( 'Currency Selection'[Currency] ) = \"USD\",",
              "        SUM('Shipment Targets'[Daily Shipment Min Target USD]),",
              "        SUM('Shipment Targets'[Daily Shipment Min Target CAD])",
              "    ),",
              "    SUM('Shipment Targets'[Daily Shipment Min Target USD])",
              ")",
              "",
              "RETURN",
              "",
              "totalmintarget"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "af5bf00d-599f-488b-af18-c0a64d2d7580"
          },
          {
            "name": "Backlog",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Core",
            "expression": [
              "",
              "",
              "var backlogvalue =",
              "CALCULATE(",
              "    [Total Spread Amount Shipment]",
              "    ,FILTER('Ship Trn'",
              "    ,'Ship Trn'[Shipment Status]  IN {\"Open\"}",
              "    &&NOT('Ship Trn'[Issue Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\"",
              "))",
              "",
              "var backlogqty =",
              "CALCULATE(",
              "    [Total Quantity]",
              "    ,FILTER('Ship Trn'",
              "    ,'Ship Trn'[Shipment Status]  IN {\"Open\"}",
              "    &&NOT('Ship Trn'[Issue Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\"",
              "))",
              "",
              "RETURN",
              "",
              "SWITCH(",
              "    TRUE()",
              "    ,SELECTEDVALUE('Quantity / Value Selection'[Quantity or Value]) = \"Quantity\",backlogqty",
              "    ,backlogvalue",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "fb61cb81-42d1-45e5-8204-57c0d51dd839"
          },
          {
            "name": "MPS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Core",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE()",
              "    ,SELECTEDVALUE('Quantity / Value Selection'[Quantity or Value]) = \"Quantity\", SUM('MPS Forecast'[Open Sales Forecast Quantity])",
              "    ,SELECTEDVALUE('Quantity / Value Selection'[Quantity or Value]) = \"Value $\", SUMX('MPS Forecast','MPS Forecast'[Open Sales Forecast Quantity]*RELATED('Item'[Item Unit Cost Amount]))",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "762ba640-72a4-4de9-a63e-88fa95a110c1"
          },
          {
            "name": "WIP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Core",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE()",
              "    ,SELECTEDVALUE('Quantity / Value Selection'[Quantity or Value]) = \"Value $\",SUMX(FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"In Shop\"),'Manufacturing Data'[Open Qty]*RELATED('Item'[Item Average Price]))",
              "    ,SUMX(FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"In Shop\"),'Manufacturing Data'[Open Qty])",
              ")"
            ],
            "lineageTag": "c026a553-b27d-49b3-9cec-eba4d9b1a398"
          },
          {
            "name": "MPS running total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Running Totals",
            "expression": [
              "",
              "CALCULATE(",
              "    [MPS]",
              "    ,FILTER(ALLSELECTED('Calendar'),'Calendar'[Date]<=MAX('Calendar'[Date])&&'Calendar'[Date]>=TODAY())",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "df9f1587-4826-426b-9944-a8768014207c"
          },
          {
            "name": "Backlog running total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Running Totals",
            "expression": [
              "",
              "CALCULATE(",
              "    [Backlog]",
              "    ,FILTER(ALLSELECTED('Calendar'),'Calendar'[Date]<=MAX('Calendar'[Date])&&'Calendar'[Date]>=TODAY())",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "428c979e-86db-438e-bc4e-63a4ec0314dd"
          },
          {
            "name": "On-Hold and Pending Shipments Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Core",
            "expression": [
              "",
              "",
              "VAR Result =",
              "",
              "CALCULATE(",
              "    ",
              "    SUM('Ship Trn'[Issue Shipment Quantity])",
              "",
              "    ,FILTER('Ship Trn'",
              "    ,'Ship Trn'[Shipment Status]  IN {\"On-Hold\",\"Pending\"}",
              "    &&NOT('Ship Trn'[Issue Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\"",
              "    )",
              "",
              ")",
              "",
              "RETURN",
              "",
              "Result"
            ],
            "formatString": "#,0",
            "lineageTag": "facb1c89-98f9-43d5-8ffa-e3defdfb8e86"
          },
          {
            "name": "Total Open Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Core",
            "expression": [
              "",
              "SUMX(",
              "    FILTER('Ship Trn'",
              "    ,'Ship Trn'[Shipment Status]  IN {\"Open\"}",
              "    &&NOT('Ship Trn'[Issue Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\")",
              "    ,RELATED('Sales Orders'[Order Quantity])-'Ship Trn'[Issued Quantity]",
              ")",
              ""
            ],
            "lineageTag": "f6c46d47-5b61-431b-922a-5c141f88f8e9"
          },
          {
            "name": "Backlog by Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Core",
            "expression": [
              "",
              "",
              "SUMX(",
              "    FILTER('Ship Trn'",
              "    ,'Ship Trn'[Shipment Status]  IN {\"Open\"}",
              "    &&NOT('Ship Trn'[Issue Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\"",
              "    )",
              "    ,SWITCH(",
              "            TRUE()",
              "            ,SELECTEDVALUE('Quantity / Value Selection'[Quantity or Value]) = \"Quantity\",RELATED('Sales Orders'[Order Quantity])-'Ship Trn'[Issued Quantity]",
              "            ,'Ship Trn'[Unit Cost Amount]*(RELATED('Sales Orders'[Order Quantity])-'Ship Trn'[Issued Quantity])",
              "        )",
              "    )",
              ""
            ],
            "lineageTag": "ef4b0337-2a42-4e24-8181-4ebdf5930601"
          },
          {
            "name": "MPS running total all",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Running Totals",
            "expression": [
              "",
              "CALCULATE(",
              "    [MPS]",
              "    ,FILTER(ALL('Calendar'),'Calendar'[Date]<=MAX('Calendar'[Date]))",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "3d240246-d733-4ac5-9819-d3e97d3b3eef"
          },
          {
            "name": "Backlog by Cost running total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Running Totals",
            "expression": [
              "",
              "CALCULATE(",
              "    [Backlog by Cost]",
              "    ,FILTER(ALL('Calendar'),'Calendar'[Date]<=MAX('Calendar'[Date]))",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "5aee4087-fcc4-4b6a-a30d-e7ec4fa8c8a8"
          },
          {
            "name": "Total Staged",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Core",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [Total Spread Amount Shipment]",
              "    ,FILTER('Ship Trn'",
              "    ,'Ship Trn'[Shipment Status]  IN {\"Staged\"}",
              "    &&NOT('Ship Trn'[Issue Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\"",
              "    &&RELATED('Sales Orders'[SO Line Status]) = \"O\"",
              ")",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "13bcd19b-2816-4f1f-aead-e71e2ea78add"
          },
          {
            "name": "Total Staged Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Core",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    SUM('Ship Trn'[Issued Quantity])",
              "    ,FILTER('Ship Trn'",
              "    ,'Ship Trn'[Shipment Status]  IN {\"Staged\"}",
              "    &&NOT('Ship Trn'[Issue Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\"",
              "    &&RELATED('Sales Orders'[SO Line Status]) = \"O\"",
              ")",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "0f2a93aa-480e-43ca-b76c-8672d1e7457f"
          },
          {
            "name": "On-Hold Shipments",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Core",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [Total Spread Amount Shipment]",
              "    ,FILTER('Ship Trn'",
              "    ,'Ship Trn'[Shipment Status]  IN {\"On-Hold\"}",
              "    &&NOT('Ship Trn'[Issue Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\"",
              ")",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "03fbe49f-4683-41d6-a485-54a0cb38af44"
          },
          {
            "name": "Pending Shipments",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Core",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [Total Spread Amount Shipment]",
              "    ,FILTER('Ship Trn'",
              "    ,'Ship Trn'[Shipment Status]  IN {\"Pending\"}",
              "    &&NOT('Ship Trn'[Issue Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\"",
              ")",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "40e093f6-3bac-411b-a3fc-d6b3ab1d2b07"
          },
          {
            "name": "On-Hold Shipments Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Core",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "",
              "    SUM('Ship Trn'[Issue Shipment Quantity])",
              "",
              "    ,FILTER('Ship Trn'",
              "    ,'Ship Trn'[Shipment Status]  IN {\"On-Hold\"}",
              "    &&NOT('Ship Trn'[Issue Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\"",
              ")",
              "",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "4796cdfc-86c7-42b3-a9d7-c2802d265d10"
          },
          {
            "name": "Pending Shipments Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Core",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "",
              "    SUM('Ship Trn'[Issue Shipment Quantity])",
              "",
              "    ,FILTER('Ship Trn'",
              "    ,'Ship Trn'[Shipment Status]  IN {\"Pending\"}",
              "    &&NOT('Ship Trn'[Issue Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\"",
              ")",
              ")",
              "",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "6e186ad4-b2de-45c9-bf67-cc35515ef811"
          },
          {
            "name": "Total Spread Amount Shipment",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Core",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( 'Currency Selection'[Currency] ),",
              "        IF (",
              "            SELECTEDVALUE ( 'Currency Selection'[Currency] ) = \"USD\",",
              "            SUM ( 'Ship Trn'[Spreaded Extended Amount USD] ),",
              "            SUM ( 'Ship Trn'[Spreaded Extended Amount CAD] )",
              "        ),",
              "        SUM ( 'Ship Trn'[Spreaded Extended Amount USD] )",
              "    )",
              ""
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a3132b5e-3439-4cbf-9148-c50d4501c3fb"
          },
          {
            "name": "Total Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Core",
            "expression": [
              "",
              " SUM('Ship Trn'[Quantity])"
            ],
            "lineageTag": "09108420-bb0c-40a5-9b09-fd0260d71d32"
          },
          {
            "name": "Total Net Shipment Quantity (Kits not exploded)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Core",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    SUMX('Ship Trn','Ship Trn'[Issue Shipment Quantity]/CALCULATE(COUNTROWS('Ship Trn'),ALLEXCEPT('Ship Trn','Ship Trn'[Sales Order Number],'Ship Trn'[Kit Item ID],'Ship Trn'[Net Shipment Flag])))",
              "    ,FILTER('Ship Trn'",
              "    ,'Ship Trn'[Shipment Status]  IN {\"Shipped\"}",
              "    &&NOT('Ship Trn'[Issue Item ID] in {\"CREDIT\",\"TRADE - IN\"})",
              "    &&RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\"",
              ")",
              ")"
            ],
            "lineageTag": "a1134de2-dfed-4a8e-afcb-2480e699494f"
          }
        ],
        "partitions": [
          {
            "name": "Sales Order Measures-d836c032-3218-4722-bd3d-6765389f863a",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales Orders",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "Base Unit Price Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "52cf7cc9-f823-43c5-956e-59f046467dd6",
            "sourceColumn": "Base Unit Price Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Company ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa33a1b3-4620-4ca8-a527-507b39333f90",
            "sourceColumn": "Company ID",
            "summarizeBy": "none"
          },
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "afccd32d-ac03-4e8d-ae39-ce8ec573e495",
            "sourceColumn": "Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc55cef6-9bff-4595-b13c-b61ee083d88f",
            "sourceColumn": "Customer Key",
            "summarizeBy": "none"
          },
          {
            "name": "Customer PO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "49549e4d-dadc-40c7-83ce-57eaba248d52",
            "sourceColumn": "Customer PO",
            "summarizeBy": "none"
          },
          {
            "name": "Customer_Modification__ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5d17e11-2f78-4a1e-9b40-391496609273",
            "sourceColumn": "Customer_Modification__ID",
            "summarizeBy": "none"
          },
          {
            "name": "Customer_Purchase_Order_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2aef9457-dacf-4ccd-84c5-ab9b92cd0441",
            "sourceColumn": "Customer_Purchase_Order_ID",
            "summarizeBy": "none"
          },
          {
            "name": "Deliver To",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28e48603-acdd-452a-a815-6b7d4e2a12a2",
            "sourceColumn": "Deliver To",
            "summarizeBy": "none"
          },
          {
            "name": "Desired Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3132defd-730f-4e61-83ad-c2c33a934b47",
            "sourceColumn": "Desired Date",
            "summarizeBy": "none"
          },
          {
            "name": "Discount Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a289470b-c2cd-4719-8eb8-b5c2583ee9d6",
            "sourceColumn": "Discount Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Discount Percentage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6316e1b7-db5f-4afa-8519-8a8badc2fe7b",
            "sourceColumn": "Discount Percentage",
            "summarizeBy": "sum"
          },
          {
            "name": "Effective Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "769a91c2-769b-48e1-9d1c-6dcf70e635ec",
            "sourceColumn": "Effective Date",
            "summarizeBy": "none"
          },
          {
            "name": "FOB",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "afa9fba3-f6e0-48bb-bd07-68accd861123",
            "sourceColumn": "FOB",
            "summarizeBy": "none"
          },
          {
            "name": "Financial Account ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa3cdc8e-9451-450c-a891-db3937cf32a5",
            "sourceColumn": "Financial Account ID",
            "summarizeBy": "none"
          },
          {
            "name": "Gross Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9f59ca86-cb84-4a2a-8e5e-4723885d547e",
            "sourceColumn": "Gross Unit Price",
            "summarizeBy": "sum"
          },
          {
            "name": "ID of the user who last created or modified row",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4816a62-7077-4f28-a6d3-8a6f18a10b44",
            "sourceColumn": "ID of the user who last created or modified row",
            "summarizeBy": "none"
          },
          {
            "name": "Inventory Abbreviation Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29fa7875-b92f-4c1f-9972-3233b58e2142",
            "sourceColumn": "Inventory Abbreviation Code",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "657ff248-1668-4b43-964a-1e3f49becf97",
            "sourceColumn": "Invoice Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice Components",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c10011a-2e24-440e-8412-da9ffa8dd41e",
            "sourceColumn": "Invoice Components",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c1012497-ad54-4a0e-b59f-06a50b989cf7",
            "sourceColumn": "Invoice Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Issue Components",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "792c4e41-bc88-46cb-bc8e-b049cbeb3193",
            "sourceColumn": "Issue Components",
            "summarizeBy": "none"
          },
          {
            "name": "Issue Line Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57367c4b-db37-46f4-a7b3-79a8c0e99d40",
            "sourceColumn": "Issue Line Key",
            "summarizeBy": "none"
          },
          {
            "name": "Issue Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b2348dc3-0e1b-4a92-acfa-d7ea0789f13a",
            "sourceColumn": "Issue Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Item ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6682ba2b-fcb4-488d-a6b0-855420814673",
            "sourceColumn": "Item ID",
            "summarizeBy": "none"
          },
          {
            "name": "Item Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9d7cec25-0e00-40d6-bc1d-85d8d53565d8",
            "sourceColumn": "Item Key",
            "summarizeBy": "count"
          },
          {
            "name": "Item_Cost_CAD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "expression": "'Sales Orders'[Item_cost_USD]    * LOOKUPVALUE( 'Calendar'[FX Rate] , 'Calendar'[Date] , 'Sales Orders'[Ship by Date] )",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d8e2bffc-533b-4649-bcf5-8af87add1928",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Item_cost_USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "expression": "RELATED('Item'[Item Unit Cost Amount])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cd184529-c698-46da-84ec-066176c53df9",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "M/B",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba574683-06c9-435c-9ad9-2e22812514ce",
            "sourceColumn": "M/B",
            "summarizeBy": "none"
          },
          {
            "name": "Model_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bac58094-baa1-4d6e-8999-9cbc3d36d8b8",
            "sourceColumn": "Model_ID",
            "summarizeBy": "none"
          },
          {
            "name": "National_Stock_Number_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "656db74e-77a8-4a15-bce0-83cf49c488b7",
            "sourceColumn": "National_Stock_Number_ID",
            "summarizeBy": "none"
          },
          {
            "name": "Net Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "85b67420-1186-4184-a5a1-627b23445097",
            "sourceColumn": "Net Unit Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "m/d/yyyy",
            "lineageTag": "ca788c80-cd10-4605-a87d-93a1f1a90088",
            "sourceColumn": "Order Date",
            "summarizeBy": "none"
          },
          {
            "name": "Order Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7f6cd901-91c8-4dbf-b80c-3fa11d0e26ee",
            "sourceColumn": "Order Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ebefed91-da68-46c6-afdd-bfb89782e8a5",
            "sourceColumn": "Order Type",
            "summarizeBy": "none"
          },
          {
            "name": "Org ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd368bf3-f6b6-4c35-b881-a007458ce883",
            "sourceColumn": "Org ID",
            "summarizeBy": "none"
          },
          {
            "name": "Original Due Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "067db387-ce8d-4d2b-9c82-38e9aa1b1b2a",
            "sourceColumn": "Original Due Date",
            "summarizeBy": "none"
          },
          {
            "name": "Partial Shipment Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6169ed0d-0833-4077-a118-6856cbcb46b0",
            "sourceColumn": "Partial Shipment Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Payment Term",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dfb6a44a-96ad-4db2-b797-090bce13d3d3",
            "sourceColumn": "Payment Term",
            "summarizeBy": "none"
          },
          {
            "name": "Payment Term Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aa927e54-352d-40e9-ba0a-b0e55764ad1d",
            "sourceColumn": "Payment Term Key",
            "summarizeBy": "count"
          },
          {
            "name": "Posted Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "82d37664-d965-4018-bf4a-abdb64379ce7",
            "sourceColumn": "Posted Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Posted Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7236b552-2c9a-4216-8407-4203755fc5c3",
            "sourceColumn": "Posted Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Price Catalog",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e80d8bed-45bf-49a6-9ec3-7846d16a97fb",
            "sourceColumn": "Price Catalog",
            "summarizeBy": "none"
          },
          {
            "name": "Process Components",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1205bf46-eb15-4946-ba0e-a7bf6740cfa9",
            "sourceColumn": "Process Components",
            "summarizeBy": "none"
          },
          {
            "name": "Project ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ee15ed38-2032-4ec7-9a52-fe21482744ad",
            "sourceColumn": "Project ID",
            "summarizeBy": "none"
          },
          {
            "name": "Project_Price_Catalog",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "093ad07b-5b2c-4df4-879d-81ecac16fd4e",
            "sourceColumn": "Project_Price_Catalog",
            "summarizeBy": "none"
          },
          {
            "name": "Promise Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "293381d3-1e46-4ca6-8ef1-1fba1013aaa9",
            "sourceColumn": "Promise Date",
            "summarizeBy": "none"
          },
          {
            "name": "Quote ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a50eed5-3871-4fd5-b9b5-08959298e208",
            "sourceColumn": "Quote ID",
            "summarizeBy": "none"
          },
          {
            "name": "Recurring Item End Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1acf247b-c2b7-4083-895a-11ab9a5a4cbc",
            "sourceColumn": "Recurring Item End Date",
            "summarizeBy": "none"
          },
          {
            "name": "Recurring Item Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3171cf5b-13bc-454e-9146-2275b017e937",
            "sourceColumn": "Recurring Item Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "SO Line Charge Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f5be757a-84ce-4931-9567-bae10021729a",
            "sourceColumn": "SO Line Charge Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "SO Line Charge Tax Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9c6e3f86-c7fd-4c81-b819-3c818af46d8d",
            "sourceColumn": "SO Line Charge Tax Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "SO Line Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d9fb4a07-4d4c-49a9-bf6e-535cbd0dbd4d",
            "sourceColumn": "SO Line Key",
            "summarizeBy": "count"
          },
          {
            "name": "SO Line Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "71417be4-be4d-40f9-92b7-3a75b4de5c4f",
            "sourceColumn": "SO Line Status",
            "summarizeBy": "none"
          },
          {
            "name": "SO Release Nr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "51ff6631-1a65-4e41-a17a-d48170636f92",
            "sourceColumn": "SO Release Nr",
            "summarizeBy": "sum"
          },
          {
            "name": "SO-LN_Ship Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecdb2e2e-96a9-46f8-aa48-11045cc7ef4a",
            "sourceColumn": "SO-LN_Ship Key",
            "summarizeBy": "none"
          },
          {
            "name": "SO_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2dad7a5-bed7-4db5-9e73-22785fa5081d",
            "sourceColumn": "SO_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "SO_LN_KEY2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d1433a09-181b-449d-95c5-b7d065605c0e",
            "sourceColumn": "SO_LN_KEY2",
            "summarizeBy": "none"
          },
          {
            "name": "SO_Status_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bbce928d-d7b6-486c-83a5-9acf0f9ae82f",
            "sourceColumn": "SO_Status_cd",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Group Abbreviation Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "033cca84-d171-452f-bb62-f99ab49e8595",
            "sourceColumn": "Sales Group Abbreviation Code",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Group Inclusion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "IF (",
              "    CONTAINSSTRING (",
              "        'Sales Orders'[Sales Group Abbreviation Code],",
              "        \"RRC\"",
              "    )",
              "        = TRUE ()",
              "        || CONTAINSSTRING (",
              "            'Sales Orders'[Sales Group Abbreviation Code],",
              "            \"WNY\"",
              "        )",
              "            = TRUE ()",
              "        || LEFT (",
              "            'Sales Orders'[Sales Group Abbreviation Code],",
              "            3",
              "        ) = \"EXP\",",
              "    \"Exclude\",",
              "    \"Include\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "a8847c4a-e145-4bcc-bf8b-9fcc45f80ce9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Sales Order Line Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3245945f-bcb7-42dd-9b2a-a774866e4747",
            "sourceColumn": "Sales Order Line Description",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Order Line Nr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7d692aed-c242-4b18-abd0-f9c7af15fc8c",
            "sourceColumn": "Sales Order Line Nr",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales Order Line Total Amount CAD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "'Sales Orders'[Sales Order Line Total Amount USD]",
              "    * LOOKUPVALUE( 'Calendar'[FX Rate] , 'Calendar'[Date] , 'Sales Orders'[Ship by Date] )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "57487db2-2c31-4eef-8840-be68516747ac",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Sales Order Line Total Amount USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1ca79feb-0f63-4d8e-8718-5bbdc8730798",
            "sourceColumn": "Sales Order Line Total Amount USD",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales Order Line Total Ext Amount CAD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "'Sales Orders'[Sales Order Line Total Ext Amount USD]",
              "    * LOOKUPVALUE( 'Calendar'[FX Rate] , 'Calendar'[Date] , 'Sales Orders'[Ship by Date] )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "be450ad3-054c-4096-a5a1-0464075025dd",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Sales Order Line Total Ext Amount USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2117d8a8-21bb-4402-928c-a12aa5c2bc85",
            "sourceColumn": "Sales Order Line Total Ext Amount USD",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales Order Line Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "512beb1a-d586-4459-a8ad-f5a5a353c048",
            "sourceColumn": "Sales Order Line Type",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Order Notes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61683bc6-c402-410e-9777-e5f789fba000",
            "sourceColumn": "Sales Order Notes",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Order Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "162bd2f2-42d2-4de5-96b1-6fc9f0b42c37",
            "sourceColumn": "Sales Order Number",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Order Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9551bc2e-40ab-435c-8ad9-ccf8dd50401b",
            "sourceColumn": "Sales Order Status",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Rep ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8896e2f-5384-49d3-b6c9-79f276104edb",
            "sourceColumn": "Sales Rep ID",
            "summarizeBy": "none"
          },
          {
            "name": "Ship Via",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0555abe0-154c-4de9-ba7f-dc6aeaea940a",
            "sourceColumn": "Ship Via",
            "summarizeBy": "none"
          },
          {
            "name": "Ship by Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "13773eeb-d9ba-4471-aa1a-385d904c2ffd",
            "sourceColumn": "Ship by Date",
            "summarizeBy": "none"
          },
          {
            "name": "Shipment ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b1c880c5-8b15-44d4-8e84-2d25ecfd934c",
            "sourceColumn": "Shipment ID",
            "summarizeBy": "none"
          },
          {
            "name": "Shipment Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "eede6061-6737-4f58-a0a7-a8eaee04f6db",
            "sourceColumn": "Shipment Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Shipment Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8b4b5fd-a18b-4dca-88cd-659655fde3dc",
            "sourceColumn": "Shipment Status",
            "summarizeBy": "none"
          },
          {
            "name": "Tax/VAT Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "57570893-6a8c-4f10-a677-90e1a86a8254",
            "sourceColumn": "Tax/VAT Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Tax/VAT Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "86e507cb-6e6d-44d0-aa3c-248f7eba0cf8",
            "sourceColumn": "Tax/VAT Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "Taxable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "158bcc1a-f0bc-4c27-a0dd-4c2ffdcbd72f",
            "sourceColumn": "Taxable",
            "summarizeBy": "none"
          },
          {
            "name": "Unit of Measure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8444d2e-8c50-4b44-8ae6-9ee09813c22f",
            "sourceColumn": "Unit of Measure",
            "summarizeBy": "none"
          },
          {
            "name": "Value Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9c0d6196-9b5b-4c98-95d6-8b1b8ede05e4",
            "sourceColumn": "Value Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Warehouse ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92406913-1813-4bff-9ead-f0150f0c1720",
            "sourceColumn": "Warehouse ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0f4215fa-7635-4de0-a6e0-54380e261a1c",
        "partitions": [
          {
            "name": "Sales Orders-195ae52a-dd51-44ff-8952-50b9bc13dfc0",
            "mode": "import",
            "queryGroup": "Deltek",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    deltek_SalesOrders = Source{[Schema=\"deltek\",Item=\"SalesOrders\"]}[Data]",
                "in",
                "    deltek_SalesOrders"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales Rep",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "SR_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f6d6129b-f540-435a-ab0e-5548d32933ed",
            "sourceColumn": "SR_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Rep ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d7d48a0-d73e-43e0-ac81-8597fc1a29e9",
            "sourceColumn": "Sales Rep ID",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Representative",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14df39e4-5bd3-4a83-a58d-5858debd3f4e",
            "sourceColumn": "Sales Representative",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Territory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "006c15b1-3158-4747-86fb-5d8c883a7877",
            "sourceColumn": "Sales Territory",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c9bc5fa5-e232-4789-9b53-1a675fb20333",
        "partitions": [
          {
            "name": "Sales Rep-7b03971b-279c-4223-b47f-629b84435999",
            "mode": "import",
            "queryGroup": "Deltek",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    deltek_Sales_Representative = Source{[Schema=\"deltek\",Item=\"Sales_Representative\"]}[Data]",
                "in",
                "    deltek_Sales_Representative"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Scheduled Receipt",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "BOM Configuration ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d78f9f18-e176-44f9-99fa-9b226552e196",
            "sourceColumn": "BOM Configuration ID",
            "summarizeBy": "none"
          },
          {
            "name": "Buyer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecbcd4f0-2a1d-4dfc-9957-34aec9c5193a",
            "sourceColumn": "Buyer ID",
            "summarizeBy": "none"
          },
          {
            "name": "Commodity Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1315e5c3-89d5-4c5d-b388-df69292219ce",
            "sourceColumn": "Commodity Code",
            "summarizeBy": "none"
          },
          {
            "name": "Common Stock Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41bc5c6a-6a7a-4343-adf7-dacfa743f549",
            "sourceColumn": "Common Stock Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Company ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6cd41a66-c744-4676-a113-b2f6aa15b4f5",
            "sourceColumn": "Company ID",
            "summarizeBy": "none"
          },
          {
            "name": "Due Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f2bf7d86-a82a-40ff-98ba-65b279de0b20",
            "sourceColumn": "Due Date",
            "summarizeBy": "none"
          },
          {
            "name": "Effective Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1371a190-0ebe-4976-b09b-0dd89f5210f8",
            "sourceColumn": "Effective Date",
            "summarizeBy": "none"
          },
          {
            "name": "Entry Date Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "61e1a038-b1cf-4155-825f-5b989b271dfc",
            "sourceColumn": "Entry Date Time",
            "summarizeBy": "none"
          },
          {
            "name": "Estimated Cost Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e4f19eb6-e882-4611-8acf-18e01fb96b75",
            "sourceColumn": "Estimated Cost Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Inventory Abbreviation Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "652ac24c-c50f-46f1-9448-e9b2d51e2303",
            "sourceColumn": "Inventory Abbreviation Code",
            "summarizeBy": "none"
          },
          {
            "name": "Inventory Abbreviation Code From",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70a07991-ace3-4c47-b40f-e025d359942b",
            "sourceColumn": "Inventory Abbreviation Code From",
            "summarizeBy": "none"
          },
          {
            "name": "Inventory Project",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b479b1bf-57d1-42f2-a346-8b313ada1d0e",
            "sourceColumn": "Inventory Project",
            "summarizeBy": "none"
          },
          {
            "name": "MO Planned In Shop Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c58e9b66-0b49-4f98-ae32-3d5f6687d64f",
            "sourceColumn": "MO Planned In Shop Date",
            "summarizeBy": "none"
          },
          {
            "name": "MPS Plan Source Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "506f4308-b5cc-47a0-b70c-75cbbf8ece0a",
            "sourceColumn": "MPS Plan Source Code",
            "summarizeBy": "none"
          },
          {
            "name": "Open Order Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8ab2a9f6-b874-4f32-b23d-c306507bb81d",
            "sourceColumn": "Open Order Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d5180c12-6068-41f7-b711-515efbf0c3e1",
            "sourceColumn": "Order Date",
            "summarizeBy": "none"
          },
          {
            "name": "Order Line Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "05076600-8a1e-41be-8490-75209d3d6dfc",
            "sourceColumn": "Order Line Key",
            "summarizeBy": "count"
          },
          {
            "name": "Order Line Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3d625c1d-0052-4d03-9cb6-31eee94032f4",
            "sourceColumn": "Order Line Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Reference",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "366bf4c3-8b53-4915-ab72-dddaa7763eeb",
            "sourceColumn": "Order Reference",
            "summarizeBy": "none"
          },
          {
            "name": "Order Reference ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85dc46ed-175a-4ad6-9f1b-cc14fe8c948e",
            "sourceColumn": "Order Reference ID",
            "summarizeBy": "none"
          },
          {
            "name": "Order Reference Release Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e07302d4-38f6-4e70-bf2e-2f058bbd8e99",
            "sourceColumn": "Order Reference Release Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Reference Type Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b096926-505b-440d-971f-48ebc93002f3",
            "sourceColumn": "Order Reference Type Code",
            "summarizeBy": "none"
          },
          {
            "name": "Order Release Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c63003cc-9b6e-4af8-9549-9bfdf7f6ad68",
            "sourceColumn": "Order Release Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Type Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "074592e2-3865-4562-b0b5-fd373cfbef69",
            "sourceColumn": "Order Type Code",
            "summarizeBy": "none"
          },
          {
            "name": "Original Order Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d9ca59c2-f631-41dc-82ba-b5d86337ef62",
            "sourceColumn": "Original Order Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Outbound Inventory Project",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d06ae943-0742-4089-9bee-15a4f85b6984",
            "sourceColumn": "Outbound Inventory Project",
            "summarizeBy": "none"
          },
          {
            "name": "Part ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95aef78d-3bdc-4835-adf3-3829d85526c7",
            "sourceColumn": "Part ID",
            "summarizeBy": "none"
          },
          {
            "name": "Planned Inventory Available Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c0adad3b-c7f3-47f7-856b-38621db295e6",
            "sourceColumn": "Planned Inventory Available Date",
            "summarizeBy": "none"
          },
          {
            "name": "Planned Order Last Change Timestamp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "53f951a4-2410-417e-b0dd-4dd40d7f1ad4",
            "sourceColumn": "Planned Order Last Change Timestamp",
            "summarizeBy": "none"
          },
          {
            "name": "Planned Order Last Change User ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61719993-fdc5-454d-999a-e3153eefad00",
            "sourceColumn": "Planned Order Last Change User ID",
            "summarizeBy": "none"
          },
          {
            "name": "Planner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9320009d-9374-41f0-9067-f881baead1cd",
            "sourceColumn": "Planner",
            "summarizeBy": "none"
          },
          {
            "name": "Planning Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7859443c-4559-45aa-b3f5-3aa5fe3d5ac6",
            "sourceColumn": "Planning Type",
            "summarizeBy": "none"
          },
          {
            "name": "Project Planning Group ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "03faa009-f6cd-422a-ab0c-bee34ce84a53",
            "sourceColumn": "Project Planning Group ID",
            "summarizeBy": "none"
          },
          {
            "name": "Reservation Warehouse ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af00d7b7-3415-4254-b34a-02dc61d84c83",
            "sourceColumn": "Reservation Warehouse ID",
            "summarizeBy": "none"
          },
          {
            "name": "Scheduled Receipt Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d172eb85-d869-4bee-9aa0-ba073ad710ec",
            "sourceColumn": "Scheduled Receipt Key",
            "summarizeBy": "count"
          },
          {
            "name": "Scheduled Receipt Type Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "006c5254-cbfc-467b-9e41-a07b6a5a187a",
            "sourceColumn": "Scheduled Receipt Type Code",
            "summarizeBy": "none"
          },
          {
            "name": "Shipping ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57b55b21-7c96-4c26-a7ad-76fd6b22933f",
            "sourceColumn": "Shipping ID",
            "summarizeBy": "none"
          },
          {
            "name": "Status Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "24297c75-8b66-4e4a-ac2c-27147f354769",
            "sourceColumn": "Status Code",
            "summarizeBy": "none"
          },
          {
            "name": "Supervisor ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a7d6310-dd00-4b9d-9bf2-cadd1378efcf",
            "sourceColumn": "Supervisor ID",
            "summarizeBy": "none"
          },
          {
            "name": "Target Release Place Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5c291387-a89c-45a0-9a79-06a27881a57e",
            "sourceColumn": "Target Release Place Date",
            "summarizeBy": "none"
          },
          {
            "name": "Transfer Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d022efb-77be-465d-98cd-eee8870664fe",
            "sourceColumn": "Transfer Type",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Cost Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3cd9b415-67e8-4510-a6b1-0213d5214693",
            "sourceColumn": "Unit Cost Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Vendor ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a8a462c-7548-46ff-bf32-708f1b784861",
            "sourceColumn": "Vendor ID",
            "summarizeBy": "none"
          },
          {
            "name": "Warehouse ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17475d13-3973-4b00-9623-b91ac498228e",
            "sourceColumn": "Warehouse ID",
            "summarizeBy": "none"
          },
          {
            "name": "Yield Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6bb2cb31-b6fb-4725-8164-be2164f29106",
            "sourceColumn": "Yield Quantity",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "a67ff666-9952-4e16-8c0c-14d7336ef24e",
        "partitions": [
          {
            "name": "Scheduled Receipt-66701da2-7986-4804-bc15-29f6d7af2709",
            "mode": "import",
            "queryGroup": "Deltek",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    deltek_Scheduled_Receipt = Source{[Schema=\"deltek\",Item=\"Scheduled_Receipt\"]}[Data]",
                "in",
                "    deltek_Scheduled_Receipt"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Ship Trn",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "Bill of Lading ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "645e6db2-d5c9-460d-9547-324abc2dbdc4",
            "sourceColumn": "Bill of Lading ID",
            "summarizeBy": "none"
          },
          {
            "name": "Confirmed Delivery Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9d118c77-5d75-4055-ab6d-e2908206a23c",
            "sourceColumn": "Confirmed Delivery Date",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14688378-99c2-4006-97c7-651370f5992a",
            "sourceColumn": "Customer Key",
            "summarizeBy": "none"
          },
          {
            "name": "Estimated Delivery Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "50fa2187-903b-4a76-9f00-d105e628e81d",
            "sourceColumn": "Estimated Delivery Date",
            "summarizeBy": "none"
          },
          {
            "name": "Expanded Shipment Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "19edbc7a-5ad7-4b39-aec9-6caa0897e5b1",
            "sortByColumn": "Expanded Shipment Status Order",
            "sourceColumn": "Expanded Shipment Status",
            "summarizeBy": "none"
          },
          {
            "name": "Expanded Shipment Status Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "88e714ec-ae44-4aba-9f10-648739022f60",
            "sourceColumn": "Expanded Shipment Status Order",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2476e006-1790-496c-9a9b-afabad451a51",
            "sourceColumn": "Invoice Key",
            "summarizeBy": "none"
          },
          {
            "name": "Issue Composite Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42925ddd-bd48-4409-96f5-e804810ef341",
            "sourceColumn": "Issue Composite Key",
            "summarizeBy": "none"
          },
          {
            "name": "Issue Item ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ede7b749-5e9e-4c27-8572-899c0b754aaf",
            "sourceColumn": "Issue Item ID",
            "summarizeBy": "none"
          },
          {
            "name": "Issue Item Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a21741a7-dfe7-4457-87dc-bf12f53e1610",
            "sourceColumn": "Issue Item Key",
            "summarizeBy": "none"
          },
          {
            "name": "Issue Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c6207f61-cbef-475b-94d4-3442e80daf76",
            "sourceColumn": "Issue Key",
            "summarizeBy": "count"
          },
          {
            "name": "Issue Line Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce02617a-38d9-4ae9-be1a-e5cd954d7332",
            "sourceColumn": "Issue Line Key",
            "summarizeBy": "none"
          },
          {
            "name": "Issue Shipment Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "0.00",
            "lineageTag": "4d7617a6-c80c-4db8-bfd1-c0e0fcfcf9a7",
            "sourceColumn": "Issue Shipment Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Issued Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0",
            "lineageTag": "94ebdc00-72e5-4421-b2b8-2ed56c62b6bb",
            "sourceColumn": "Issued Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Item Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "306d4c82-ae96-4f4b-9599-a422b2e26ce8",
            "sourceColumn": "Item Key",
            "summarizeBy": "count"
          },
          {
            "name": "Kit Item ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04a27c0c-90bf-4971-8d6c-e3b6dd885360",
            "sourceColumn": "Kit Item ID",
            "summarizeBy": "none"
          },
          {
            "name": "Kit Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c3ba3b83-f2aa-455f-91e8-c33a522e28af",
            "sourceColumn": "Kit Unit Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Net Shipment Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF('Ship Trn'[Issued Quantity]>=0,\"Net Shipments\",\"Credits\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "db59ac68-89ca-4857-b6aa-ed48a3cce03c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "On Time Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "",
              "VAR ResultUSD =",
              "",
              "CALCULATE(",
              "    ",
              "    SUMX ( 'Ship Trn', ",
              "        IF( RELATED('Sales Orders'[Issue Components]) = \"Y\" && RELATED('Sales Orders'[Invoice Components]) = \"Y\" , DIVIDE(RELATED('Sales Orders'[Sales Order Line Total Ext Amount USD]) , CALCULATE(COUNTROWS('Ship Trn'),ALLEXCEPT('Ship Trn','Ship Trn'[SO-LN_Ship Key])))",
              "        ,IF( RELATED('Sales Orders'[Issue Components]) = \"Y\" && CALCULATE(SUM('Ship Trn'[Issue Shipment Quantity]),ALLEXCEPT('Ship Trn','Ship Trn'[SO-LN_Ship Key])) > RELATED('Sales Orders'[Order Quantity]) , DIVIDE(RELATED('Sales Orders'[Sales Order Line Total Ext Amount USD]) , CALCULATE(COUNTROWS('Ship Trn'),ALLEXCEPT('Ship Trn','Ship Trn'[SO-LN_Ship Key])))",
              "        ,RELATED('Sales Orders'[Sales Order Line Total Ext Amount USD]) / RELATED('Sales Orders'[Order Quantity]) * 'Ship Trn'[Issue Shipment Quantity] )))",
              "",
              "    ,FILTER('Ship Trn',RELATED('Sales Orders'[Sales Group Inclusion]) = \"Include\"",
              "    --&&'Sales Orders'[Sales Order Line Type] = \"INV\"",
              "    &&RELATED('Sales Orders'[Net Unit Price])>0",
              "    &&'Ship Trn'[Shipment Status]=\"Shipped\"",
              "    )",
              ")",
              "",
              "RETURN",
              "",
              "IF(ResultUSD>0&&NOT(ISBLANK('Ship Trn'[Shipment Date]))&&RELATED('Sales Orders'[Net Unit Price])>0&&'Ship Trn'[Shipment Status]=\"Shipped\",IF('Ship Trn'[Shipment Date]<RELATED('Sales Orders'[Promise Date])+1,\"Y\",\"N\"),\"\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "9d53e960-6e9b-41e7-a06a-ea0118eb7ad5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Open Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5cb398d5-072a-4e93-b57f-01ef15edd1f2",
            "sourceColumn": "Open Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "PS_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b3a96f7-a1d1-49a1-a22e-dcb93008102d",
            "sourceColumn": "PS_ID",
            "summarizeBy": "none"
          },
          {
            "name": "Partial Shipment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(CALCULATE(SUM('Ship Trn'[Issued Quantity]),ALLEXCEPT('Ship Trn','Sales Orders'[SO-LN_Ship Key]))<RELATED('Sales Orders'[Order Quantity]),\"Partial Shipment\")",
            "isDataTypeInferred": true,
            "lineageTag": "a741fd69-f730-4924-84d6-d115b34fb00f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "67d21506-47ab-496b-8044-791a33fc959a",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Related Inclusion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "RELATED('Sales Orders'[Sales Group Inclusion])",
            "isDataTypeInferred": true,
            "lineageTag": "6fa523b0-f7c4-4df3-94fd-06bc9648bb52",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "SO Line Nr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e0102efa-9bab-4ccd-8cfa-bae19ca84942",
            "sourceColumn": "SO Line Nr",
            "summarizeBy": "sum"
          },
          {
            "name": "SO-LN Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ce1cfcb-c1b1-49d8-ad66-94232ab344d4",
            "sourceColumn": "SO-LN Key",
            "summarizeBy": "none"
          },
          {
            "name": "SO-LN-Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bbab9cd1-d3e4-465d-bb17-6724c380d2ce",
            "sourceColumn": "SO-LN-Key",
            "summarizeBy": "none"
          },
          {
            "name": "SO-LN_Ship Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6dc2e9f-e734-4cc0-9c69-6ab804b51d77",
            "sourceColumn": "SO-LN_Ship Key",
            "summarizeBy": "none"
          },
          {
            "name": "SO_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "59759e01-6ca7-40a1-912c-c73b17627c3a",
            "sourceColumn": "SO_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Order Line Component Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a707d8c4-0663-454e-a9b4-9c2c55ca784f",
            "sourceColumn": "Sales Order Line Component Key",
            "summarizeBy": "count"
          },
          {
            "name": "Sales Order Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d016d456-6787-428c-962e-44e843d255cd",
            "sourceColumn": "Sales Order Number",
            "summarizeBy": "none"
          },
          {
            "name": "Ship Via",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95bcc9a2-51f8-4c2a-983b-1619844f5800",
            "sourceColumn": "Ship Via",
            "summarizeBy": "none"
          },
          {
            "name": "Shipment / Ship By Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "c46235c4-0102-489e-895c-aea668d8a090",
            "sourceColumn": "Shipment / Ship By Date",
            "summarizeBy": "none"
          },
          {
            "name": "Shipment Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "m/d/yyyy",
            "lineageTag": "34e0c79a-e3a2-4e37-93ac-d9e689e22de3",
            "sourceColumn": "Shipment Date",
            "summarizeBy": "none"
          },
          {
            "name": "Shipment ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4696b877-2115-4fbf-a161-d6155f083b8e",
            "sourceColumn": "Shipment ID",
            "summarizeBy": "none"
          },
          {
            "name": "Shipment Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf798c47-fc24-4761-80fd-1e6af6f4e328",
            "sortByColumn": "Shipment Status Order",
            "sourceColumn": "Shipment Status",
            "summarizeBy": "none"
          },
          {
            "name": "Shipment Status Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b727fde0-b577-4b81-9b1c-dd1bf883a46c",
            "sourceColumn": "Shipment Status Order",
            "summarizeBy": "sum"
          },
          {
            "name": "Spreaded Extended Amount CAD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "'Ship Trn'[Spreaded Extended Amount USD] * CALCULATE(MAX('Calendar'[FX Rate]),FILTER('Calendar','Calendar'[Date]='Ship Trn'[Shipment / Ship By Date]))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "4543f4b4-a9e6-403b-a8af-eef30985bb8e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Spreaded Extended Amount USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "50a1bb21-6584-49c5-a911-0a08d602d31e",
            "sourceColumn": "Spreaded Extended Amount USD",
            "summarizeBy": "none"
          },
          {
            "name": "Transaction Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "6237c777-27a3-4336-9605-e884ffd8b0df",
            "sourceColumn": "Transaction Date",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Cost Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d3c2b76a-bb44-4c3c-8ff4-d2b85df29b88",
            "sourceColumn": "Unit Cost Amount",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "c3631eaf-90c8-419b-8488-62688ea1c7e8",
        "partitions": [
          {
            "name": "Ship Trn-ee1452a5-b0ae-495c-898a-a700a47ada85",
            "mode": "import",
            "queryGroup": "Deltek",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    deltek_Shipment_Transactions_Expanded = Source{[Schema=\"deltek\",Item=\"Shipment_Transactions_Expanded\"]}[Data]",
                "in",
                "    deltek_Shipment_Transactions_Expanded"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Shipment Inventory Transactions",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "Charge Project Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a214369c-e0fa-47af-9f77-c4575d048119",
            "sourceColumn": "Charge Project Number",
            "summarizeBy": "none"
          },
          {
            "name": "Inventory Transaction Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83c85a0f-82a5-4d0e-8139-db50dec78808",
            "sourceColumn": "Inventory Transaction Description",
            "summarizeBy": "none"
          },
          {
            "name": "Inventory Transaction Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "06184b66-d201-4d74-bb53-8e0de7e82f47",
            "sourceColumn": "Inventory Transaction Number",
            "summarizeBy": "none"
          },
          {
            "name": "Inventory Transaction Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97a765bc-4424-48ff-908c-57aa1da4ecaf",
            "sourceColumn": "Inventory Transaction Type",
            "summarizeBy": "none"
          },
          {
            "name": "Labor Cost Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cc8cc505-6805-4d26-bd39-83fbc209ba02",
            "sourceColumn": "Labor Cost Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Material Burden Cost Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8dc009be-33eb-442d-aa12-2324d142c85b",
            "sourceColumn": "Material Burden Cost Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Material Cost Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5be2383e-f74a-40b7-a5a8-5663970ec383",
            "sourceColumn": "Material Cost Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "PO, MO or SO ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "843b174f-5bc2-414b-a6c2-3cdf476cc75b",
            "sourceColumn": "PO, MO or SO ID",
            "summarizeBy": "none"
          },
          {
            "name": "Part ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a9b4545-5e4e-4ed8-8bca-8dcb564b299a",
            "sourceColumn": "Part ID",
            "summarizeBy": "none"
          },
          {
            "name": "Serial Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3f3d4c0-72a9-4e3d-9c0f-1e774b625ed2",
            "sourceColumn": "Serial Number",
            "summarizeBy": "none"
          },
          {
            "name": "Transaction Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "c92546ac-c9fb-46fb-aa64-98a3a36f3043",
            "sourceColumn": "Transaction Date",
            "summarizeBy": "none"
          },
          {
            "name": "Transaction Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "65bfdb6d-1efa-4af4-bb7f-186617c678b6",
            "sourceColumn": "Transaction Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Transaction Used Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2d83c34e-ed38-4f00-87aa-573c77ab13d2",
            "sourceColumn": "Transaction Used Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Unit Cost Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "533e5998-138e-46d7-a2e5-4a3e3b72b808",
            "sourceColumn": "Unit Cost Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Warehouse ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "604f6b21-4111-4dde-9a2d-111f29facd6f",
            "sourceColumn": "Warehouse ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ebd787ce-71fb-4aa8-b202-038cbf35a6b9",
        "partitions": [
          {
            "name": "Shipment Inventory Transactions-2902b667-3c08-4483-a01c-7de28ae11758",
            "mode": "import",
            "queryGroup": "Deltek",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    deltek_Shipment_Inventory_Transactions = Source{[Schema=\"deltek\",Item=\"Shipment_Inventory_Transactions\"]}[Data]",
                "in",
                "    deltek_Shipment_Inventory_Transactions"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Shipment Targets",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Daily Shipment Forecast CAD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "82ac76f0-84b0-454b-8c77-b25c42eceb77",
            "sourceColumn": "Daily Shipment Forecast CAD",
            "summarizeBy": "sum"
          },
          {
            "name": "Daily Shipment Forecast USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "60865020-8ca8-4b77-8baa-619da2d4a189",
            "sourceColumn": "Daily Shipment Forecast USD",
            "summarizeBy": "sum"
          },
          {
            "name": "Daily Shipment Min Target CAD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "5728c5ca-7905-4091-ad3a-786e9e0c1dd9",
            "sourceColumn": "Daily Shipment Min Target CAD",
            "summarizeBy": "sum"
          },
          {
            "name": "Daily Shipment Min Target USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "f331b09d-cfd7-40e1-b044-69eeb2515a10",
            "sourceColumn": "Daily Shipment Min Target USD",
            "summarizeBy": "sum"
          },
          {
            "name": "Daily Shipment Target CAD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "1bfbeb16-b563-4bda-938d-1bc619e4b797",
            "sourceColumn": "Daily Shipment Target CAD",
            "summarizeBy": "sum"
          },
          {
            "name": "Daily Shipment Target USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "1b43d3d5-27fb-4df3-9d7b-358f69325018",
            "sourceColumn": "Daily Shipment Target USD",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3121448b-96dd-4094-8e8b-92b102a481f3",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Exchange Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3e5515da-daa3-46e7-9d65-b263869cc468",
            "sourceColumn": "Exchange Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Year-Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b902ffdd-97b1-45bc-a4e8-2802d63dfeee",
            "sourceColumn": "Fiscal Year-Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Shipment Forecast CAD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "051b3ab7-8470-40c5-9055-e9a68dc519ff",
            "sourceColumn": "Shipment Forecast CAD",
            "summarizeBy": "sum"
          },
          {
            "name": "Shipment Forecast USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f0a51362-1a4b-4462-950a-7bf7cfb29fe4",
            "sourceColumn": "Shipment Forecast USD",
            "summarizeBy": "sum"
          },
          {
            "name": "Shipment Min Target CAD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "d50f151c-76c5-4e52-b865-e6655dfc6c4a",
            "sourceColumn": "Shipment Min Target CAD",
            "summarizeBy": "sum"
          },
          {
            "name": "Shipment Min Target USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "ada14228-fe62-4317-b7b1-fa5a04fa8000",
            "sourceColumn": "Shipment Min Target USD",
            "summarizeBy": "sum"
          },
          {
            "name": "Shipment Target CAD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "25bafac7-ba48-4078-b6e8-e7f54f4f9dea",
            "sourceColumn": "Shipment Target CAD",
            "summarizeBy": "sum"
          },
          {
            "name": "Shipment Target USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ab53e274-3faf-48a6-844d-50189f9d3991",
            "sourceColumn": "Shipment Target USD",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "1d181bb1-fd46-4e05-8b22-0fd977143e5f",
        "partitions": [
          {
            "name": "Shipment Targets-dc519edd-e7d5-4cd0-90f2-f9146e612453",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    sharepoint_ShipmentTargets = Source{[Schema=\"sharepoint\",Item=\"ShipmentTargets\"]}[Data]",
                "in",
                "    sharepoint_ShipmentTargets"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Supply - Demand Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "description": "This section contains Sales Order related measures",
        "lineageTag": "d4b9bbef-9475-405b-abc4-3687915e5e6b",
        "measures": [
          {
            "name": "Item Avg Price",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "var levelcode = ",
              "SWITCH(",
              "    TRUE()",
              "    ,ISINSCOPE('Product Hierarchy'[Level 7]),SELECTEDVALUE('Product Hierarchy'[Level 7])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 6]),SELECTEDVALUE('Product Hierarchy'[Level 6])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 5]),SELECTEDVALUE('Product Hierarchy'[Level 5])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 4]),SELECTEDVALUE('Product Hierarchy'[Level 4])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 3]),SELECTEDVALUE('Product Hierarchy'[Level 3])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 2]),SELECTEDVALUE('Product Hierarchy'[Level 2])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 1]),SELECTEDVALUE('Product Hierarchy'[Level 1])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 0]),SELECTEDVALUE('Product Hierarchy'[Level 0])",
              "    --,ISINSCOPE('Product Hierarchy'[Level 8]),SELECTEDVALUE('Product Hierarchy'[Level 8])",
              "    ,SELECTEDVALUE('Product Hierarchy'[Level 8])",
              ")",
              "",
              "var result =",
              "CALCULATE(",
              "    AVERAGE('Item'[Item Average Price])",
              "    ,FILTER('Item','Item'[Item ID]=levelcode)",
              ")",
              "",
              "RETURN",
              "",
              "result"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "4e2ab1b1-a352-47b8-9469-d3cf131ee78d"
          },
          {
            "name": "MPS Qty",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "var level0 =",
              "CALCULATE(",
              "    SUM('MPS Forecast'[Open Sales Forecast Quantity])",
              "    ,FILTER('MPS Forecast','MPS Forecast'[Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 0]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])*MAX('Product Hierarchy'[Qty L3])*MAX('Product Hierarchy'[Qty L2])*MAX('Product Hierarchy'[Qty L1])",
              "",
              "var level1 =",
              "CALCULATE(",
              "    SUM('MPS Forecast'[Open Sales Forecast Quantity])",
              "    ,FILTER('MPS Forecast','MPS Forecast'[Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 1]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])*MAX('Product Hierarchy'[Qty L3])*MAX('Product Hierarchy'[Qty L2])",
              "",
              "var level2 =",
              "CALCULATE(",
              "    SUM('MPS Forecast'[Open Sales Forecast Quantity])",
              "    ,FILTER('MPS Forecast','MPS Forecast'[Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 2]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])*MAX('Product Hierarchy'[Qty L3])",
              "",
              "var level3 =",
              "CALCULATE(",
              "    SUM('MPS Forecast'[Open Sales Forecast Quantity])",
              "    ,FILTER('MPS Forecast','MPS Forecast'[Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 3]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])",
              "",
              "var level4 =",
              "CALCULATE(",
              "    SUM('MPS Forecast'[Open Sales Forecast Quantity])",
              "    ,FILTER('MPS Forecast','MPS Forecast'[Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 4]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])",
              "",
              "var level5 =",
              "CALCULATE(",
              "    SUM('MPS Forecast'[Open Sales Forecast Quantity])",
              "    ,FILTER('MPS Forecast','MPS Forecast'[Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 5]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])",
              "",
              "var level6 =",
              "CALCULATE(",
              "    SUM('MPS Forecast'[Open Sales Forecast Quantity])",
              "    ,FILTER('MPS Forecast','MPS Forecast'[Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 6]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])",
              "",
              "var level7 =",
              "CALCULATE(",
              "    SUM('MPS Forecast'[Open Sales Forecast Quantity])",
              "    ,FILTER('MPS Forecast','MPS Forecast'[Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 7]))",
              ")*MAX('Product Hierarchy'[Qty L8])",
              "",
              "var level8 =",
              "CALCULATE(",
              "    SUM('MPS Forecast'[Open Sales Forecast Quantity])",
              "    ,FILTER('MPS Forecast','MPS Forecast'[Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 8]))",
              ")",
              "",
              "RETURN",
              "",
              "SWITCH(",
              "    TRUE()",
              "    ,ISINSCOPE('Product Hierarchy'[Level 7]),level7",
              "    ,ISINSCOPE('Product Hierarchy'[Level 6]),level6",
              "    ,ISINSCOPE('Product Hierarchy'[Level 5]),level5",
              "    ,ISINSCOPE('Product Hierarchy'[Level 4]),level4",
              "    ,ISINSCOPE('Product Hierarchy'[Level 3]),level3",
              "    ,ISINSCOPE('Product Hierarchy'[Level 4]),level2",
              "    ,ISINSCOPE('Product Hierarchy'[Level 1]),level1",
              "    ,ISINSCOPE('Product Hierarchy'[Level 0]),level0",
              "    --,ISINSCOPE('Product Hierarchy'[Level 8]),SELECTEDVALUE('Product Hierarchy'[Level 8])",
              "    ,level8",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "7b6abf25-2426-4af1-90a3-a3efb179a7ca"
          },
          {
            "name": "Cumulative Qty",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "var cumqtyL0 =",
              "SUMX(",
              "    'Product Hierarchy'",
              "    ,'Product Hierarchy'[Qty L1]*'Product Hierarchy'[Qty L2]*'Product Hierarchy'[Qty L3]*'Product Hierarchy'[Qty L4]*'Product Hierarchy'[Qty L5]*'Product Hierarchy'[Qty L6]*'Product Hierarchy'[Qty L7]*'Product Hierarchy'[Qty L8])",
              "",
              "var cumqtyL1 =",
              "SUMX(",
              "    'Product Hierarchy'",
              "    ,'Product Hierarchy'[Qty L2]*'Product Hierarchy'[Qty L3]*'Product Hierarchy'[Qty L4]*'Product Hierarchy'[Qty L5]*'Product Hierarchy'[Qty L6]*'Product Hierarchy'[Qty L7]*'Product Hierarchy'[Qty L8])",
              "",
              "var cumqtyL2 =",
              "SUMX(",
              "    'Product Hierarchy'",
              "    ,'Product Hierarchy'[Qty L3]*'Product Hierarchy'[Qty L4]*'Product Hierarchy'[Qty L5]*'Product Hierarchy'[Qty L6]*'Product Hierarchy'[Qty L7]*'Product Hierarchy'[Qty L8])",
              "",
              "var cumqtyL3 =",
              "SUMX(",
              "    'Product Hierarchy'",
              "    ,'Product Hierarchy'[Qty L4]*'Product Hierarchy'[Qty L5]*'Product Hierarchy'[Qty L6]*'Product Hierarchy'[Qty L7]*'Product Hierarchy'[Qty L8])",
              "",
              "var cumqtyL4 =",
              "SUMX(",
              "    'Product Hierarchy'",
              "    ,'Product Hierarchy'[Qty L5]*'Product Hierarchy'[Qty L6]*'Product Hierarchy'[Qty L7]*'Product Hierarchy'[Qty L8])",
              "",
              "var cumqtyL5 =",
              "SUMX(",
              "    'Product Hierarchy'",
              "    ,'Product Hierarchy'[Qty L6]*'Product Hierarchy'[Qty L7]*'Product Hierarchy'[Qty L8])",
              "",
              "var cumqtyL6 =",
              "SUMX(",
              "    'Product Hierarchy'",
              "    ,'Product Hierarchy'[Qty L7]*'Product Hierarchy'[Qty L8])",
              "",
              "var cumqtyL7 =",
              "SUMX(",
              "    'Product Hierarchy'",
              "    ,'Product Hierarchy'[Qty L8])",
              "",
              "RETURN",
              "",
              "SWITCH(",
              "    TRUE()",
              "    ,ISINSCOPE('Product Hierarchy'[Level 7]),cumqtyL7",
              "    ,ISINSCOPE('Product Hierarchy'[Level 6]),cumqtyL6",
              "    ,ISINSCOPE('Product Hierarchy'[Level 5]),cumqtyL5",
              "    ,ISINSCOPE('Product Hierarchy'[Level 4]),cumqtyL4",
              "    ,ISINSCOPE('Product Hierarchy'[Level 3]),cumqtyL3",
              "    ,ISINSCOPE('Product Hierarchy'[Level 4]),cumqtyL2",
              "    ,ISINSCOPE('Product Hierarchy'[Level 1]),cumqtyL1",
              "    ,ISINSCOPE('Product Hierarchy'[Level 0]),cumqtyL0",
              "    --,ISINSCOPE('Product Hierarchy'[Level 8]),SELECTEDVALUE('Product Hierarchy'[Level 8])",
              "    ,1",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "335753a2-dfb7-4a25-9f6a-7f4d17a97b93"
          },
          {
            "name": "On-Hand Qty",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "var level0 =",
              "CALCULATE(",
              "    SUM(Inventory[On Hand Quantity])",
              "    ,FILTER('Inventory','Inventory'[Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 0]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])*MAX('Product Hierarchy'[Qty L3])*MAX('Product Hierarchy'[Qty L2])*MAX('Product Hierarchy'[Qty L1])",
              "",
              "var level1 =",
              "CALCULATE(",
              "    SUM(Inventory[On Hand Quantity])",
              "    ,FILTER('Inventory','Inventory'[Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 1]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])*MAX('Product Hierarchy'[Qty L3])*MAX('Product Hierarchy'[Qty L2])",
              "",
              "var level2 =",
              "CALCULATE(",
              "    SUM(Inventory[On Hand Quantity])",
              "    ,FILTER('Inventory','Inventory'[Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 2]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])*MAX('Product Hierarchy'[Qty L3])",
              "",
              "var level3 =",
              "CALCULATE(",
              "    SUM(Inventory[On Hand Quantity])",
              "    ,FILTER('Inventory','Inventory'[Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 3]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])",
              "",
              "var level4 =",
              "CALCULATE(",
              "    SUM(Inventory[On Hand Quantity])",
              "    ,FILTER('Inventory','Inventory'[Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 4]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])",
              "",
              "var level5 =",
              "CALCULATE(",
              "    SUM(Inventory[On Hand Quantity])",
              "    ,FILTER('Inventory','Inventory'[Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 5]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])",
              "",
              "var level6 =",
              "CALCULATE(",
              "    SUM(Inventory[On Hand Quantity])",
              "    ,FILTER('Inventory','Inventory'[Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 6]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])",
              "",
              "var level7 =",
              "CALCULATE(",
              "    SUM(Inventory[On Hand Quantity])",
              "    ,FILTER('Inventory','Inventory'[Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 7]))",
              ")*MAX('Product Hierarchy'[Qty L8])",
              "",
              "var level8 =",
              "CALCULATE(",
              "    SUM(Inventory[On Hand Quantity])",
              "    ,FILTER('Inventory','Inventory'[Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 8]))",
              ")",
              "",
              "RETURN",
              "",
              "SWITCH(",
              "    TRUE()",
              "    ,ISINSCOPE('Product Hierarchy'[Level 7]),level7",
              "    ,ISINSCOPE('Product Hierarchy'[Level 6]),level6",
              "    ,ISINSCOPE('Product Hierarchy'[Level 5]),level5",
              "    ,ISINSCOPE('Product Hierarchy'[Level 4]),level4",
              "    ,ISINSCOPE('Product Hierarchy'[Level 3]),level3",
              "    ,ISINSCOPE('Product Hierarchy'[Level 4]),level2",
              "    ,ISINSCOPE('Product Hierarchy'[Level 1]),level1",
              "    ,ISINSCOPE('Product Hierarchy'[Level 0]),level0",
              "    --,ISINSCOPE('Product Hierarchy'[Level 8]),SELECTEDVALUE('Product Hierarchy'[Level 8])",
              "    ,level8",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "1731468c-4287-474a-8385-543824692251"
          },
          {
            "name": "Open Order Qty",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "var level0 =",
              "CALCULATE(",
              "    SUM('Sales Orders'[Order Quantity])",
              "    ,FILTER('Sales Orders','Sales Orders'[Item ID]=SELECTEDVALUE('Product Hierarchy'[Level 0])&&'Sales Orders'[SO Line Status]=\"O\")",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])*MAX('Product Hierarchy'[Qty L3])*MAX('Product Hierarchy'[Qty L2])*MAX('Product Hierarchy'[Qty L1])",
              "",
              "var level1 =",
              "CALCULATE(",
              "    SUM('Sales Orders'[Order Quantity])",
              "    ,FILTER('Sales Orders','Sales Orders'[Item ID]=SELECTEDVALUE('Product Hierarchy'[Level 1])&&'Sales Orders'[SO Line Status]=\"O\")",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])*MAX('Product Hierarchy'[Qty L3])*MAX('Product Hierarchy'[Qty L2])",
              "",
              "var level2 =",
              "CALCULATE(",
              "    SUM('Sales Orders'[Order Quantity])",
              "    ,FILTER('Sales Orders','Sales Orders'[Item ID]=SELECTEDVALUE('Product Hierarchy'[Level 2])&&'Sales Orders'[SO Line Status]=\"O\")",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])*MAX('Product Hierarchy'[Qty L3])",
              "",
              "var level3 =",
              "CALCULATE(",
              "    SUM('Sales Orders'[Order Quantity])",
              "    ,FILTER('Sales Orders','Sales Orders'[Item ID]=SELECTEDVALUE('Product Hierarchy'[Level 3])&&'Sales Orders'[SO Line Status]=\"O\")",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])",
              "",
              "var level4 =",
              "CALCULATE(",
              "    SUM('Sales Orders'[Order Quantity])",
              "    ,FILTER('Sales Orders','Sales Orders'[Item ID]=SELECTEDVALUE('Product Hierarchy'[Level 4])&&'Sales Orders'[SO Line Status]=\"O\")",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])",
              "",
              "var level5 =",
              "CALCULATE(",
              "    SUM('Sales Orders'[Order Quantity])",
              "    ,FILTER('Sales Orders','Sales Orders'[Item ID]=SELECTEDVALUE('Product Hierarchy'[Level 5])&&'Sales Orders'[SO Line Status]=\"O\")",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])",
              "",
              "var level6 =",
              "CALCULATE(",
              "    SUM('Sales Orders'[Order Quantity])",
              "    ,FILTER('Sales Orders','Sales Orders'[Item ID]=SELECTEDVALUE('Product Hierarchy'[Level 6])&&'Sales Orders'[SO Line Status]=\"O\")",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])",
              "",
              "var level7 =",
              "CALCULATE(",
              "    SUM('Sales Orders'[Order Quantity])",
              "    ,FILTER('Sales Orders','Sales Orders'[Item ID]=SELECTEDVALUE('Product Hierarchy'[Level 7])&&'Sales Orders'[SO Line Status]=\"O\")",
              ")*MAX('Product Hierarchy'[Qty L8])",
              "",
              "var level8 =",
              "CALCULATE(",
              "    SUM('Sales Orders'[Order Quantity])",
              "    ,FILTER('Sales Orders','Sales Orders'[Item ID]=SELECTEDVALUE('Product Hierarchy'[Level 8])&&'Sales Orders'[SO Line Status]=\"O\")",
              ")",
              "",
              "RETURN",
              "",
              "SWITCH(",
              "    TRUE()",
              "    ,ISINSCOPE('Product Hierarchy'[Level 7]),level7",
              "    ,ISINSCOPE('Product Hierarchy'[Level 6]),level6",
              "    ,ISINSCOPE('Product Hierarchy'[Level 5]),level5",
              "    ,ISINSCOPE('Product Hierarchy'[Level 4]),level4",
              "    ,ISINSCOPE('Product Hierarchy'[Level 3]),level3",
              "    ,ISINSCOPE('Product Hierarchy'[Level 4]),level2",
              "    ,ISINSCOPE('Product Hierarchy'[Level 1]),level1",
              "    ,ISINSCOPE('Product Hierarchy'[Level 0]),level0",
              "    --,ISINSCOPE('Product Hierarchy'[Level 8]),SELECTEDVALUE('Product Hierarchy'[Level 8])",
              "    ,level8",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "e43720f5-c761-4a67-87cd-f552b18b6904"
          },
          {
            "name": "ToIssueQty Firm-Planned",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "var chosenlevel =",
              "SWITCH(",
              "    TRUE()",
              "    ,ISINSCOPE('Product Hierarchy'[Level 7]),SELECTEDVALUE('Product Hierarchy'[Level 7])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 6]),SELECTEDVALUE('Product Hierarchy'[Level 6])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 5]),SELECTEDVALUE('Product Hierarchy'[Level 5])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 4]),SELECTEDVALUE('Product Hierarchy'[Level 4])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 3]),SELECTEDVALUE('Product Hierarchy'[Level 3])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 4]),SELECTEDVALUE('Product Hierarchy'[Level 2])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 1]),SELECTEDVALUE('Product Hierarchy'[Level 1])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 0]),SELECTEDVALUE('Product Hierarchy'[Level 0])",
              "    --,ISINSCOPE('Product Hierarchy'[Level 8]),SELECTEDVALUE('Product Hierarchy'[Level 8])",
              "    ,SELECTEDVALUE('Product Hierarchy'[Level 8])",
              ")",
              "",
              "var relatedMOs =",
              "SELECTCOLUMNS(",
              "    FILTER(",
              "        SUMMARIZE(",
              "            'Manufacturing Data'",
              "            ,'Manufacturing Data'[Manufacturing Order ID]",
              "            ,'Manufacturing Data'[MO Build Part ID]",
              "            ,'Manufacturing Data'[MO Status Description]",
              "            ,'Manufacturing Data'[Open Qty]",
              "        )",
              "        ,'Manufacturing Data'[MO Status Description]=\"Firm Planned\"&&'Manufacturing Data'[MO Build Part ID]=chosenlevel&&'Manufacturing Data'[Open Qty]>0",
              "    )",
              "    ,\"MOs\"",
              "    ,'Manufacturing Data'[Manufacturing Order ID]",
              ")",
              "",
              "RETURN",
              "",
              "SUMX(",
              "    FILTER(",
              "        'Manufacturing Requirements'",
              "        ,'Manufacturing Requirements'[Manufacturing Order ID] IN relatedMOs && 'Manufacturing Requirements'[Component Part ID] = SELECTEDVALUE('Product Hierarchy'[Level 8])",
              "    )",
              "    ,'Manufacturing Requirements'[To Issue Quantity]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "4e505620-6889-41b4-ba1b-6604b9772c63"
          },
          {
            "name": "ToIssueQty In-Shop",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "var chosenlevel =",
              "SWITCH(",
              "    TRUE()",
              "    ,ISINSCOPE('Product Hierarchy'[Level 7]),SELECTEDVALUE('Product Hierarchy'[Level 7])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 6]),SELECTEDVALUE('Product Hierarchy'[Level 6])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 5]),SELECTEDVALUE('Product Hierarchy'[Level 5])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 4]),SELECTEDVALUE('Product Hierarchy'[Level 4])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 3]),SELECTEDVALUE('Product Hierarchy'[Level 3])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 4]),SELECTEDVALUE('Product Hierarchy'[Level 2])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 1]),SELECTEDVALUE('Product Hierarchy'[Level 1])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 0]),SELECTEDVALUE('Product Hierarchy'[Level 0])",
              "    --,ISINSCOPE('Product Hierarchy'[Level 8]),SELECTEDVALUE('Product Hierarchy'[Level 8])",
              "    ,SELECTEDVALUE('Product Hierarchy'[Level 8])",
              ")",
              "",
              "var relatedMOs =",
              "SELECTCOLUMNS(",
              "    FILTER(",
              "        SUMMARIZE(",
              "            'Manufacturing Data'",
              "            ,'Manufacturing Data'[Manufacturing Order ID]",
              "            ,'Manufacturing Data'[MO Build Part ID]",
              "            ,'Manufacturing Data'[MO Status Description]",
              "            ,'Manufacturing Data'[Open Qty]",
              "        )",
              "        ,'Manufacturing Data'[MO Status Description]=\"In Shop\"&&'Manufacturing Data'[MO Build Part ID]=chosenlevel&&'Manufacturing Data'[Open Qty]>0",
              "    )",
              "    ,\"MOs\"",
              "    ,'Manufacturing Data'[Manufacturing Order ID]",
              ")",
              "",
              "RETURN",
              "",
              "SUMX(",
              "    FILTER(",
              "        'Manufacturing Requirements'",
              "        ,'Manufacturing Requirements'[Manufacturing Order ID] IN relatedMOs && 'Manufacturing Requirements'[Component Part ID] = SELECTEDVALUE('Product Hierarchy'[Level 8])",
              "    )",
              "    ,'Manufacturing Requirements'[To Issue Quantity]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "65c44089-2ae5-4b10-9c2c-83d6b67fe023"
          },
          {
            "name": "ToIssueQty Released",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "var chosenlevel =",
              "SWITCH(",
              "    TRUE()",
              "    ,ISINSCOPE('Product Hierarchy'[Level 7]),SELECTEDVALUE('Product Hierarchy'[Level 7])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 6]),SELECTEDVALUE('Product Hierarchy'[Level 6])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 5]),SELECTEDVALUE('Product Hierarchy'[Level 5])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 4]),SELECTEDVALUE('Product Hierarchy'[Level 4])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 3]),SELECTEDVALUE('Product Hierarchy'[Level 3])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 4]),SELECTEDVALUE('Product Hierarchy'[Level 2])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 1]),SELECTEDVALUE('Product Hierarchy'[Level 1])",
              "    ,ISINSCOPE('Product Hierarchy'[Level 0]),SELECTEDVALUE('Product Hierarchy'[Level 0])",
              "    --,ISINSCOPE('Product Hierarchy'[Level 8]),SELECTEDVALUE('Product Hierarchy'[Level 8])",
              "    ,SELECTEDVALUE('Product Hierarchy'[Level 8])",
              ")",
              "",
              "var relatedMOs =",
              "SELECTCOLUMNS(",
              "    FILTER(",
              "        SUMMARIZE(",
              "            'Manufacturing Data'",
              "            ,'Manufacturing Data'[Manufacturing Order ID]",
              "            ,'Manufacturing Data'[MO Build Part ID]",
              "            ,'Manufacturing Data'[MO Status Description]",
              "            ,'Manufacturing Data'[Open Qty]",
              "        )",
              "        ,'Manufacturing Data'[MO Status Description]=\"Released\"&&'Manufacturing Data'[MO Build Part ID]=chosenlevel&&'Manufacturing Data'[Open Qty]>0",
              "    )",
              "    ,\"MOs\"",
              "    ,'Manufacturing Data'[Manufacturing Order ID]",
              ")",
              "",
              "RETURN",
              "",
              "SUMX(",
              "    FILTER(",
              "        'Manufacturing Requirements'",
              "        ,'Manufacturing Requirements'[Manufacturing Order ID] IN relatedMOs && 'Manufacturing Requirements'[Component Part ID] = SELECTEDVALUE('Product Hierarchy'[Level 8])",
              "    )",
              "    ,'Manufacturing Requirements'[To Issue Quantity]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "9a28278f-2fcb-4824-ad5b-5172860b0f9a"
          },
          {
            "name": "WIP (Firm Planned) Qty",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "var level0 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"Firm Planned\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 0]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])*MAX('Product Hierarchy'[Qty L3])*MAX('Product Hierarchy'[Qty L2])*MAX('Product Hierarchy'[Qty L1])",
              "",
              "var level1 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"Firm Planned\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 1]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])*MAX('Product Hierarchy'[Qty L3])*MAX('Product Hierarchy'[Qty L2])",
              "",
              "var level2 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"Firm Planned\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 2]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])*MAX('Product Hierarchy'[Qty L3])",
              "",
              "var level3 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"Firm Planned\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 3]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])",
              "",
              "var level4 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"Firm Planned\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 4]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])",
              "",
              "var level5 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"Firm Planned\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 5]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])",
              "",
              "var level6 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"Firm Planned\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 6]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])",
              "",
              "var level7 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"Firm Planned\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 7]))",
              ")*MAX('Product Hierarchy'[Qty L8])",
              "",
              "var level8 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"Firm Planned\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 8]))",
              ")",
              "",
              "RETURN",
              "",
              "SWITCH(",
              "    TRUE()",
              "    ,ISINSCOPE('Product Hierarchy'[Level 7]),level7",
              "    ,ISINSCOPE('Product Hierarchy'[Level 6]),level6",
              "    ,ISINSCOPE('Product Hierarchy'[Level 5]),level5",
              "    ,ISINSCOPE('Product Hierarchy'[Level 4]),level4",
              "    ,ISINSCOPE('Product Hierarchy'[Level 3]),level3",
              "    ,ISINSCOPE('Product Hierarchy'[Level 4]),level2",
              "    ,ISINSCOPE('Product Hierarchy'[Level 1]),level1",
              "    ,ISINSCOPE('Product Hierarchy'[Level 0]),level0",
              "    --,ISINSCOPE('Product Hierarchy'[Level 8]),SELECTEDVALUE('Product Hierarchy'[Level 8])",
              "    ,level8",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "39afaba6-19e3-484a-b2d9-46c71043ad7b"
          },
          {
            "name": "WIP (In shop) Qty",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "var level0 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"In Shop\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 0]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])*MAX('Product Hierarchy'[Qty L3])*MAX('Product Hierarchy'[Qty L2])*MAX('Product Hierarchy'[Qty L1])",
              "",
              "var level1 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"In Shop\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 1]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])*MAX('Product Hierarchy'[Qty L3])*MAX('Product Hierarchy'[Qty L2])",
              "",
              "var level2 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"In Shop\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 2]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])*MAX('Product Hierarchy'[Qty L3])",
              "",
              "var level3 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"In Shop\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 3]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])",
              "",
              "var level4 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"In Shop\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 4]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])",
              "",
              "var level5 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"In Shop\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 5]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])",
              "",
              "var level6 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"In Shop\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 6]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])",
              "",
              "var level7 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"In Shop\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 7]))",
              ")*MAX('Product Hierarchy'[Qty L8])",
              "",
              "var level8 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"In Shop\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 8]))",
              ")",
              "",
              "RETURN",
              "",
              "SWITCH(",
              "    TRUE()",
              "    ,ISINSCOPE('Product Hierarchy'[Level 7]),level7",
              "    ,ISINSCOPE('Product Hierarchy'[Level 6]),level6",
              "    ,ISINSCOPE('Product Hierarchy'[Level 5]),level5",
              "    ,ISINSCOPE('Product Hierarchy'[Level 4]),level4",
              "    ,ISINSCOPE('Product Hierarchy'[Level 3]),level3",
              "    ,ISINSCOPE('Product Hierarchy'[Level 4]),level2",
              "    ,ISINSCOPE('Product Hierarchy'[Level 1]),level1",
              "    ,ISINSCOPE('Product Hierarchy'[Level 0]),level0",
              "    --,ISINSCOPE('Product Hierarchy'[Level 8]),SELECTEDVALUE('Product Hierarchy'[Level 8])",
              "    ,level8",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "89b39ee6-aeb9-47bf-84f9-b480904e4c92"
          },
          {
            "name": "WIP (Released) Qty",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "var level0 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"Released\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 0]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])*MAX('Product Hierarchy'[Qty L3])*MAX('Product Hierarchy'[Qty L2])*MAX('Product Hierarchy'[Qty L1])",
              "",
              "var level1 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"Released\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 1]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])*MAX('Product Hierarchy'[Qty L3])*MAX('Product Hierarchy'[Qty L2])",
              "",
              "var level2 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"Released\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 2]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])*MAX('Product Hierarchy'[Qty L3])",
              "",
              "var level3 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"Released\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 3]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])*MAX('Product Hierarchy'[Qty L4])",
              "",
              "var level4 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"Released\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 4]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])*MAX('Product Hierarchy'[Qty L5])",
              "",
              "var level5 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"Released\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 5]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])*MAX('Product Hierarchy'[Qty L6])",
              "",
              "var level6 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"Released\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 6]))",
              ")*MAX('Product Hierarchy'[Qty L8])*MAX('Product Hierarchy'[Qty L7])",
              "",
              "var level7 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"Released\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 7]))",
              ")*MAX('Product Hierarchy'[Qty L8])",
              "",
              "var level8 =",
              "CALCULATE(",
              "    SUM('Manufacturing Data'[Open Qty])",
              "    ,FILTER('Manufacturing Data','Manufacturing Data'[MO Status Description]=\"Released\"&&'Manufacturing Data'[MO Build Part ID]=SELECTEDVALUE('Product Hierarchy'[Level 8]))",
              ")",
              "",
              "RETURN",
              "",
              "SWITCH(",
              "    TRUE()",
              "    ,ISINSCOPE('Product Hierarchy'[Level 7]),level7",
              "    ,ISINSCOPE('Product Hierarchy'[Level 6]),level6",
              "    ,ISINSCOPE('Product Hierarchy'[Level 5]),level5",
              "    ,ISINSCOPE('Product Hierarchy'[Level 4]),level4",
              "    ,ISINSCOPE('Product Hierarchy'[Level 3]),level3",
              "    ,ISINSCOPE('Product Hierarchy'[Level 4]),level2",
              "    ,ISINSCOPE('Product Hierarchy'[Level 1]),level1",
              "    ,ISINSCOPE('Product Hierarchy'[Level 0]),level0",
              "    --,ISINSCOPE('Product Hierarchy'[Level 8]),SELECTEDVALUE('Product Hierarchy'[Level 8])",
              "    ,level8",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "1a9b7762-cb96-4925-9fb2-79c3ed981ab3"
          },
          {
            "name": "Supply",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "var supply =",
              "(([On-Hand Qty]+[WIP (In Shop) Qty]+[WIP (Firm Planned) Qty]+[WIP (Released) Qty])*[Cumulative Qty])-([ToIssueQty In-Shop]+[ToIssueQty Firm-Planned]+[ToIssueQty Released])",
              "",
              "RETURN",
              "",
              "supply"
            ],
            "formatString": "#,0",
            "lineageTag": "da21af7d-fef9-4319-b408-9a93c147cdf5"
          },
          {
            "name": "Demand",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "var demand =",
              "(([Open Order Qty]+[MPS Qty])*[Cumulative Qty])+[ToIssueQty In-Shop]+[ToIssueQty Firm-Planned]+[ToIssueQty Released]",
              "",
              "RETURN",
              "",
              "demand"
            ],
            "formatString": "#,0",
            "lineageTag": "1b73dbaf-1ed9-425b-943a-f76d8f0383c1"
          },
          {
            "name": "Balance",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[Supply]-[Demand]",
            "formatString": "#,0",
            "lineageTag": "aa9dfec2-43dd-455f-a82b-eca7ce53288b"
          },
          {
            "name": "Cumulative Supply",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "var supplyL0 =",
              "",
              "    SUMMARIZE(",
              "        'Product Hierarchy'",
              "        ,'Product Hierarchy'[Level 0]",
              "        ,\"supplyL0\"",
              "        ,(([On-Hand Qty]+[WIP (In Shop) Qty]+[WIP (Firm Planned) Qty]+[WIP (Released) Qty])*[Cumulative Qty])-([ToIssueQty In-Shop]+[ToIssueQty Firm-Planned]+[ToIssueQty Released])",
              "    )",
              "",
              "var supplyL1 =",
              "",
              "    SUMMARIZE(",
              "        'Product Hierarchy'",
              "        ,'Product Hierarchy'[Level 1]",
              "        ,\"supplyL1\"",
              "        ,(([On-Hand Qty]+[WIP (In Shop) Qty]+[WIP (Firm Planned) Qty]+[WIP (Released) Qty])*[Cumulative Qty])-([ToIssueQty In-Shop]+[ToIssueQty Firm-Planned]+[ToIssueQty Released])",
              "    )",
              "",
              "var supplyL2 =",
              "",
              "    SUMMARIZE(",
              "        'Product Hierarchy'",
              "        ,'Product Hierarchy'[Level 2]",
              "        ,\"supplyL2\"",
              "        ,(([On-Hand Qty]+[WIP (In Shop) Qty]+[WIP (Firm Planned) Qty]+[WIP (Released) Qty])*[Cumulative Qty])-([ToIssueQty In-Shop]+[ToIssueQty Firm-Planned]+[ToIssueQty Released])",
              "    )",
              "",
              "var supplyL3 =",
              "",
              "    SUMMARIZE(",
              "        'Product Hierarchy'",
              "        ,'Product Hierarchy'[Level 3]",
              "        ,\"supplyL3\"",
              "        ,(([On-Hand Qty]+[WIP (In Shop) Qty]+[WIP (Firm Planned) Qty]+[WIP (Released) Qty])*[Cumulative Qty])-([ToIssueQty In-Shop]+[ToIssueQty Firm-Planned]+[ToIssueQty Released])",
              "    )",
              "",
              "var supplyL4 =",
              "",
              "    SUMMARIZE(",
              "        'Product Hierarchy'",
              "        ,'Product Hierarchy'[Level 4]",
              "        ,\"supplyL4\"",
              "        ,(([On-Hand Qty]+[WIP (In Shop) Qty]+[WIP (Firm Planned) Qty]+[WIP (Released) Qty])*[Cumulative Qty])-([ToIssueQty In-Shop]+[ToIssueQty Firm-Planned]+[ToIssueQty Released])",
              "    )",
              "",
              "var supplyL5 =",
              "",
              "    SUMMARIZE(",
              "        'Product Hierarchy'",
              "        ,'Product Hierarchy'[Level 5]",
              "        ,\"supplyL5\"",
              "        ,(([On-Hand Qty]+[WIP (In Shop) Qty]+[WIP (Firm Planned) Qty]+[WIP (Released) Qty])*[Cumulative Qty])-([ToIssueQty In-Shop]+[ToIssueQty Firm-Planned]+[ToIssueQty Released])",
              "    )",
              "",
              "var supplyL6 =",
              "",
              "    SUMMARIZE(",
              "        'Product Hierarchy'",
              "        ,'Product Hierarchy'[Level 6]",
              "        ,\"supplyL6\"",
              "        ,(([On-Hand Qty]+[WIP (In Shop) Qty]+[WIP (Firm Planned) Qty]+[WIP (Released) Qty])*[Cumulative Qty])-([ToIssueQty In-Shop]+[ToIssueQty Firm-Planned]+[ToIssueQty Released])",
              "    )",
              "",
              "var supplyL7 =",
              "",
              "    SUMMARIZE(",
              "        'Product Hierarchy'",
              "        ,'Product Hierarchy'[Level 7]",
              "        ,\"supplyL7\"",
              "        ,(([On-Hand Qty]+[WIP (In Shop) Qty]+[WIP (Firm Planned) Qty]+[WIP (Released) Qty])*[Cumulative Qty])-([ToIssueQty In-Shop]+[ToIssueQty Firm-Planned]+[ToIssueQty Released])",
              "    )",
              "",
              "var supplyL8 =",
              "",
              "    SUMMARIZE(",
              "        'Product Hierarchy'",
              "        ,'Product Hierarchy'[Level 8]",
              "        ,\"supplyL8\"",
              "        ,(([On-Hand Qty]+[WIP (In Shop) Qty]+[WIP (Firm Planned) Qty]+[WIP (Released) Qty])*[Cumulative Qty])-([ToIssueQty In-Shop]+[ToIssueQty Firm-Planned]+[ToIssueQty Released])",
              "    )",
              "",
              "RETURN",
              "",
              "SUMX(",
              "    supplyL0",
              "    ,[supplyL0]",
              ")",
              "+",
              "SUMX(",
              "    supplyL1",
              "    ,[supplyL1]",
              ")",
              "+",
              "SUMX(",
              "    supplyL2",
              "    ,[supplyL2]",
              ")",
              "+",
              "SUMX(",
              "    supplyL3",
              "    ,[supplyL3]",
              ")",
              "+",
              "SUMX(",
              "    supplyL4",
              "    ,[supplyL4]",
              ")",
              "+",
              "SUMX(",
              "    supplyL5",
              "    ,[supplyL5]",
              ")",
              "+",
              "SUMX(",
              "    supplyL6",
              "    ,[supplyL6]",
              ")",
              "+",
              "SUMX(",
              "    supplyL7",
              "    ,[supplyL7]",
              ")",
              "+",
              "SUMX(",
              "    supplyL8",
              "    ,[supplyL8]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "64e35e48-30b1-4d82-9461-e952480eab6e"
          },
          {
            "name": "Cumulative Demand",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "var demandL0 =",
              "",
              "    SUMMARIZE(",
              "        'Product Hierarchy'",
              "        ,'Product Hierarchy'[Level 0]",
              "        ,\"demandL0\"",
              "        ,(([Open Order Qty]+[MPS Qty])*[Cumulative Qty])+[ToIssueQty In-Shop]+[ToIssueQty Firm-Planned]+[ToIssueQty Released]",
              "    )",
              "",
              "var demandL1 =",
              "",
              "    SUMMARIZE(",
              "        'Product Hierarchy'",
              "        ,'Product Hierarchy'[Level 1]",
              "        ,\"demandL1\"",
              "        ,(([Open Order Qty]+[MPS Qty])*[Cumulative Qty])+[ToIssueQty In-Shop]+[ToIssueQty Firm-Planned]+[ToIssueQty Released]",
              "    )",
              "",
              "var demandL2 =",
              "",
              "    SUMMARIZE(",
              "        'Product Hierarchy'",
              "        ,'Product Hierarchy'[Level 2]",
              "        ,\"demandL2\"",
              "        ,(([Open Order Qty]+[MPS Qty])*[Cumulative Qty])+[ToIssueQty In-Shop]+[ToIssueQty Firm-Planned]+[ToIssueQty Released]",
              "    )",
              "",
              "var demandL3 =",
              "",
              "    SUMMARIZE(",
              "        'Product Hierarchy'",
              "        ,'Product Hierarchy'[Level 3]",
              "        ,\"demandL3\"",
              "        ,(([Open Order Qty]+[MPS Qty])*[Cumulative Qty])+[ToIssueQty In-Shop]+[ToIssueQty Firm-Planned]+[ToIssueQty Released]",
              "    )",
              "",
              "var demandL4 =",
              "",
              "    SUMMARIZE(",
              "        'Product Hierarchy'",
              "        ,'Product Hierarchy'[Level 4]",
              "        ,\"demandL4\"",
              "        ,(([Open Order Qty]+[MPS Qty])*[Cumulative Qty])+[ToIssueQty In-Shop]+[ToIssueQty Firm-Planned]+[ToIssueQty Released]",
              "    )",
              "",
              "var demandL5 =",
              "",
              "    SUMMARIZE(",
              "        'Product Hierarchy'",
              "        ,'Product Hierarchy'[Level 5]",
              "        ,\"demandL5\"",
              "        ,(([Open Order Qty]+[MPS Qty])*[Cumulative Qty])+[ToIssueQty In-Shop]+[ToIssueQty Firm-Planned]+[ToIssueQty Released]",
              "    )",
              "",
              "var demandL6 =",
              "",
              "    SUMMARIZE(",
              "        'Product Hierarchy'",
              "        ,'Product Hierarchy'[Level 6]",
              "        ,\"demandL6\"",
              "        ,(([Open Order Qty]+[MPS Qty])*[Cumulative Qty])+[ToIssueQty In-Shop]+[ToIssueQty Firm-Planned]+[ToIssueQty Released]",
              "    )",
              "",
              "var demandL7 =",
              "",
              "    SUMMARIZE(",
              "        'Product Hierarchy'",
              "        ,'Product Hierarchy'[Level 7]",
              "        ,\"demandL7\"",
              "        ,(([Open Order Qty]+[MPS Qty])*[Cumulative Qty])+[ToIssueQty In-Shop]+[ToIssueQty Firm-Planned]+[ToIssueQty Released]",
              "    )",
              "",
              "var demandL8 =",
              "",
              "    SUMMARIZE(",
              "        'Product Hierarchy'",
              "        ,'Product Hierarchy'[Level 8]",
              "        ,\"demandL8\"",
              "        ,(([Open Order Qty]+[MPS Qty])*[Cumulative Qty])+[ToIssueQty In-Shop]+[ToIssueQty Firm-Planned]+[ToIssueQty Released]",
              "    )",
              "",
              "RETURN",
              "",
              "SUMX(",
              "    demandL0",
              "    ,[demandL0]",
              ")",
              "+",
              "SUMX(",
              "    demandL1",
              "    ,[demandL1]",
              ")",
              "+",
              "SUMX(",
              "    demandL2",
              "    ,[demandL2]",
              ")",
              "+",
              "SUMX(",
              "    demandL3",
              "    ,[demandL3]",
              ")",
              "+",
              "SUMX(",
              "    demandL4",
              "    ,[demandL4]",
              ")",
              "+",
              "SUMX(",
              "    demandL5",
              "    ,[demandL5]",
              ")",
              "+",
              "SUMX(",
              "    demandL6",
              "    ,[demandL6]",
              ")",
              "+",
              "SUMX(",
              "    demandL7",
              "    ,[demandL7]",
              ")",
              "+",
              "SUMX(",
              "    demandL8",
              "    ,[demandL8]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "4889bc3c-0698-41ed-a2fb-cbf513734bef"
          },
          {
            "name": "Cumulative Balance",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[Cumulative Supply]-[Cumulative Demand]",
            "formatString": "#,0",
            "lineageTag": "89213c5c-cfed-4abe-974a-6c2b68d47526"
          }
        ],
        "partitions": [
          {
            "name": "Supply - Demand Measures-76f01cff-b893-46c8-8af7-9692842ff6f2",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Time Intelligence",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "Current",
              "expression": "SELECTEDMEASURE ()",
              "ordinal": 0
            },
            {
              "name": "Last Year Same Period",
              "expression": [
                "VAR periodlastyear =",
                "    SWITCH (",
                "        TRUE (),",
                "        ISFILTERED ( 'Calendar'[Date] ), SELECTEDVALUE ( 'Calendar'[DateYYYYMMdd] ) - 10000,",
                "        ISFILTERED ( 'Calendar'[Fiscal Year-Week] ), SELECTEDVALUE ( 'Calendar'[Fiscal Year-Week Order] ) - 100,",
                "        ISFILTERED ( 'Calendar'[Fiscal Year-Month] ), SELECTEDVALUE ( 'Calendar'[Fiscal Year-Month Order] ) - 100,",
                "        ISFILTERED ( 'Calendar'[Fiscal Year-Quarter] ), SELECTEDVALUE ( 'Calendar'[Fiscal Year-Quarter Order] ) - 10,",
                "        ISFILTERED ( 'Calendar'[Fiscal Year] ), SELECTEDVALUE ( 'Calendar'[Fiscal Year] ) - 1",
                "    )",
                "RETURN",
                "    CALCULATE (",
                "        SELECTEDMEASURE(),",
                "        ALL ( 'Calendar' ),",
                "        SWITCH (",
                "            TRUE (),",
                "            HASONEVALUE ( 'Calendar'[Date] ), 'Calendar'[DateYYYYMMdd] = periodlastyear,",
                "            HASONEVALUE ( 'Calendar'[Fiscal Year-Week] ), 'Calendar'[Fiscal Year-Week Order] = periodlastyear,",
                "            HASONEVALUE ( 'Calendar'[Fiscal Year-Month] ), 'Calendar'[Fiscal Year-Month Order] = periodlastyear,",
                "            HASONEVALUE ( 'Calendar'[Fiscal Year-Quarter] ), 'Calendar'[Fiscal Year-Quarter Order] = periodlastyear,",
                "            HASONEVALUE ( 'Calendar'[Fiscal Year] ), 'Calendar'[Fiscal Year] = periodlastyear",
                "        )",
                "    )"
              ],
              "ordinal": 1
            },
            {
              "name": "Fiscal YTD",
              "expression": [
                "VAR selecteddate =",
                "    TODAY ()",
                "VAR currentperiod =",
                "    CALCULATE (",
                "        MAX ( 'Calendar'[Fiscal Year] ),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Date] = selecteddate",
                "    )",
                "VAR selectedperiod =",
                "    SELECTEDVALUE ( 'Calendar'[Fiscal Year] )",
                "VAR startofcurrentperiod =",
                "    CALCULATE (",
                "        MIN ( 'Calendar'[Date] ),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Fiscal Year] = currentperiod",
                "    )",
                "VAR mindateselectedperiod =",
                "    CALCULATE (",
                "        MIN ( 'Calendar'[Date] ),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Fiscal Year] = selectedperiod",
                "    )",
                "VAR endofselectedperiod =",
                "    CALCULATE (",
                "        MAX ( 'Calendar'[Date] ),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Fiscal Year] = selectedperiod",
                "    )",
                "VAR nrofdaysuntiltoday =",
                "    DATEDIFF ( startofcurrentperiod, selecteddate, DAY )",
                "VAR untiltheday =",
                "    MIN ( mindateselectedperiod + nrofdaysuntiltoday, endofselectedperiod )",
                "RETURN",
                "    CALCULATE (",
                "        SELECTEDMEASURE (),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Date] >= mindateselectedperiod",
                "            && 'Calendar'[Date] <= untiltheday",
                "    )"
              ],
              "ordinal": 3
            },
            {
              "name": "Fiscal QTD",
              "expression": [
                "VAR selecteddate =",
                "    TODAY ()",
                "VAR currentperiod =",
                "    CALCULATE (",
                "        MAX ( 'Calendar'[Fiscal Year-Quarter] ),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Date] = selecteddate",
                "    )",
                "VAR selectedperiod =",
                "    SELECTEDVALUE ( 'Calendar'[Fiscal Year-Quarter] )",
                "VAR startofcurrentperiod =",
                "    CALCULATE (",
                "        MIN ( 'Calendar'[Date] ),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Fiscal Year-Quarter] = currentperiod",
                "    )",
                "VAR mindateselectedperiod =",
                "    CALCULATE (",
                "        MIN ( 'Calendar'[Date] ),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Fiscal Year-Quarter] = selectedperiod",
                "    )",
                "VAR endofselectedperiod =",
                "    CALCULATE (",
                "        MAX ( 'Calendar'[Date] ),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Fiscal Year-Quarter] = selectedperiod",
                "    )",
                "VAR nrofdaysuntiltoday =",
                "    DATEDIFF ( startofcurrentperiod, selecteddate, DAY )",
                "VAR untiltheday =",
                "    MIN ( mindateselectedperiod + nrofdaysuntiltoday, endofselectedperiod )",
                "RETURN",
                "    CALCULATE (",
                "        SELECTEDMEASURE (),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Date] >= mindateselectedperiod",
                "            && 'Calendar'[Date] <= untiltheday",
                "    )"
              ],
              "ordinal": 4
            },
            {
              "name": "Fiscal MTD",
              "expression": [
                "VAR selecteddate =",
                "    TODAY ()",
                "VAR currentperiod =",
                "    CALCULATE (",
                "        MAX ( 'Calendar'[Fiscal Year-Month] ),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Date] = selecteddate",
                "    )",
                "VAR selectedperiod =",
                "    SELECTEDVALUE ( 'Calendar'[Fiscal Year-Month] )",
                "VAR startofcurrentperiod =",
                "    CALCULATE (",
                "        MIN ( 'Calendar'[Date] ),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Fiscal Year-Month] = currentperiod",
                "    )",
                "VAR mindateselectedperiod =",
                "    CALCULATE (",
                "        MIN ( 'Calendar'[Date] ),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Fiscal Year-Month] = selectedperiod",
                "    )",
                "VAR endofselectedperiod =",
                "    CALCULATE (",
                "        MAX ( 'Calendar'[Date] ),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Fiscal Year-Month] = selectedperiod",
                "    )",
                "VAR nrofdaysuntiltoday =",
                "    DATEDIFF ( startofcurrentperiod, selecteddate, DAY )",
                "VAR untiltheday =",
                "    MIN ( mindateselectedperiod + nrofdaysuntiltoday, endofselectedperiod )",
                "RETURN",
                "    CALCULATE (",
                "        SELECTEDMEASURE (),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Date] >= mindateselectedperiod",
                "            && 'Calendar'[Date] <= untiltheday",
                "    )"
              ],
              "ordinal": 5
            },
            {
              "name": "Fiscal WTD",
              "expression": [
                "VAR selecteddate =",
                "    TODAY ()",
                "VAR currentperiod =",
                "    CALCULATE (",
                "        MAX ( 'Calendar'[Fiscal Year-Week] ),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Date] = selecteddate",
                "    )",
                "VAR selectedperiod =",
                "    SELECTEDVALUE ( 'Calendar'[Fiscal Year-Week] )",
                "VAR startofcurrentperiod =",
                "    CALCULATE (",
                "        MIN ( 'Calendar'[Date] ),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Fiscal Year-Week] = currentperiod",
                "    )",
                "VAR mindateselectedperiod =",
                "    CALCULATE (",
                "        MIN ( 'Calendar'[Date] ),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Fiscal Year-Week] = selectedperiod",
                "    )",
                "VAR endofselectedperiod =",
                "    CALCULATE (",
                "        MAX ( 'Calendar'[Date] ),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Fiscal Year-Week] = selectedperiod",
                "    )",
                "VAR nrofdaysuntiltoday =",
                "    DATEDIFF ( startofcurrentperiod, selecteddate, DAY )",
                "VAR untiltheday =",
                "    MIN ( mindateselectedperiod + nrofdaysuntiltoday, endofselectedperiod )",
                "RETURN",
                "    CALCULATE (",
                "        SELECTEDMEASURE (),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Date] >= mindateselectedperiod",
                "            && 'Calendar'[Date] <= untiltheday",
                "    )"
              ],
              "ordinal": 6
            },
            {
              "name": "Variance %",
              "expression": [
                "VAR periodlastyear =",
                "    SWITCH (",
                "        TRUE (),",
                "        ISFILTERED ( 'Calendar'[Date] ), SELECTEDVALUE ( 'Calendar'[DateYYYYMMdd] ) - 10000,",
                "        ISFILTERED ( 'Calendar'[Fiscal Year-Week] ), SELECTEDVALUE ( 'Calendar'[Fiscal Year-Week Order] ) - 100,",
                "        ISFILTERED ( 'Calendar'[Fiscal Year-Month] ), SELECTEDVALUE ( 'Calendar'[Fiscal Year-Month Order] ) - 100,",
                "        ISFILTERED ( 'Calendar'[Fiscal Year-Quarter] ), SELECTEDVALUE ( 'Calendar'[Fiscal Year-Quarter Order] ) - 10,",
                "        ISFILTERED ( 'Calendar'[Fiscal Year] ), SELECTEDVALUE ( 'Calendar'[Fiscal Year] ) - 1",
                "    )",
                "RETURN",
                "    DIVIDE (",
                "        SELECTEDMEASURE (),",
                "        CALCULATE (",
                "            SELECTEDMEASURE (),",
                "            ALL ( 'Calendar' ),",
                "            SWITCH (",
                "                TRUE (),",
                "                HASONEVALUE ( 'Calendar'[Date] ), 'Calendar'[DateYYYYMMdd] = periodlastyear,",
                "                HASONEVALUE ( 'Calendar'[Fiscal Year-Week] ), 'Calendar'[Fiscal Year-Week Order] = periodlastyear,",
                "                HASONEVALUE ( 'Calendar'[Fiscal Year-Month] ), 'Calendar'[Fiscal Year-Month Order] = periodlastyear,",
                "                HASONEVALUE ( 'Calendar'[Fiscal Year-Quarter] ), 'Calendar'[Fiscal Year-Quarter Order] = periodlastyear,",
                "                HASONEVALUE ( 'Calendar'[Fiscal Year] ), 'Calendar'[Fiscal Year] = periodlastyear",
                "            )",
                "        )",
                "    )"
              ],
              "formatStringDefinition": {
                "expression": "\"0.00%\""
              },
              "ordinal": 2
            },
            {
              "name": "Running Total YTD",
              "expression": [
                "VAR maxdate =",
                "    MAX ( 'Calendar'[Date] )",
                "RETURN",
                "    CALCULATE (",
                "        SELECTEDMEASURE (),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Date] <= maxdate,",
                "        VALUES ( 'Calendar'[Fiscal Year] )",
                "    )"
              ],
              "ordinal": 7
            },
            {
              "name": "Running Total QTD",
              "expression": [
                "VAR maxdate =",
                "    MAX ( 'Calendar'[Date] )",
                "RETURN",
                "    CALCULATE (",
                "        SELECTEDMEASURE (),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Date] <= maxdate,",
                "        VALUES ( 'Calendar'[Fiscal Year-Quarter] )",
                "    )"
              ],
              "ordinal": 8
            },
            {
              "name": "Runnning Total MTD",
              "expression": [
                "VAR maxdate =",
                "    MAX ( 'Calendar'[Date] )",
                "RETURN",
                "    CALCULATE (",
                "        SELECTEDMEASURE (),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Date] <= maxdate,",
                "        VALUES ( 'Calendar'[Fiscal Year-Month] )",
                "    )"
              ],
              "ordinal": 9
            },
            {
              "name": "Running Total WTD",
              "expression": [
                "VAR maxdate =",
                "    MAX ( 'Calendar'[Date] )",
                "RETURN",
                "    CALCULATE (",
                "        SELECTEDMEASURE (),",
                "        ALL ( 'Calendar' ),",
                "        'Calendar'[Date] <= maxdate,",
                "        VALUES ( 'Calendar'[Fiscal Year-Week] )",
                "    )"
              ],
              "ordinal": 10
            }
          ]
        },
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "a26ef2af-70ce-489e-a38c-e49dd57ad0b6",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "9692da68-fea7-444a-a9b4-bcc021a82f10",
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "33b461f3-fb30-4542-bd4c-3e7a0b0ffa4b",
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Warehouse",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Warehouse Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae21e708-65d2-4dcf-82f7-61b9a5cda1ff",
            "sourceColumn": "Warehouse Address",
            "summarizeBy": "none"
          },
          {
            "name": "Warehouse City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "deaea09b-8c9b-43c7-a2e5-573a7115a19e",
            "sourceColumn": "Warehouse City",
            "summarizeBy": "none"
          },
          {
            "name": "Warehouse Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b22bd53-c8f0-40a6-ba4c-290ccb943652",
            "sourceColumn": "Warehouse Country",
            "summarizeBy": "none"
          },
          {
            "name": "Warehouse Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec30b454-56c1-4788-a036-70f5998f7fee",
            "sourceColumn": "Warehouse Description",
            "summarizeBy": "none"
          },
          {
            "name": "Warehouse ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35a002da-3d6d-4585-9385-1e83f24d12cf",
            "sourceColumn": "Warehouse ID",
            "summarizeBy": "none"
          },
          {
            "name": "Warehouse Postal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "317a507d-38f5-4bff-a111-ab93428f2c59",
            "sourceColumn": "Warehouse Postal Code",
            "summarizeBy": "none"
          },
          {
            "name": "Warehouse Ship ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da43db93-df29-4f62-9e91-4e00e49f5fbd",
            "sourceColumn": "Warehouse Ship ID",
            "summarizeBy": "none"
          },
          {
            "name": "Warehouse State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "522519f2-7ce2-4358-8e2a-a98bb1d640f8",
            "sourceColumn": "Warehouse State",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "30b54cef-f4c1-4591-bdfe-fbe10d361bbc",
        "partitions": [
          {
            "name": "Warehouse-7c0ad113-9ce5-4c83-a118-1f3b7a009bac",
            "mode": "import",
            "queryGroup": "Deltek",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"cae-hc-cace-synapse-sbx-dataanalytics.sql.azuresynapse.net\", \"AnalyticsSQLPool\"),",
                "    deltek_Warehouses = Source{[Schema=\"deltek\",Item=\"Warehouses\"]}[Data]",
                "in",
                "    deltek_Warehouses"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}